### ISSUE TITLE
Calibration upload eebecb

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#1000]
Calibration images were uploaded to the directory that starts with “`eebecb_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

**Comment by tuxfanx** [comment]
@ uploader: Unfortunately the picture is not suitable for calibration. Please [read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how pictures have to be taken.

**Comment by tuxfanx** [comment]
calibration data are completely included in lensfuns database
