### ISSUE TITLE
Different correction applied by Hugin and lensfun

### ISSUE THREAD

**Issue by boeleman** [lensfun/lensfun#1002]
Hello,

This finding came about because I am trying to create a correction profile for a shift lens. I created a panorama of a modern building with straight horizontal lines by taking photos in the most left position, middle position and most right position and stitching them together. I would like to create a distortion and tca profile for this composite image so I can apply it to other panoramas made in the same way.

Following the lensfun tutorial I found the lens distortion parameters using Hugin and when I apply these parameters in Hugin I get a straight lines. However, when I apply these parameters in either Darktable, Rawtherapee, or the Gimp using a lensfun xml file I created using the python script, the lines are not straight. Am I using lensfun for something it was not designed to do or is this a bug?

Thanks,

Arnout

**Comment by junkyardsparkle** [comment]
That's certainly not what I would call a *normal* use case. ;-) Is there some reason you can't get what you want directly from Hugin by choosing an appropriate output projection (i.e. rectilinear for straight lines)?

**Comment by boeleman** [comment]
As a workaround I could use the distortion parameters I computed using Hugin, store them in an ini file, and apply them to other panoramas in Hugin. However, it seems to me that using lensfun should work.

**Comment by junkyardsparkle** [comment]
I was assuming you were performing the original stitching in Hugin, in which case the typical workflow would involve using lensfun prior to stitching (if at all). If this isn't the case and you're using a method of stitching that doesn't do any correction, and you really want to avoid Hugin in the workflow, well... I guess the first thing to check would be the crop factor being used by Hugin vs the one used by darktable etc. The crop factor associated with the camera body will no longer be correct in this case.

**Comment by junkyardsparkle** [comment]
Probably the best approach, once you know the correct crop factor for this larger "virtual" sensor, would be to add a camera profile with a unique name ("myShiftcam" or whatever) for make, model, and mount, and similarly for the lens profile, using the same mount. You could then associate these as if they were a fixed-lens camera, and manually selecting the "virtual" camera in darktable should automatically select the lens. For examples look at, for instance, [the actioncam profiles](https://github.com/lensfun/lensfun/blob/master/data/db/actioncams.xml).

**Comment by boeleman** [comment]
Thanks for pointing me to the actioncam profiles! When I added the right aspect ratio to my panorama lens-profile the correction was correct.
