### ISSUE TITLE
Adapted Lens: Sigma 150-600 and MC-11 on Sony camera

### ISSUE THREAD

**Issue by abhijit86k** [lensfun/lensfun#1003]
I'm using a Sigma 150-600 Canon Mount lens on a sony body with the officially supported Sigma MC-11 adapter. exiv2 correctly recognises the lens but I think it does not know that this lens+body commbination is allowed. I'm not sure what is the best way to fix this - guidance is appreciated. I am willing to send in a patch / fix.

**Comment by junkyardsparkle** [comment]
You can tell your local lensfun to consider these mounts to be "compatible" by adding an adapter entry; see https://lensfun.github.io/manual/v0.3.2/lensfun-add-adapter.html

**Comment by tuxfanx** [comment]
issue completed
