### ISSUE TITLE
Complete profile for Sigma 20mm F1.4 DG HSM | Art 015

### ISSUE THREAD

**Issue by quister** [lensfun/lensfun#1006]
Hello, this lens is currently missing vignetting data in the dev lens list. Here is a complete profile:

<lensdatabase>

    <lens>
        <maker>Sigma</maker>
        <model>20mm F1.4 DG HSM | Art 015</model>
        <mount>Canon EF</mount>
        <cropfactor>1</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="20" a="0.00311138529694815" b="-0.0194138067857546" c="0.00615645932381851"/>
            <tca model="poly3" focal="20" vr="1.0000855" vb="1.0000273"/>
            <tca model="poly3" focal="20" vr="1.0000881" vb="1.0000149"/>
            <tca model="poly3" focal="20" vr="1.0001081" vb="1.0000040"/>
            <vignetting model="pa" focal="20" aperture="1.4" distance="0.276" k1="-1.7357" k2="1.5419" k3="-0.6319"/>
            <vignetting model="pa" focal="20" aperture="1.4" distance="0.5" k1="-1.7566" k2="1.7472" k3="-0.8031"/>
            <vignetting model="pa" focal="20" aperture="1.4" distance="1.6" k1="-1.7470" k2="1.7744" k3="-0.8381"/>
            <vignetting model="pa" focal="20" aperture="1.4" distance="1000" k1="-1.7410" k2="1.7755" k3="-0.8473"/>
            <vignetting model="pa" focal="20" aperture="2" distance="0.276" k1="-0.0046" k2="-1.6103" k3="0.9289"/>
            <vignetting model="pa" focal="20" aperture="2" distance="0.5" k1="-0.0981" k2="-1.1272" k3="0.5654"/>
            <vignetting model="pa" focal="20" aperture="2" distance="1.6" k1="-0.1585" k2="-0.8932" k3="0.3937"/>
            <vignetting model="pa" focal="20" aperture="2" distance="1000" k1="-0.1747" k2="-0.8430" k3="0.3539"/>
            <vignetting model="pa" focal="20" aperture="2.8" distance="0.276" k1="-0.2093" k2="0.1386" k3="-0.3844"/>
            <vignetting model="pa" focal="20" aperture="2.8" distance="0.5" k1="-0.3635" k2="0.6001" k3="-0.6831"/>
            <vignetting model="pa" focal="20" aperture="2.8" distance="1.6" k1="-0.3792" k2="0.6087" k3="-0.6852"/>
            <vignetting model="pa" focal="20" aperture="2.8" distance="1000" k1="-0.3645" k2="0.5511" k3="-0.6448"/>
            <vignetting model="pa" focal="20" aperture="4" distance="0.276" k1="-0.3453" k2="0.4743" k3="-0.3294"/>
            <vignetting model="pa" focal="20" aperture="4" distance="0.5" k1="-0.4423" k2="0.7908" k3="-0.6093"/>
            <vignetting model="pa" focal="20" aperture="4" distance="1.6" k1="-0.4808" k2="0.9521" k3="-0.7929"/>
            <vignetting model="pa" focal="20" aperture="4" distance="1000" k1="-0.4665" k2="0.9079" k3="-0.7732"/>
            <vignetting model="pa" focal="20" aperture="16" distance="0.276" k1="-0.2916" k2="0.1724" k3="-0.0238"/>
            <vignetting model="pa" focal="20" aperture="16" distance="0.5" k1="-0.3208" k2="0.2142" k3="-0.0411"/>
            <vignetting model="pa" focal="20" aperture="16" distance="1.6" k1="-0.3321" k2="0.2279" k3="-0.0454"/>
            <vignetting model="pa" focal="20" aperture="16" distance="1000" k1="-0.3290" k2="0.2077" k3="-0.0287"/>
        </calibration>
    </lens>

</lensdatabase>

**Comment by uchrisu** [comment]
Do you have the original raw files for verification?

**Comment by tuxfanx** [comment]
added vignetting data from this issue to Sigma 20mm F1.4 DG HSM | A
lens data are now complete
