### ISSUE TITLE
Lens calibration for Canon PowerShot A590 IS

### ISSUE THREAD

**Issue by RonaldNiberg** [lensfun/lensfun#1021]
Lens calibration. Missing profile. PTLens has it. The only one that is working one. But it only works with tiff and jpg.
Camera: Canon PowerShot A590 IS Reported 
Lens: 5.8-23.2 mm f/2.6-5.5
With CHDK
[CRW_1236.zip](https://github.com/lensfun/lensfun/files/3753384/CRW_1236.zip)
[CRW_1232.zip](https://github.com/lensfun/lensfun/files/3753366/CRW_1232.zip)
[CRW_1256.zip](https://github.com/lensfun/lensfun/files/3753402/CRW_1256.zip)

**Comment by tuxfanx** [comment]
the pictures are not suitable for calibration. Please [read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how they have to be taken
