### ISSUE TITLE
Warnings while compiling under MacOS with XCode

### ISSUE THREAD

**Issue by cgilles** [lensfun/lensfun#1025]
Compiling digiKam lensfun plugin under MacOS report these warnings below. Lensfun from git/master is used : 

In file included from /Users/gilles/dktemp/digikam-master/core/dplugins/editor/enhance/lensautofix/lensautofixtool.cpp:48:
In file included from /Users/gilles/dktemp/digikam-master/core/libs/dimg/filters/lens/lensfuniface.h:33:
/opt/digikam/include/lensfun/lensfun.h:1032:1: warning: 'lfLens' defined as a struct here but previously declared as a class [-Wmismatched-tags]
struct LF_EXPORT lfLens
^
/opt/digikam/include/lensfun/lensfun.h:953:12: note: did you mean struct here?
    friend class lfLens;
           ^~~~~
           struct
/opt/digikam/include/lensfun/lensfun.h:1716:1: warning: 'lfDatabase' defined as a struct here but previously declared as a class [-Wmismatched-tags]
struct LF_EXPORT lfDatabase
^
/opt/digikam/include/lensfun/lensfun.h:952:12: note: did you mean struct here?
    friend class lfDatabase;
           ^~~~~
           struct

**Comment by seebk** [comment]
Thanks, it should be fixed in master now. I do not have a Mac to verify, please reopen if the warnings still occur.
