### ISSUE TITLE
Generate release for v0.3.95?

### ISSUE THREAD

**Issue by oblute** [lensfun/lensfun#1029]
I can see on the homepage - http://lensfun.sourceforge.net/news/ - that there was an alpha release that can be downloaded as a tarball from sourceforge via that site. Is it possible to generate a release for the newest version on here, since the most recent one is from 2015 and this was done in 2018? I'm attempting to add this to the conda-forge and running into Windows issues (mainly regex.h, and more) that seem to be rectified in the newer version; I'd also like to add the newest possible version. Thanks!

**Comment by seebk** [comment]
Oh yes, the 0.3.95 tag somehow got lost in the transition from Sourceforge to GitHub. I have explicitly pushed the tag to GitHub again.  
https://github.com/lensfun/lensfun/releases/tag/v0.3.95

Thanks for letting us know!

**Comment by oblute** [comment]
@seebk thank you!
