### ISSUE TITLE
Calibration data for SIGMA 56mm F1.4 DC DN

### ISSUE THREAD

**Issue by catharanthus** [lensfun/lensfun#1035]
Lens: SIGMA 56mm F1.4 DC DN
Mount: Micro 4/3
Purpose: distortion calibration

Calibration data attached.

[lensfun.xml.gz](https://github.com/lensfun/lensfun/files/3854203/lensfun.xml.gz)

**Comment by catharanthus** [comment]
Raw source at #1036

**Comment by tuxfanx** [comment]
distortion data are included in db
