### ISSUE TITLE
translation → slr-ussr.xml

### ISSUE THREAD

**Issue by ghost** [lensfun/lensfun#1041]
I see that entries in slr-ussr.xml are only partially translated. So I translated the rest. File is in the attachment. It's not a big deal, just a bit annoying to see them split in two groups in programs which use lensfun (one Russian name and another in Latin).

Thank you very much for the great work you do!

[slr-ussr.zip](https://github.com/lensfun/lensfun/files/3885294/slr-ussr.zip)

**Comment by tuxfanx** [comment]
is included --> closed
