### ISSUE TITLE
Add Sony a6600 (ILCE-6600) camera entry

### ISSUE THREAD

**Issue by stettler** [lensfun/lensfun#1046]
Would it be possible to add the Sony a6600 (ILCE-6600) camera please? It should probably be very similar, if not the same as the Sony a6400. (The a6600 use the same technology as the a6400. Also both a6600 and a6400 have the same sensor as the a6100, a6300 and a6500)

**Comment by junkyardsparkle** [comment]
Added 6400 as well, thanks for the heads-up. :-)
