### ISSUE TITLE
LX100M2 unrecognized

### ISSUE THREAD

**Issue by paolobenve** [lensfun/lensfun#1048]
Lensfun knows the Panasonic LX100, but it doesn't know the LX100M2, which moreover shares the same lens.

Please add LX100m2 equal to LX100.

**Comment by junkyardsparkle** [comment]
It was added some months ago: https://github.com/lensfun/lensfun/commit/71ec282915468346a2abc1ff372e30b07b72d148

Maybe you need to update your database?

**Comment by paolobenve** [comment]
is it still missing in changelog file?

**Comment by junkyardsparkle** [comment]
The changelog file is only updated for new releases of the LensFun software itself. The database is being updated constantly, you can check current camera/lens support here: https://wilson.bronger.org/lensfun_coverage.html

**Comment by tuxfanx** [comment]
camera is included in db --> closed
