### ISSUE TITLE
Panasonic Lumix G Vario 14-140mm f/3.5-5.6 II unrecognized

### ISSUE THREAD

**Issue by catharanthus** [lensfun/lensfun#1051]
Panasonic released a new version of the 14-140mm f/3.5-5.6 lens. The lens name is reported as "LUMIX G VARIO 14-140mm F3.5-5.6 II". This lens has the same optics as the previous one (without "II") which already has a profile. Please make lensfun recognize this new name.

**Comment by junkyardsparkle** [comment]
Added, thanks.
