### ISSUE TITLE
LEICA DG SUMMILUX 25mm F1.4 II unrecognized

### ISSUE THREAD

**Issue by catharanthus** [lensfun/lensfun#1052]
A new version of the Panasonic Leica 25mm f/1.4. The name is reported as "LEICA DG SUMMILUX 25mm F1.4 II". The optics are the same as in the previous version, according to the manufacturer and confirmed by a quick test. The previous version already has a profile. Please make lensfun recognize this new name.

https://www.dpreview.com/news/1850697700/panasonic-leica-dg-summilux-25mm-f1-4-ii-asph-adds-weather-sealing-new-finish

**Comment by junkyardsparkle** [comment]
Added, thanks.
