### ISSUE TITLE
Lens Calibration Request Lumix DC Vario (Panasonic DC FZ80)

### ISSUE THREAD

**Issue by Gijssio** [lensfun/lensfun#1053]
I would like to request the following lens for calibration: 
Lumix DC Vario (fixed lens of Panasonic DC FZ80 https://www.panasonic.com/middleeast/en/consumer/cameras-camcorders/lumix-digital-cameras/dc-fz80.specs.html) 
This would help me a lot, thanks!

**Comment by tuxfanx** [comment]
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/
