### ISSUE TITLE
Calibration data for NIKKOR Z 14-30mm f/4 

### ISSUE THREAD

**Issue by Affreux666** [lensfun/lensfun#1054]
[Nikon 14-30 lensfun.tar.gz](https://github.com/lensfun/lensfun/files/3973680/Nikon.14-30.lensfun.tar.gz)

**Comment by trougnouf** [comment]
Can this be combined with #1404 ? (vignetting)

**Comment by trougnouf** [comment]
Could the distortion be off? It definitely helps in some cases, but makes the lines worse in images such as that attached (raw file [here](https://nc.trougnouf.com/index.php/s/zAHJiTwq7bazY9c)).
![scrn-2021-04-18-12-47-30](https://user-images.githubusercontent.com/6899116/115142890-6bb24e80-a044-11eb-9042-7a8bf624ff68.png)
![scrn-2021-04-18-12-46-51](https://user-images.githubusercontent.com/6899116/115142893-6f45d580-a044-11eb-8a73-78bde606b46e.png)

**Comment by gnl21** [comment]
This can definitely be combined with separate vignetting data like that in #1404, but how happy are we with the distortion correction here? I can merge the data into the database, but I don't have any way of testing the corrections.

**Comment by trougnouf** [comment]
I haven't done extensive testing with this lens yet but with the combined profile I end up leaving the distortion correction off more often than not :/

**Comment by Sturmflut** [comment]
I linked a pull request that combines the TCA corrections with the vignetting data from issue #1404. Is someone able to correct the distortion data or upload images?

**Comment by Sturmflut** [comment]
There are now three different issues with data for this lens: this, #1200 and #1404. Each has partial data. Is someone maybe able to find out which combination of distortion, tca and vignetting data from the three data sets is the best?

**Comment by Sturmflut** [comment]
...and there is also a fourth one, #1494.

**Comment by Sturmflut** [comment]
Merged in lensfun@c39ccac780ffec1a5d6e835f1b328ef44f77bdbe
