### ISSUE TITLE
Request for Tokina AT-X 24-70mm F2.8 PRO FX Profile

### ISSUE THREAD

**Issue by Allmedialab** [lensfun/lensfun#1058]
Hi,
The most common lens from Tokina is missing in the profiles:
Tokina AT-X 24-70mm F2.8 PRO FX for Canon and Nikon
Regards,
David

**Comment by tuxfanx** [comment]
data for distortion and tca are included in db. For vignetting data we need raw pictures. [Read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how they have to be taken.
