### ISSUE TITLE
Tamron SP 15-30mm F/2.8 Di VC USD G2

### ISSUE THREAD

**Issue by jcubic** [lensfun/lensfun#1066]
I'm not able to upload the files [the site](https://wilson.bronger.org/) keep showing error "ERR_ADDRESS_UNREACHABLE" how big file you can send?

I've uploaded the file to my shared hosting.

http://jcubic.pl/tamron-15-30-SP-G2.tar.gz

**Comment by tuxfanx** [comment]
calibration data completely included in DB

**Comment by jcubic** [comment]
@tuxfanx how to get a new DB? Do I need to install lensFun from the source or is there a way to grab just the database? Also, the lens is not listed on https://lensfun.github.io/lenslist/ is it included in a development version?

**Comment by sarunasb** [comment]
Database files are `data/db/*`. You can download all or some of them and then replace your existing ones.

On Linux you can run `lensfun-update-data`, which will do the same.
