### ISSUE TITLE
Poor performance on chromatic aberration correction

### ISSUE THREAD

**Issue by tim-hilt** [lensfun/lensfun#1087]
Hi there! I wanted to apply TCA- and distortion-correction to an image, but apparently it makes not so much of a difference when i include TCA (left is with TCA-correction (`ApplySubpixelGeometryDistortion`), right is without (`ApplyGeometryDistortion`)):

![Comparison_WO_TCA](https://user-images.githubusercontent.com/16037579/74081757-d0dadf00-4a52-11ea-83c1-d9091b02a622.png)

When i check image similarity with mean squared error it give a difference of 26, which is **very** low, considering it's a 5246x3932 image.

I used OpenCV to perform the corrections on. Here is the relevant code:

    mod->EnableTCACorrection(); // Is this line actually needed? ssim shows no difference
    mod->EnableDistortionCorrection();

    auto *pos = new float[width * 2 * 3];
    bool ok = true;

    cv::Mat B, G, R;
    cv::Mat channels[3];
    cv::split(Img, channels);
    B = channels[0];
    G = channels[1];
    R = channels[2];

    cv::Mat mapX_B(height, width, CV_32FC1);
    cv::Mat mapY_B(height, width, CV_32FC1);
    cv::Mat mapX_G(height, width, CV_32FC1);
    cv::Mat mapY_G(height, width, CV_32FC1);
    cv::Mat mapX_R(height, width, CV_32FC1);
    cv::Mat mapY_R(height, width, CV_32FC1);

    for (int i = 0; i < height; i++) {
        ok = mod->ApplySubpixelGeometryDistortion(0.0, (float)i, width, 1, pos);
        if (ok) {
            float *src = pos;
            for (int j = 0; j < width; j++) {
                mapX_B.at<float>(i, j) = src[0];
                mapY_B.at<float>(i, j) = src[1];
                mapX_G.at<float>(i, j) = src[2];
                mapY_G.at<float>(i, j) = src[3];
                mapX_R.at<float>(i, j) = src[4];
                mapY_R.at<float>(i, j) = src[5];
                src += 6;
            }
        }
    }

    delete [] pos;

    cv::Mat dest_B(height, width, CV_32FC1);
    cv::Mat dest_G(height, width, CV_32FC1);
    cv::Mat dest_R(height, width, CV_32FC1);
    cv::remap(B, dest_B, mapX_B, mapY_B, cv::INTER_LANCZOS4);
    cv::remap(G, dest_G, mapX_G, mapY_G, cv::INTER_LANCZOS4);
    cv::remap(R, dest_R, mapX_R, mapY_R, cv::INTER_LANCZOS4);
    cv::Mat dest;
    cv::Mat corrected[3] = { dest_B, dest_G, dest_R };
    cv::merge(corrected, 3, dest);
    cv::imwrite("Corrected.png", dest);

The camera i used is a Canon PowerShot SX70 HS, which uses the exact same lens as the PowerShot SX60 HS (according to customer service). [The PowerShot SX60 HS is available in the database](https://github.com/lensfun/lensfun/blob/master/data/db/compact-canon.xml#L3392).

What have i done wrong? Is it maybe because of the Interpolation method (`cv::INTER_LANCZOS4`)?

**Comment by uchrisu** [comment]
Hi @tim-hilt 
your image seems to be taken from at al close distance. Normally, TCA-profiles are taken near infinity. 
The problem is that TCA can vary much over distance.
See the discussion in #1640

**Comment by tuxfanx** [comment]
anwered --> closed
