### ISSUE TITLE
Calibration data for Canon EF 24-105mm f/3.5-5.6 IS STM and Canon EF 15mm f/2.8 Fisheye

### ISSUE THREAD

**Issue by salsergey** [lensfun/lensfun#1088]
Please add the attached lens data to the lensfun data base.

The images were taken with Canon EOS 6D Mark II. I tried to follow the instructions as much as I could. I have shot several panoramas with the fisheye lens in order to measure vignetting parameters.

If you need additional information (images, pdfs, etc.) I can provide them too.

[lensfun.zip](https://github.com/lensfun/lensfun/files/4174189/lensfun.zip)

**Comment by junkyardsparkle** [comment]
Added, thanks!
