### ISSUE TITLE
Add Panasonic DMC-TZ96 camera entry

### ISSUE THREAD

**Issue by andijoos** [lensfun/lensfun#1094]
Would it be possible to add the Panasonic TZ96 camera to compact-panasonic.xml please? It should probably be very similar, if not the same as the Panasonic TZ90.
For me it works, when I add the following:
`<camera>`
        `<maker>Panasonic</maker>`
        `<model>DMC-TZ96</model>`
        `<mount>panasonicTZ70</mount>`
        `<cropfactor>5.58</cropfactor>`
  `</camera>`

**Comment by junkyardsparkle** [comment]
Done, thanks!
