### ISSUE TITLE
Sigma SIGMA 30mm f/1.4 DC DN not recognized

### ISSUE THREAD

**Issue by ttonino** [lensfun/lensfun#1095]
I noticed the Sigma 30mm f/1.4 DC DN not being recognized because of a difference in name.

I copied the profile and changed the model to:<model>SIGMA 30mm f/1.4 DC DN | Contemporary 016</model>

(The original model tag contains just the letter C whereas my lens seems to have Contemporary)

**Comment by cjelgin** [comment]
I'm having the same issue when using the lensfun database with darktable. It appears that this fix was never permanently implemented.

**Comment by tuxfanx** [comment]
was changed --> closed
