### ISSUE TITLE
Add Panasonic Lumix S1R (DC-S1R) camera entry

### ISSUE THREAD

**Issue by NFecDe** [lensfun/lensfun#1099]
Hi, can you please add the Panasonic DC-S1R (Lumix S1R)to the camera database?
The S1R is the high-resolution model (47MP) of the new Full Frame line up from Panasonic and uses as mount the L-Mount (Leica L Mount).
I had a look into the mil-panasonic.xml and also the mil-leica.xml to find out which name is used for the mount.
Here are the tags which shall fit to be added to the mil-panasonic.xml:

    <camera>
        <maker>Panasonic</maker>
        <model>DC-S1R</model>
        <mount>Leica L</mount>
        <cropfactor>1</cropfactor>
    </camera>

In case you want to add the "lower resolution" model (24MP), the DC-S1 as well this shall fit:

    <camera>
        <maker>Panasonic</maker>
        <model>DC-S1</model>
        <mount>Leica L</mount>
        <cropfactor>1</cropfactor>
    </camera>

Thanks a lot!!

**Comment by junkyardsparkle** [comment]
Added, thanks!
