### ISSUE TITLE
TAMRON 17-28 f/2.8 DI RxD for SONY eMount lensfun data missing in db

### ISSUE THREAD

**Issue by peter-hb-1955** [lensfun/lensfun#1102]
Hello,
I missed my TAMRON 17-28 f/2.8 DI RxD for SONY eMount in the lensfun database and therefore generated it by myself. Please find my data attached. I tested it with darktable and I think it is Ok to distribute for all.
All the best
Peter Seifert
[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/4262834/lensfun_calibration.zip)

**Comment by somniumAeternam** [comment]
Maybe you can send this calibration to https://wilson.bronger.org/calibration or contact Torsten Bronger directly, so he can add this calibration file to the database. You should also send him the raws on which your calibration is based. I'm looking forward to have this lense in the database.

**Comment by tuxfanx** [comment]
Only f/2.8 vignetting data included what is not usable. Please [read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how the data have to be.
distortion data are already included in db. tca data are usable.
