### ISSUE TITLE
TAMRON 28-75 f/2.8 Di III RxD for SONY eMount is not in lensfun db

### ISSUE THREAD

**Issue by peter-hb-1955** [lensfun/lensfun#1103]
Hello,
I missed my TAMRON 28-75 f/2.8 DI RxD for SONY eMount in the lensfun database and therefore generated it by myself. Please find my data attached. I tested it with darktable and I think it is Ok to distribute for all.
All the best
[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/4262862/lensfun_calibration.zip)

Peter Seifert

**Comment by StefanDieke** [comment]
Thanks a lot Peter, for making your calibration data for the Tamron DI RxD lenses for Sony eMount available! This is exactly what I was looking for! I hope they will be integrated into lensfun quickly!
How do I integrate them locally (I'm running on linux)?

**Comment by peter-hb-1955** [comment]
Hello Stefan,
you have to edit the lensfun file "mil-tamron.xml" and to add there the new <lens> data block before the file end </lensdatabase>. In manjaro KDE I have the kate editor. In other Linux versions there are different editors. The file has to be edited / saved in admin mode. For Manjaro KDE YOu can edit it in the terminal with this command "kate /usr/share/lensfun/version_2/mil-tamron.xml". May be in other linux the lensfun directory is different.
In my case I also had to add my camera in the file "mil-sony.xml". The ALPHA 7 RM3 data can be duplicated simply from the R2 data block and then changing the camera name.  Darktable is recognizing the lens only if also the camera is available in lensfun database.
Have fun!
Peter Seifert

**Comment by StefanDieke** [comment]
Perfect! Thanks a lot again, Peter! After finding the right files (which for Antergos are in ~/.local/share/lensfun/updates/version2) it works like a charm!
Anyway, I think this data should be included in the official lensfun database for a wider usage!

**Comment by vladakoz** [comment]
Hello, I am very new to this but I was not successfull following your process. I have Sony A 7 III body and Tamron 28-75mm f/2.8 Di III RXD lens. I am running Darktable on Linux Leap 15.1.
After implementing your procedure Darktable is not able to find the lens. In fact if I attempt to find the lens manually a do not have the Tamron available in the lens pull down menu. The camera is reported as Sony, Alpha 7 III and the lens as E 28-75mm F2.8-2.8. Any suggestions where I went wrong ?
Vlada.

**Comment by uchrisu** [comment]
A much easier way of including the lens profile to the lensfun database without touching the original files is to copy the lensfun.xml from the appendix above in the directory ~/.local/share/lensfun/
with an arbitrary name, e.g., ~/.local/share/lensfun/Tamron_28_75_28.xml

Lensfun will search through every xml file for local lenses in this directory.


As I have the lens too, I will test your suggested profile and add it to the master branch if it works fine. Probably I will need some time.

**Comment by vladakoz** [comment]
Great that worked uchrisu. Thank you very much. Vlada.

**Comment by peter-hb-1955** [comment]
Hi,
great really!
I searched for such easy solution but without success.
Is it already documented in the darktable page ? If not would be very 
fine (Github is a not a common page for foto enthusiasts to look for 
such things).
Have a fine day and stay healthy
Peter Seifert

Am 31.03.20 um 20:05 schrieb uchrisu:

**Comment by uchrisu** [comment]
I had a look on in and tested the profile on my own pictures. It works great! I have merged it to master. Thank you!
