### ISSUE TITLE
Tamron 20mm F2.8 Di III OSD M1:2, Distortion

### ISSUE THREAD

**Issue by santagraus** [lensfun/lensfun#1105]
This lens is available since Januar 2020. I did my best to create proper distortion correction values.
Tested with Darktable, it looks usable.
Note:
The test data was generated using a Sony A7III. The lens is recognized by the camera as 
E 20mm F2.8 F050

[tamron_20mm_f2-8_DiIII_OSD.txt](https://github.com/lensfun/lensfun/files/5393533/tamron_20mm_f2-8_DiIII_OSD.txt)

**Comment by uchrisu** [comment]
@santagraus  The important part (Calibration data) is empty!?

**Comment by santagraus** [comment]
@uchrisu Thanks. Somehow I got the wrong version file. I fixed it

**Comment by uchrisu** [comment]
Thanks, I've verified the profile and will put it into our database. 
Thanks for providing the profile!

**Comment by uchrisu** [comment]
It it in the master brach now. I will close this issue.
