### ISSUE TITLE
Add Olympus OM-D E-M5 Mark III

### ISSUE THREAD

**Issue by olupton** [lensfun/lensfun#1126]
The Olympus OM-D E-M5 Mark III does not seem to be recognised by lensfun. Looking at an example raw file shows:
```
$ exiv2 -pt P3150621.ORF
...
Exif.Image.Make                              Ascii      24  OLYMPUS CORPORATION
Exif.Image.Model                             Ascii      17  E-M5MarkIII
...
```
Can this please be added to the database? Thanks!

**Comment by sarunasb** [comment]
Olympus OM-D E-M5 Mark III camera added to data/db/mil-olympus.xml.
