### ISSUE TITLE
How to add support for a missing lens

### ISSUE THREAD

**Issue by paolostivanin** [lensfun/lensfun#1131]
Hello,
I'd like to add support for the following lens, because it seems that only the older version is supporteD:
```
Lens ID                         : Tamron SP 90mm f/2.8 Di VC USD Macro 1:1 (F017)
```
How can I do that?
Thanks

**Comment by paolostivanin** [comment]
nv, I just found out :)

**Comment by tradespite** [comment]
@paolostivanin I'm also looking for a suitable profile for the lens `Tamron SP 90mm f/2.8 Di VC USD Macro 1:1 (F017)`.
Can you share your settings for this lens?

**Comment by paolostivanin** [comment]
Sorry, I sold the lens a long time ago :)
I ended up using the adobe lcp profile though. There's a guide on RawTherapee's rawpedia on how to extract it

**Comment by tradespite** [comment]
@paolostivanin thank you, that way seems to work.

These links were helpful for me:
- https://lensfun.github.io/manual/latest/lensfun-convert-lcp.html
- https://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles

**Comment by Sturmflut** [comment]
Calibrator info: There are two calibration uploads for lenses with this name, #993 (on a Canon EOS 5D Mark IV) and #1083 (on a Nikon D750).

**Comment by Sturmflut** [comment]
Distortion and TCA for this lens on Nikon F AF and Canon EF mounts (crop factor 1.0) were committed in lensfun/lensfun@d83d1b7c9ba0c80b74cc61aaeea9baa63507b79f . 

Crop factor 1.613 was already in the database for Nikon F AF/Canon EF/Sony Alpha mounts, but I suspect the current model name (`Tamron SP 90mm f/2.8 Di VC USD Macro 1:1 F004`) won't be detected on anything else than Canon.

Could you please update your local database and check it?
