### ISSUE TITLE
Calibration for OLYMPUS M.14-42mm F3.5-5.6 II R seems to be wrong

### ISSUE THREAD

**Issue by krauthaufen** [lensfun/lensfun#1167]
Hey all, I'm really happy using LensFun in my project, but the calibration for my Lens seems to be wrong.

| EXIF | Value |
|:-- |:-- |
| Camera | [`Olympus OM-D E-M10`](https://www.digicamdb.com/specs/olympus_om-d-e-m10/) |
| Lens |  `OLYMPUS M.14-42mm F3.5-5.6 II R`  |
| FocalLength | `14.0mm` |
| CropFactor | `2.0` |

LensFun (correctly) detects the lens to be
`Olympus M.Zuiko Digital ED 14-42mm f/3.5-5.6 II R`

but the undistortion yields the following image (with non-straight lines)

[![IncorrectUndistortion](https://aardvarkians.com/demo/bug2.jpg)](https://aardvarkians.com/demo/olympus_bug.jpg)

Since I'm using LensFun in my own project I also cross-checked with AffinityPhoto which yields the identical result.

I'd be totally okay with calibrating the camera myself if someone could let me know how to do that!

Additional Info for the resolved camera, lens and distortion:
```
Olympus Imaging Corp. E-M10
  crop:   2
  score:  200
  mount:  Micro 4/3 System { DKL; Generic; M42; T2 }
  sensor: 17.3mm x 13mm
  lenses
    Olympus Olympus M.Zuiko Digital ED 14-42mm f/3.5-5.6 II R
      type:      Rectilinear
      focal:     14-42mm
      aperture:  3.5
      center:    0 0
      distortion
        info:      PtLens (0.01377000008,-0.06575000286,0.009519999847)
        focal:     14.5944mm
```

[Original Image](https://aardvarkians.com/demo/P1010349.JPG)

Cheers

**Comment by junkyardsparkle** [comment]
That looks like the correction is being applied twice... were you applying it to an out-of-camera JPEG by any chance? Those should already be corrected; the data in LensFun is for uncorrected RAW files.

**Comment by krauthaufen** [comment]
Hey, i figured that it's actually not the correct lens since the `ED` models are different from the ones without `ED` in the name and yes I used a jpeg, but the input file seems to be distorted quite heavily...

Tomorrow I'll continue to investigate the issue and calibrate the camera manually using OpenCV. Afaik OpenCV uses a different distortion model with two tangential terms. Any experience with converting these values for LensFun?

Btw just a quick question: since most of our users don't have RAW files, is there any known way to get the firmware-applied distortion for a camera? Or would it be possible to add measured distortions for jpegs with a common suffix (mylens-jpeg) or something similar?
Cheers

**Comment by junkyardsparkle** [comment]
> yes I used a jpeg, but the input file seems to be distorted quite heavily...

I applied the profile in "distort" mode to your image, and the result does show some residual barrel distortion (I wouldn't call it "heavy", though). It's possible the in-camera correction at the wide end for that lens is less than absolute; I have a copy somewhere I've never really used, if I get a chance I'll take a look at that. You would need to create a new profile from camera-corrected JPEG output if that's what you need, in general that's out of scope for the official LensFun database.

**Comment by krauthaufen** [comment]
Hey, thanks for the clarification, I'm planning to calibrate the lens with RAW and jpeg and submit a PR with the RAW parameters when I have the time.
