### ISSUE TITLE
Vignetting data for smc Pentax-DA L 18-50mm f/4-5.6 DC WR RE

### ISSUE THREAD

**Issue by falket** [lensfun/lensfun#118]
Vignetting data for smc Pentax-DA L 18-50mm f/4-5.6 DC WR RE follows.

p.s according to pentaxforums ( http://www.pentaxforums.com/lensreviews/hd-pentax-da-18-50mm-f4-56-dc-wr-re.html even if it's the hd version and not the smc one) it's a kaf3 and not kaf2.

Thank you.

            <vignetting model="pa" focal="18" aperture="4" distance="10" k1="-0.1711" k2="-0.9527" k3="0.5945" />
            <vignetting model="pa" focal="18" aperture="4" distance="1000" k1="-0.1711" k2="-0.9527" k3="0.5945" />
            <vignetting model="pa" focal="18" aperture="5.6" distance="10" k1="-0.0563" k2="-0.5835" k3="0.1701" />
            <vignetting model="pa" focal="18" aperture="5.6" distance="1000" k1="-0.0563" k2="-0.5835" k3="0.1701" />
            <vignetting model="pa" focal="18" aperture="8" distance="10" k1="-0.2812" k2="0.2809" k3="-0.3809" />
            <vignetting model="pa" focal="18" aperture="8" distance="1000" k1="-0.2812" k2="0.2809" k3="-0.3809" />
            <vignetting model="pa" focal="18" aperture="11" distance="10" k1="-0.3233" k2="0.3157" k3="-0.2672" />
            <vignetting model="pa" focal="18" aperture="11" distance="1000" k1="-0.3233" k2="0.3157" k3="-0.2672" />
            <vignetting model="pa" focal="18" aperture="22" distance="10" k1="-0.2513" k2="-0.0017" k3="0.0500" />
            <vignetting model="pa" focal="18" aperture="22" distance="1000" k1="-0.2513" k2="-0.0017" k3="0.0500" />
            <vignetting model="pa" focal="24" aperture="4.5" distance="10" k1="-0.0623" k2="-0.9608" k3="0.5561" />
            <vignetting model="pa" focal="24" aperture="4.5" distance="1000" k1="-0.0623" k2="-0.9608" k3="0.5561" />
            <vignetting model="pa" focal="24" aperture="5.6" distance="10" k1="-0.1184" k2="-0.1416" k3="-0.0579" />
            <vignetting model="pa" focal="24" aperture="5.6" distance="1000" k1="-0.1184" k2="-0.1416" k3="-0.0579" />
            <vignetting model="pa" focal="24" aperture="8" distance="10" k1="-0.2333" k2="0.1738" k3="-0.1239" />
            <vignetting model="pa" focal="24" aperture="8" distance="1000" k1="-0.2333" k2="0.1738" k3="-0.1239" />
            <vignetting model="pa" focal="24" aperture="11" distance="10" k1="-0.2046" k2="0.0233" k3="0.0363" />
            <vignetting model="pa" focal="24" aperture="11" distance="1000" k1="-0.2046" k2="0.0233" k3="0.0363" />
            <vignetting model="pa" focal="24" aperture="22" distance="10" k1="-0.2095" k2="0.0317" k3="0.0322" />
            <vignetting model="pa" focal="24" aperture="22" distance="1000" k1="-0.2095" k2="0.0317" k3="0.0322" />
            <vignetting model="pa" focal="34" aperture="4.5" distance="10" k1="-0.6655" k2="0.4679" k3="-0.1657" />
            <vignetting model="pa" focal="34" aperture="4.5" distance="1000" k1="-0.6655" k2="0.4679" k3="-0.1657" />
            <vignetting model="pa" focal="34" aperture="5.6" distance="10" k1="-0.1549" k2="-0.3719" k3="0.2863" />
            <vignetting model="pa" focal="34" aperture="5.6" distance="1000" k1="-0.1549" k2="-0.3719" k3="0.2863" />
            <vignetting model="pa" focal="34" aperture="8" distance="10" k1="-0.1223" k2="-0.0198" k3="0.0589" />
            <vignetting model="pa" focal="34" aperture="8" distance="1000" k1="-0.1223" k2="-0.0198" k3="0.0589" />
            <vignetting model="pa" focal="34" aperture="11" distance="10" k1="-0.1237" k2="-0.0396" k3="0.0843" />
            <vignetting model="pa" focal="34" aperture="11" distance="1000" k1="-0.1237" k2="-0.0396" k3="0.0843" />
            <vignetting model="pa" focal="34" aperture="22" distance="10" k1="-0.1258" k2="-0.0556" k3="0.1032" />
            <vignetting model="pa" focal="34" aperture="22" distance="1000" k1="-0.1258" k2="-0.0556" k3="0.1032" />
            <vignetting model="pa" focal="43" aperture="5.6" distance="10" k1="-0.7965" k2="0.7042" k3="-0.2677" />
            <vignetting model="pa" focal="43" aperture="5.6" distance="1000" k1="-0.7965" k2="0.7042" k3="-0.2677" />
            <vignetting model="pa" focal="43" aperture="8" distance="10" k1="-0.0475" k2="-0.2120" k3="0.0921" />
            <vignetting model="pa" focal="43" aperture="8" distance="1000" k1="-0.0475" k2="-0.2120" k3="0.0921" />
            <vignetting model="pa" focal="43" aperture="11" distance="10" k1="-0.1185" k2="0.0018" k3="0.0462" />
            <vignetting model="pa" focal="43" aperture="11" distance="1000" k1="-0.1185" k2="0.0018" k3="0.0462" />
            <vignetting model="pa" focal="43" aperture="22" distance="10" k1="-0.1113" k2="-0.0213" k3="0.0536" />
            <vignetting model="pa" focal="43" aperture="22" distance="1000" k1="-0.1113" k2="-0.0213" k3="0.0536" />
            <vignetting model="pa" focal="50" aperture="5.6" distance="10" k1="-0.8485" k2="0.8254" k3="-0.3390" />
            <vignetting model="pa" focal="50" aperture="5.6" distance="1000" k1="-0.8485" k2="0.8254" k3="-0.3390" />
            <vignetting model="pa" focal="50" aperture="8" distance="10" k1="-0.0474" k2="-0.5397" k3="0.3555" />
            <vignetting model="pa" focal="50" aperture="8" distance="1000" k1="-0.0474" k2="-0.5397" k3="0.3555" />
            <vignetting model="pa" focal="50" aperture="11" distance="10" k1="-0.1252" k2="0.0568" k3="-0.0007" />
            <vignetting model="pa" focal="50" aperture="11" distance="1000" k1="-0.1252" k2="0.0568" k3="-0.0007" />
            <vignetting model="pa" focal="50" aperture="22" distance="10" k1="-0.1280" k2="0.0673" k3="-0.0116" />
            <vignetting model="pa" focal="50" aperture="22" distance="1000" k1="-0.1280" k2="0.0673" k3="-0.0116" />

**Comment by bronger** [comment]
Thank you very much for the data!  With which camera were the test images made?

Please report bugs, feature wishes, or calibration data at <https://sourceforge.net/projects/lensfun/>.  The GitHub repo is only for coordinating the work of the calibration team.

**Comment by falket** [comment]
Pentax K20. Thank you!

Next time i'll use sourceforge tickets.

**Comment by bronger** [comment]
Okay, it is included!  Thanks again!
