### ISSUE TITLE
How can I create a new lens profile from an existing profile to access it from Darktable?

### ISSUE THREAD

**Issue by MRedbook** [lensfun/lensfun#1180]
I have no knowledge how to create a new lens profile for lensfun that can be accessed from Darktable under Windows. I searched in Internet several sites, but this subject seems to be complicated. I could not find any straightforward guide explaining the procedure step by step.

What I need is the following:
I own a newer Fujifilm lens XC 35 mm f/2.0 for that there exists no entry in Darktable for lens correction. I noticed there is another Fujifilm lens XF 35 mm f/2.0 that I can select manually and the result of correction is reasonable. Both lenses may have a very similar construction.

I would like to create a lens profile (I assume it is a XML text file) for XC 35 mm f/2.0 just by importing the existing data of the lens XF 35 mm f/2.0.  

My first question is in which folder Lensfun database under Windows 8.1 is stored, when I install Darktable. How are the lens profiles named and how I can create a new one so that it can be automatically recognized by Darktable.

Thank you for your help in advance.
Regards,
Mustafa K.

**Comment by jcubic** [comment]
You can check the code it have data/db with lot of xml files, just search the disk on your Windows 8.1 machine (best is to use Cygwin or Git Bash that give you real linux env but you can use use standard search feature build into windows) for xml file that hold your lens. By searching for XC 35 on GitHub you will see this file:

https://github.com/lensfun/lensfun/blob/800750b71d344b3cbe02434cd33f33795097a423/data/db/mil-fujifilm.xml

You need to find that file on your system and add another entry for your lens using copy paste. But I'm not an expert so I have no idea if it will work or you will find that file on your disk.
