### ISSUE TITLE
Please add "Nikon NIKKOR Z DX 50-250mm f/4.5-6.3 VR" to lensfun database

### ISSUE THREAD

**Issue by enricokratter** [lensfun/lensfun#1191]
Please add "Nikon NIKKOR Z DX 50-250mm f/4.5-6.3 VR" to lensfun database

**Comment by apostel338** [comment]
I made my own distortion-correction for this lens. If the devs like to, they can use it. 

###             <distortion model="ptlens" focal="50" a="0.00037" b="-0.00973" c="0.00219"/>
            <distortion model="ptlens" focal="60" a="0.00051" b="-0.00831" c="0.00928"/>
            <distortion model="ptlens" focal="68" a="-0.00493" b="0.01702" c="-0.02137"/>
            <distortion model="ptlens" focal="81" a="0.00271" b="-0.00362" c="0.00076"/>
            <distortion model="ptlens" focal="98" a="0.00638" b="-0.01557" c="0.01839"/>
            <distortion model="ptlens" focal="125" a="-0.00372" b="0.01594" c="-0.00515"/>
            <distortion model="ptlens" focal="195" a="-0.00262" b="0.01301" c="-0.00402"/>
            <distortion model="ptlens" focal="250" a="-0.01474" b="0.05824" c="-0.05597"/>

**Comment by tuxfanx** [comment]
[no test pictures available](https://wilson.bronger.org/calibration) --> closed
