### ISSUE TITLE
Distortion anf Vignetting for NIKKOR Z 14-30mm f/4 S

### ISSUE THREAD

**Issue by wgoetz** [lensfun/lensfun#1200]
<lensdatabase>

    <lens>
        <maker>Nikon Corporation</maker>
        <model>NIKKOR Z 14-30mm f/4 S</model>
        <mount>Nikon Z</mount>
        <cropfactor>1</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="14" a="0.01" b="-0.046" c="-0.017"/>
            <distortion model="ptlens" focal="16" a="-0.005" b="0.023" c="-0.083"/>
            <distortion model="ptlens" focal="20" a="-0.045" b="0.166" c="-0.185"/>
            <distortion model="ptlens" focal="24" a="-0.031" b="0.122" c="-0.119"/>
            <distortion model="ptlens" focal="30" a="-0.013" b="0.07" c="-0.066"/>
            <vignetting model="pa" focal="14" aperture="4" distance="10" k1="-1.5065" k2="0.8760" k3="-0.2721"/>
            <vignetting model="pa" focal="14" aperture="4" distance="1000" k1="-1.5065" k2="0.8760" k3="-0.2721"/>
            <vignetting model="pa" focal="14" aperture="5.6" distance="10" k1="-1.8184" k2="1.8712" k3="-0.9160"/>
            <vignetting model="pa" focal="14" aperture="5.6" distance="1000" k1="-1.8184" k2="1.8712" k3="-0.9160"/>
            <vignetting model="pa" focal="14" aperture="8" distance="10" k1="-1.9712" k2="2.1906" k3="-1.0463"/>
            <vignetting model="pa" focal="14" aperture="8" distance="1000" k1="-1.9712" k2="2.1906" k3="-1.0463"/>
            <vignetting model="pa" focal="14" aperture="11" distance="10" k1="-1.9274" k2="2.0508" k3="-0.9254"/>
            <vignetting model="pa" focal="14" aperture="11" distance="1000" k1="-1.9274" k2="2.0508" k3="-0.9254"/>
            <vignetting model="pa" focal="14" aperture="16" distance="10" k1="-1.8106" k2="1.8460" k3="-0.8200"/>
            <vignetting model="pa" focal="14" aperture="16" distance="1000" k1="-1.8106" k2="1.8460" k3="-0.8200"/>
            <vignetting model="pa" focal="14" aperture="22" distance="10" k1="-2.0501" k2="2.2478" k3="-0.9696"/>
            <vignetting model="pa" focal="14" aperture="22" distance="1000" k1="-2.0501" k2="2.2478" k3="-0.9696"/>
            <vignetting model="pa" focal="16" aperture="4" distance="10" k1="-1.4664" k2="0.9939" k3="-0.3008"/>
            <vignetting model="pa" focal="16" aperture="4" distance="1000" k1="-1.4664" k2="0.9939" k3="-0.3008"/>
            <vignetting model="pa" focal="16" aperture="5.6" distance="10" k1="-1.7495" k2="1.6376" k3="-0.6284"/>
            <vignetting model="pa" focal="16" aperture="5.6" distance="1000" k1="-1.7495" k2="1.6376" k3="-0.6284"/>
            <vignetting model="pa" focal="16" aperture="8" distance="10" k1="-1.7674" k2="1.6375" k3="-0.6013"/>
            <vignetting model="pa" focal="16" aperture="8" distance="1000" k1="-1.7674" k2="1.6375" k3="-0.6013"/>
            <vignetting model="pa" focal="16" aperture="11" distance="10" k1="-1.7464" k2="1.6251" k3="-0.6125"/>
            <vignetting model="pa" focal="16" aperture="11" distance="1000" k1="-1.7464" k2="1.6251" k3="-0.6125"/>
            <vignetting model="pa" focal="16" aperture="16" distance="10" k1="-1.6494" k2="1.5251" k3="-0.5921"/>
            <vignetting model="pa" focal="16" aperture="16" distance="1000" k1="-1.6494" k2="1.5251" k3="-0.5921"/>
            <vignetting model="pa" focal="16" aperture="22" distance="10" k1="-1.6769" k2="1.4434" k3="-0.4887"/>
            <vignetting model="pa" focal="16" aperture="22" distance="1000" k1="-1.6769" k2="1.4434" k3="-0.4887"/>
            <vignetting model="pa" focal="20" aperture="4" distance="10" k1="-1.2383" k2="0.6393" k3="-0.1022"/>
            <vignetting model="pa" focal="20" aperture="4" distance="1000" k1="-1.2383" k2="0.6393" k3="-0.1022"/>
            <vignetting model="pa" focal="20" aperture="5.6" distance="10" k1="-1.3358" k2="0.9354" k3="-0.2735"/>
            <vignetting model="pa" focal="20" aperture="5.6" distance="1000" k1="-1.3358" k2="0.9354" k3="-0.2735"/>
            <vignetting model="pa" focal="20" aperture="8" distance="10" k1="-1.4609" k2="1.1199" k3="-0.3378"/>
            <vignetting model="pa" focal="20" aperture="8" distance="1000" k1="-1.4609" k2="1.1199" k3="-0.3378"/>
            <vignetting model="pa" focal="20" aperture="11" distance="10" k1="-1.2161" k2="0.7226" k3="-0.1688"/>
            <vignetting model="pa" focal="20" aperture="11" distance="1000" k1="-1.2161" k2="0.7226" k3="-0.1688"/>
            <vignetting model="pa" focal="20" aperture="16" distance="10" k1="-1.2321" k2="0.8121" k3="-0.2178"/>
            <vignetting model="pa" focal="20" aperture="16" distance="1000" k1="-1.2321" k2="0.8121" k3="-0.2178"/>
            <vignetting model="pa" focal="20.5" aperture="22" distance="10" k1="-1.4632" k2="1.0370" k3="-0.2480"/>
            <vignetting model="pa" focal="20.5" aperture="22" distance="1000" k1="-1.4632" k2="1.0370" k3="-0.2480"/>
            <vignetting model="pa" focal="23.5" aperture="22" distance="10" k1="-1.1382" k2="0.6356" k3="-0.1247"/>
            <vignetting model="pa" focal="23.5" aperture="22" distance="1000" k1="-1.1382" k2="0.6356" k3="-0.1247"/>
            <vignetting model="pa" focal="24" aperture="4" distance="10" k1="-1.1123" k2="0.3661" k3="0.0699"/>
            <vignetting model="pa" focal="24" aperture="4" distance="1000" k1="-1.1123" k2="0.3661" k3="0.0699"/>
            <vignetting model="pa" focal="24" aperture="8" distance="10" k1="-1.1836" k2="0.7952" k3="-0.2189"/>
            <vignetting model="pa" focal="24" aperture="8" distance="1000" k1="-1.1836" k2="0.7952" k3="-0.2189"/>
            <vignetting model="pa" focal="24" aperture="11" distance="10" k1="-1.0086" k2="0.4446" k3="-0.0425"/>
            <vignetting model="pa" focal="24" aperture="11" distance="1000" k1="-1.0086" k2="0.4446" k3="-0.0425"/>
            <vignetting model="pa" focal="24" aperture="16" distance="10" k1="-1.1382" k2="0.8435" k3="-0.2905"/>
            <vignetting model="pa" focal="24" aperture="16" distance="1000" k1="-1.1382" k2="0.8435" k3="-0.2905"/>
            <vignetting model="pa" focal="24.5" aperture="5.6" distance="10" k1="-1.1451" k2="0.7648" k3="-0.2234"/>
            <vignetting model="pa" focal="24.5" aperture="5.6" distance="1000" k1="-1.1451" k2="0.7648" k3="-0.2234"/>
            <vignetting model="pa" focal="29.5" aperture="16" distance="10" k1="-0.8785" k2="0.3811" k3="-0.0348"/>
            <vignetting model="pa" focal="29.5" aperture="16" distance="1000" k1="-0.8785" k2="0.3811" k3="-0.0348"/>
            <vignetting model="pa" focal="30" aperture="4" distance="10" k1="-1.3060" k2="0.9330" k3="-0.2751"/>
            <vignetting model="pa" focal="30" aperture="4" distance="1000" k1="-1.3060" k2="0.9330" k3="-0.2751"/>
            <vignetting model="pa" focal="30" aperture="5.6" distance="10" k1="-0.9521" k2="0.5836" k3="-0.1650"/>
            <vignetting model="pa" focal="30" aperture="5.6" distance="1000" k1="-0.9521" k2="0.5836" k3="-0.1650"/>
            <vignetting model="pa" focal="30" aperture="8" distance="10" k1="-0.9405" k2="0.5192" k3="-0.1091"/>
            <vignetting model="pa" focal="30" aperture="8" distance="1000" k1="-0.9405" k2="0.5192" k3="-0.1091"/>
            <vignetting model="pa" focal="30" aperture="11" distance="10" k1="-0.7921" k2="0.3577" k3="-0.0947"/>
            <vignetting model="pa" focal="30" aperture="11" distance="1000" k1="-0.7921" k2="0.3577" k3="-0.0947"/>
            <vignetting model="pa" focal="30" aperture="22" distance="10" k1="-0.9388" k2="0.4949" k3="-0.0950"/>
            <vignetting model="pa" focal="30" aperture="22" distance="1000" k1="-0.9388" k2="0.4949" k3="-0.0950"/>
        </calibration>
    </lens>

</lensdatabase>

**Comment by wgoetz** [comment]
added vignetting

**Comment by Sturmflut** [comment]
There are now three different issues with data for this lens: this, #1054 and #1404. Each has partial data. Is someone maybe able to find out which combination of distortion, tca and vignetting data from the three data sets is the best?

**Comment by Sturmflut** [comment]
...and there is also a fourth one, #1494.

**Comment by Sturmflut** [comment]
Merged in lensfun@c39ccac780ffec1a5d6e835f1b328ef44f77bdbe
