### ISSUE TITLE
Calibration data for Tamron 18-400mm f/3.5-6.3 Di II VC HLD (B028) lens.

### ISSUE THREAD

**Issue by markus-gaipl** [lensfun/lensfun#1228]
Please add the supplied calibration data for the lens mentioned above.
[lensfun_calibration_tamron_18-400mm_(B028).zip](https://github.com/lensfun/lensfun/files/5047569/lensfun_calibration_tamron_18-400mm_.B028.zip)

**Comment by tuxfanx** [comment]
see PR #1684
