### ISSUE TITLE
Calibration data for Sigma 60-600mm F4.5-6.3 DG OS HSM | S on Canon EF-S mount

### ISSUE THREAD

**Issue by tomato42** [lensfun/lensfun#1238]
Full set of calibration data for the new "Bigma", shot on Canon 7D Mark II.

[Sigma60-600.zip](https://github.com/lensfun/lensfun/files/5133036/Sigma60-600.zip)

**Comment by tuxfanx** [comment]
Unfortunately I could not find any raw pictures for a test of your data. An upload would be possible [here](https://wilson.bronger.org/calibration).

**Comment by tomato42** [comment]
what kind of raw files you want? some generic pictures or the pictures I used for calibration? (not sure if I kept them, will need to look for them)

also you want just few to verify or all of them?

**Comment by tomato42** [comment]
@tuxfanx ok, uploaded few of the pictures I used for calibration, see https://github.com/lensfun/lensfun/issues/1894

**Comment by tuxfanx** [comment]
Thanks, looks good!
