### ISSUE TITLE
Calibration data for Canon EF 75-300mm f/4-5.6 III

### ISSUE THREAD

**Issue by jose-lens** [lensfun/lensfun#1247]
Please add the attached lens data to the lensfun data base.
Note: I couldn't use the newer lens_calibrate.py because the raw files didn't have the Exif.Photo.FocalLength, and I couldn't add it, maybe because it's an old camera (Canon EOS D60), because with a newer Canon raw file downloaded from internet that Exif parameter appeared and I could add/delete it. I used Torsten Bronger's calibrate.py script.

[lensfun.zip](https://github.com/lensfun/lensfun/files/5168121/lensfun.zip)

**Comment by tuxfanx** [comment]
added
