### ISSUE TITLE
database invalid, mil-sigma.xml: ERROR: Double primary key for lens!  ('sigma', 'sigma 19mm f/2.8 ex dn', 1.534)

### ISSUE THREAD

**Issue by mandree** [lensfun/lensfun#125]
$ grep -nri "sigma 19mm f/2.8 ex dn"  $SOMEDIR/lensfun-code.git/data/db
$SOMEDIR/lensfun-code.git/data/db/mil-sigma.xml:39:        <model>Sigma 19mm f/2.8 EX DN</model>
$SOMEDIR/lensfun-code.git/data/db/mil-sigma.xml:52:        <model>Sigma 19mm f/2.8 EX DN</model>
$SOMEDIR/lensfun-code.git/data/db/mil-sigma.xml:65:        <model>Sigma 19mm f/2.8 EX DN</model>

**Comment by bronger** [comment]
I can see only two occurences, and both have different crop factors (which is part of the primary key).

**Comment by mandree** [comment]
well... try enabling tests and running them.
ctest -VV:
```
      Start 11: Database_integrity

11: Test command: /usr/bin/python "/home/mandree/VCS-other/lensfun-code.git/tools/check_database/check_database.py" "/home/mandree/VCS-other/lensfun-code.git/data/db"
11: Test timeout computed to be: 9.99988e+06
11: ERROR: Double primary key for lens!  ('sigma', 'sigma 19mm f/2.8 ex dn', 1.534)
11/11 Test #11: Database_integrity ......................***Failed    1.25 sec
```

**Comment by bronger** [comment]
Ah, thank you, fixed!
