### ISSUE TITLE
Canon 5DS not supported. Can I help add it?

### ISSUE THREAD

**Issue by criadoperez** [lensfun/lensfun#1259]
One the main professional Canon Cameras, the Canon 5DS is not supported. 
According to [this](https://wilson.bronger.org/lensfun_coverage.html) page, it can be added very easily. Can we add it somehow? Can I help to do it?. I own this camera.

**Comment by criadoperez** [comment]
I edited the code and made a pull request for this change. https://github.com/lensfun/lensfun/pull/1260

**Comment by uchrisu** [comment]
I have merged it to master. Please verify if it works, e.g., after lensfun-update-data. Then this issue can be closed.

**Comment by criadoperez** [comment]
Works. Thank you.
