### ISSUE TITLE
Python cleanup commit breaks builds on Ubuntu Xenial

### ISSUE THREAD

**Issue by CarVac** [lensfun/lensfun#1261]
https://github.com/lensfun/lensfun/commit/29eb38e1b4ecf70e34d85a8d194392600ff86822

The above commit breaks my AppImage build on Ubuntu Xenial (16.04). Instructing the build to use the previous commit makes the build work.

```
File "/home/travis/build/CarVac/filmulator-gui/lensfun/build/apps/setup.py", line 3
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/build/CarVac/filmulator-gui/lensfun/build/apps/setup.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I think it's from deleting the encoding lines.

**Comment by bronger** [comment]
Can you confirm that it’s the encoding lines? If so, I will immediately restore them.

**Comment by bronger** [comment]
According to https://docs.python.org/3.8/tutorial/interpreter.html#source-code-encoding, the encoding declaration should not be necessary. That said, if it helps with external workflows that are difficult to fix, I would restore them.

**Comment by CarVac** [comment]
I just tested, and I had the same issue on my home machine (running Ubuntu 20.04), but if I just added the encoding line back to apps/setup.py.in, then it works.

You don't have to add all of them back.
