### ISSUE TITLE
Where can I find the calibration info for "NIKKOR Z 24-70mm f/2.8 S"?

### ISSUE THREAD

**Issue by ethpi** [lensfun/lensfun#1263]
Hi,

many thanks for your great work on lens correction. I use lensfun really often with darktable. But now I got some photos made with a NIKKOR Z 24-70mm f/2.8 S and I miss it in my version of lensfun (0.3.2 shipped with Ubuntu 20.04.1). 

But at https://wilson.bronger.org/lensfun_coverage.html I read that lensfun covers the lens "NIKKOR Z 24-70mm f/2.8 S".  So I took the development version of lensfun showed here: https://lensfun.github.io/development/. But I can't find any calibration info for NIKKOR Z 24-70mm f/2.8 S in any file of lensfun/data/db that seems to belong to NIKKOR Z 24-70mm f/2.8 S

How can I add this lens to my local lensfun data directory?

**Comment by uchrisu** [comment]
Have you tried using the `lensfun-update-data` script? Simply run this command and it should install the most recent database in your personal folder.

**Comment by ethpi** [comment]
Thanks for your answer.

It took a wile till I noticed that I need the package liblensfun-bin. After this installation I ran `lensfun-data-update`. Everythings fine now.

And now the solution, why I didn't find the suitable lens: I looked in `slr-nikon.xml`, but "NIKKOR Z 24-70mm f/2.8 S" belongs to `mil-nikon.xml`. Sorry.
