### ISSUE TITLE
Calibration upload ceebaa

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#1278]
Calibration images were uploaded to the directory that starts with “`ceebaa_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

Additional comments by the uploader:

> Might have mistakenly uploaded twice, closed page too early first upload.
> Fujinon XF 16-80mm f/4 R OIS WR mounted on a Fujifilm X-T4. OIS and IBIS were turned off. Since the X-T4 body isn't in the database, a shot with a Canon EF-S 24mm f/2.8 attached to a Fringer EF-FX II adapter is also included. I have another set taken further back, but the building isn't large enough for the widest angle on that set.

**Comment by tuxfanx** [comment]
Unfortunately your pictures are not suitable for calibration. Please [read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how they have to be taken.
lens is included in db --> closed
