### ISSUE TITLE
Canon lens with double naming

### ISSUE THREAD

**Issue by criadoperez** [lensfun/lensfun#1281]
Canon lens appears as "Canon EF 24-105mm f/4L IS USM" and it's correct.
However it seems than sometimes (maybe different production batches of the same lens) it appears as "Canon EF 24-105mm f/4L IS"
This IS lens ALWAYS has USM, so it is the same lens. I have copied the values of "Canon EF 24-105mm f/4L IS USM"  into the new lens "Canon EF 24-105mm f/4L IS" 

Some exiv2    ###extracts:
Exif.Canon.LensModel                         Ascii      74  EF24-105mm f/4L IS  #USM
Exif.CanonCs.LensType                        Short       1  Canon EF 24-105mm f/4L IS # #1280 

Pull request #1280

**Comment by criadoperez** [comment]
Instead of adding a new lens, maybe we could also solve the issue but just adding the following line to the current lens:
`<model lang="en">Canon EF 24-105mm f/4L IS</model>`
Is this how it works?
If this is the preferred method, please let me know and I will make that change instead with a new pull request.

**Comment by tuxfanx** [comment]
lens recognition should work for both. "EF 24-105 mm 4.0 L IS USM" is the correct name for the lens, so "<model lang="en">Canon EF 24-105mm f/4L IS</model>" makes no sense --> closed
