### ISSUE TITLE
Calibration data for Canon EF-M 18-150mm 1:3.5-6.3 IS STM

### ISSUE THREAD

**Issue by illerfan** [lensfun/lensfun#1284]
Please add the calibration data for the "Canon EF-M 18-150mm 1:3.5-6.3 IS STM" lens or let me know how I could created the data myself. 

Any help is appreciated. Thanks a  lot.

**Comment by PeterWem** [comment]
To add calibration data for 18-150 one will need to have the lens in possession.
What you can do is to take the necessary raw files and upload them here. Tutorial is here and it will make you busy for a while https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
no pictures up to now --> closed
