### ISSUE TITLE
Request to add Panasonic Lumix DC-G91 to the camera List

### ISSUE THREAD

**Issue by ExpPhysU** [lensfun/lensfun#1286]
Please add the Panasonic Lumix DC-G91 to the mil-panasonic.xml camera list.

It has a  "Micro /4/3 System" Mount, and a crop factor of 2. It has the same sensor geometry as the Panasonic DC-G9, which is already in the database.

Depending on the region, the camera is sold as 
DC-G90
DC-G91
DC-G95
DC-G99

In my local database, the following code works with the DC-G91

    <camera>
        <maker>Panasonic</maker>
        <model>DC-G90</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G91</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G95</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G99</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>

Thanks for all your work!
Othmar Marti

**Comment by tuxfanx** [comment]
cameras are included in DB
