### ISSUE TITLE
Spurious > in lens name for Sony 70-200 F2.8 GM

### ISSUE THREAD

**Issue by FreddieWitherden** [lensfun/lensfun#1291]
The maker for the Sony FE 70-200mm F2.8 GM OSS is currently `Sony>` as opposed to `Sony`.

https://github.com/lensfun/lensfun/blob/5c78d634364abfe2b6d895a4ea3eb0be7367a294/data/db/mil-sony.xml#L1420

**Comment by junkyardsparkle** [comment]
Fixed, thanks for reporting!
