### ISSUE TITLE
Missing lens: NIKKOR AF-P 70-300 f/4.5-6.3G ED DX (the non-VR version)

### ISSUE THREAD

**Issue by jumbonionga** [lensfun/lensfun#1293]
I found that the aforementioned lens isn't showing in the development list. Theorically, it should be the same as the non-VR version, but if you need for me to provide some test photos, I can gladly do so.

**Comment by jumbonionga** [comment]
I'm glad you suggested darktable, as I'm using darktable on both an Ubuntu and Windows 10 PC and both of them won't show the lens, but rather "162". Now, I do have the VR version, and that lens does show up without issues. I'm attaching how the lenses show on darktable for reference.
![Captura de pantalla 2022-04-04 223835](https://user-images.githubusercontent.com/14968398/161679893-2a9cddb7-ad09-43b2-bb00-9bc49a8236bf.png)
.

**Comment by tuxfanx** [comment]
could you please [upload here](https://wilson.bronger.org/calibration) a raw picture for a test? Could not find any on the Internet

**Comment by jumbonionga** [comment]
I have a bunch of them, although none that complies with the guidelines shown on the site. I will have to scout and take some shots today.

**Comment by jumbonionga** [comment]
Sorry for the delay. I just uploaded the samples that I took recently. It has both JPGs and RAWs files.

**Comment by tuxfanx** [comment]
Have you taken the pictures with the VR or with the non VR Version? 
On my system (debian 11), the lens model is not identified by exiv2, but darktable depends on exiv2. Exiftool identifies the lens as a VR version. 
[exifdata.txt](https://github.com/lensfun/lensfun/files/8508207/exifdata.txt)

**Comment by jumbonionga** [comment]
I did it with the non VR Version. I also have the VR version and it does identify it properly. On ething that I find interesting is that darktable shows the Lens ID Number instead of the proper Lens ID.

**Comment by tuxfanx** [comment]
Darktable displays what exiv2 delivers and uses that to select the lens from the lensfun db. It's an exiv2 problem. If that is solved the lensfun db can be adjusted accordingly if it is necessary. You can [create an issue in the exiv2 project on github ](https://github.com/Exiv2/exiv2/issues) but the solution could take a long time to reach the users. 
Another solution might be to create an .exiv2 file with a corresponding entry (VR Version of the lens) [as described here ](https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/) but I haven't tested it with darktable.

**Comment by jumbonionga** [comment]
Thanks for the solutions. I will create the issue on the link that you provided so the information is propagated eventually to everyone, and I might try to add the information to the file as the article described.
