### ISSUE TITLE
Calibration data for Canon EF85mm f/1.4L IS USM

### ISSUE THREAD

**Issue by piratenpanda** [lensfun/lensfun#1295]
I followed the tutorial at https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ to create this file. I hope I did everything correctly but first tests look promising in darktable.

Correction data:
[lensfun.zip](https://github.com/lensfun/lensfun/files/5504795/lensfun.zip)

**Comment by MStraeten** [comment]
It’s already supported for slr since September 23

**Comment by piratenpanda** [comment]
Update database didn't provide it for me though. So then at least learned how to calibrate

**Comment by piratenpanda** [comment]
It still doesn't

**Comment by MStraeten** [comment]
On OSX i have .local/share/lensfun/updates/version_1 and .local/share/lensfun/updates/version_2 but lensfun-update-data just updates the version_1 directory. Darktable needs the version_1 directory so I’m fine ;)
Maybe you need to check this.
