### ISSUE TITLE
Support for sigma art 24-70 dg dn?

### ISSUE THREAD

**Issue by TTBFIRE** [lensfun/lensfun#1296]
Hello Guys, 
is there any lens correction support for the sigma art 24-70 dg dn? If yes where I can find it. I would be happy if someone could help me.
Greetings Tim.

**Comment by MStraeten** [comment]
If it’s not in https://github.com/lensfun/lensfun/blob/master/data/db/slr-sigma.xml then it’s not supported yet. You can do it yourself following https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ or provide the required images following https://wilson.bronger.org/calibration

**Comment by dhui** [comment]
Yeah, I've been using [my own calibrations](https://github.com/lensfun/lensfun/issues/1096#issuecomment-586668112)
