### ISSUE TITLE
Calibration request for Canon EF 70-200mm f/4L IS II USM Lens

### ISSUE THREAD

**Issue by cglosser** [lensfun/lensfun#1299]
Please consider adding a calibration for the Canon EF 70-200mm f/4L IS II USM Lens. I'd be happy to follow [the guide](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) and take the pictures if someone will review and coach me on the results :slightly_smiling_face:

**Comment by matt-maguire** [comment]
If you take the raw images and upload to the calibration service, someone will take a look and let you know if the images are ok or not, and if the images are ok they'll make the calculations and update the lensfun database.

https://wilson.bronger.org/calibration

**Comment by tuxfanx** [comment]
no pictures up to now --> closed
