### ISSUE TITLE
mil-panasonic.xml Please add Lumix DC-G90, DC-G91, DC-G95 and DC-G99

### ISSUE THREAD

**Issue by ExpPhysU** [lensfun/lensfun#1311]
The cameras Lumix DC-G90, DC-G91, DC-G95 and DC-G99 are newer Panasonic mirrorless cameras with an MFT mount and a cropfactor of 2. The numbers are aliases for different parts of the world. Could you please add them? I have included the text which works when included into the local database.
Thanks. Othmar Marti

    <camera>
        <maker>Panasonic</maker>
        <model>DC-G90</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G91</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G95</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>
    
    <camera>
        <maker>Panasonic</maker>
        <model>DC-G99</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
    </camera>

**Comment by MStraeten** [comment]
you can speed up the process by editing https://github.com/lensfun/lensfun/blob/master/data/db/mil-panasonic.xml yourself and initiating a pull request.

**Comment by ExpPhysU** [comment]
I did what you suggested, hoping that my request is documented enough.
Thanks for the hint.

**Comment by tuxfanx** [comment]
cameras are in included in db --> closed
