### ISSUE TITLE
Support for the new Fujifilm X-S10

### ISSUE THREAD

**Issue by dimk1** [lensfun/lensfun#1314]
Hello there,

is there a plan to include the new X-S10 from Fujifilm in Lensfun? How could I help to do so? Sample images perhaps?

thanks in advance

**Comment by dimk1** [comment]
Any updates on that? thanks

**Comment by MStraeten** [comment]
You might add it yourself to https://github.com/lensfun/lensfun/blob/master/data/db/mil-fujifilm.xml and initiate a pull request

**Comment by dimk1** [comment]
I did, as shown [here](https://github.com/lensfun/lensfun/pull/1322). I'm not sure of the crop factor though, how can I check that 1.534 is correct?

**Comment by tuxfanx** [comment]
x-s10 is included in DB
