### ISSUE TITLE
Missing lens in xml db but it is listed on website

### ISSUE THREAD

**Issue by sbradl** [lensfun/lensfun#1315]
Lens: Sony FE 35mm F2.8 ZA

According to https://wilson.bronger.org/lensfun_coverage.html the lens should be in the database.
Darktable does not let me select it and so I searched the database for it after running lensfun-update-data. The lens seems to be missing in mil-sony.xml.

Am I doing something wrong?

**Comment by sbradl** [comment]
Problem is that my new Sony A7C is in the file. After adding it manually the lens is detected

**Comment by MStraeten** [comment]
you can edit https://github.com/lensfun/lensfun/blob/master/data/db/mil-sony.xml file here and initiate a pull request - this speeds up the camera to be supported ;)

**Comment by sbradl** [comment]
I made the PR
