### ISSUE TITLE
Canon R in mil or slr files?

### ISSUE THREAD

**Issue by MStraeten** [lensfun/lensfun#1320]
The first RF lenses populates the mil-canon file. Could it be a better solution to integrate these and the R cameras in the slr-canon file since all EF lenses can be adapted there and so these can be supported for R cameras just by adding the R Mount. Since the adapter just compensates the missing space the lens parameters should be the same. 
The mil-camera contained the m series lenses which aren’t interchangeable with the R series

**Comment by sboukortt** [comment]
I thought the fact that they can be adapted without changes in the parameters was what the `compat` line was supposed to indicate. Is that not the case?

https://github.com/lensfun/lensfun/blob/3baedcb7f6c91be6286571732e86ba171f6b4f88/data/db/mil-canon.xml#L18

**Comment by MStraeten** [comment]
It’s the opposite: the ef lenses needs the R mount line.
My request is about storing similar things together since the R line is more comparable to the EF/EF-S SLR cameraline than the M line. (There‘s no interchangeability between M and R)
