### ISSUE TITLE
Calibration data for Voigtlander COLOR SKOPAR 20mm F3.5 SL-II Aspherical (Pentax KAF3)

### ISSUE THREAD

**Issue by DanceOfLight** [lensfun/lensfun#1347]
[Voigtlander_COLOR_SKOPAR_20mm_F3.5 SL-II_Aspherical.zip](https://github.com/lensfun/lensfun/files/5861898/Voigtlander_COLOR_SKOPAR_20mm_F3.5.SL-II_Aspherical.zip)

**Comment by DanceOfLight** [comment]
created using Andreas Schneider's python script. Happy to upload the original RAW files if anyone needs it.

**Comment by tuxfanx** [comment]
Your vignetting shots are asymmetrical. Something went wrong there. If you would like us to take over the distortion and tca data then please [upload your raw images here](https://wilson.bronger.org/calibration)
