### ISSUE TITLE
Calibration data for smc PENTAX-D FA 50mm F2.8 Macro

### ISSUE THREAD

**Issue by DanceOfLight** [lensfun/lensfun#1348]
[smc_PENTAX-D_FA 50mm_F2.8_Macro.zip](https://github.com/lensfun/lensfun/files/5861992/smc_PENTAX-D_FA.50mm_F2.8_Macro.zip)

**Comment by DanceOfLight** [comment]
created using Andreas Schneider's python script

**Comment by tuxfanx** [comment]
no answer --> closed
