### ISSUE TITLE
Calibration data for SAMYANG AF 45mm F1.8

### ISSUE THREAD

**Issue by GustavHaapalahti** [lensfun/lensfun#1362]
I updated the calibration data that was already available for SAMYANG AF 45mm F1.8 with vignetting data.
The data comes from running the calibration.py script by Torsten Bronger.
 
The attached file contains a complete <lens> section with the vignetting data pasted into the already available data.

[lensfun-merged.zip](https://github.com/lensfun/lensfun/files/6016382/lensfun-merged.zip)

**Comment by tuxfanx** [comment]
all correction data are contained in the database --closed
