### ISSUE TITLE
Add Support for Nikon Z6_2

### ISSUE THREAD

**Issue by talmholt** [lensfun/lensfun#1371]
<camera>
        <maker>Nikon Corporation</maker>
        <maker lang="en">Nikon</maker>
        <model>Nikon Z6_2</model>
        <model lang="en">Z6_2</model>
        <mount>Nikon Z</mount>
        <cropfactor>1</cropfactor>
    </camera>

**Comment by Sturmflut** [comment]
Fixed in lensfun@e6cd7aabdf2de44b0fb51d0a7bf8349a99d437be
