### ISSUE TITLE
Add "Nikon AF Nikkor 300mm f/4 IF-ED" to slr-nikon.xml

### ISSUE THREAD

**Issue by talmholt** [lensfun/lensfun#1374]
<lens>
        <maker>Nikon</maker>
        <model>Nikon AF Nikkor 300mm f/4 IF-ED</model>
        <model lang="en">Nikkor AF 300mm f/4 IF-ED</model>
        <mount>Nikon F AF</mount>
        <cropfactor>1</cropfactor>
        <calibration>
           <distortion model="ptlens" focal="300" a="0.00571001" b="-0.0266534" c="0.0462541"/>
            <vignetting model="pa" focal="300" aperture="4" distance="10" k1="-1.1272" k2="1.2909" k3="-0.6485"/>
            <vignetting model="pa" focal="300" aperture="4" distance="1000" k1="-1.1272" k2="1.2909" k3="-0.6485"/>
            <vignetting model="pa" focal="300" aperture="5.6" distance="10" k1="-0.1795" k2="-0.7529" k3="0.5416"/>
            <vignetting model="pa" focal="300" aperture="5.6" distance="1000" k1="-0.1795" k2="-0.7529" k3="0.5416"/>
            <vignetting model="pa" focal="300" aperture="8" distance="10" k1="0.1386" k2="-0.7053" k3="0.2723"/>
            <vignetting model="pa" focal="300" aperture="8" distance="1000" k1="0.1386" k2="-0.7053" k3="0.2723"/>
            <vignetting model="pa" focal="300" aperture="11" distance="10" k1="-0.1201" k2="0.2628" k3="-0.3309"/>
            <vignetting model="pa" focal="300" aperture="11" distance="1000" k1="-0.1201" k2="0.2628" k3="-0.3309"/>
            <vignetting model="pa" focal="300" aperture="16" distance="10" k1="-0.0734" k2="-0.0092" k3="0.0071"/>
            <vignetting model="pa" focal="300" aperture="16" distance="1000" k1="-0.0734" k2="-0.0092" k3="0.0071"/>
            <vignetting model="pa" focal="300" aperture="22" distance="10" k1="-0.0687" k2="-0.0306" k3="0.0279"/>
            <vignetting model="pa" focal="300" aperture="22" distance="1000" k1="-0.0687" k2="-0.0306" k3="0.0279"/>
            <vignetting model="pa" focal="300" aperture="32" distance="10" k1="-0.0706" k2="-0.0255" k3="0.0249"/>
            <vignetting model="pa" focal="300" aperture="32" distance="1000" k1="-0.0706" k2="-0.0255" k3="0.0249"/>
        </calibration>
    </lens>

**Comment by talmholt** [comment]
Here is a zip file with the xml file included.

x-special/nautilus-clipboard
copy
file:///media/user/Seagate%20Expansion%20Drive/DCIM/slr-nikon_add.zip

**Comment by talmholt** [comment]
Here is a file with the XML included

[slr-nikon_add.zip](https://github.com/lensfun/lensfun/files/6073138/slr-nikon_add.zip)

**Comment by tuxfanx** [comment]
In order to be able to check and accept your work, we need some raw images made with your lenses. The pictures for determining the vignetting would also be very helpful. you can upload the pictures [here](https://wilson.bronger.org/calibration)

**Comment by piratenpanda** [comment]
Why is it 300 here and 135 in the PR?

**Comment by tuxfanx** [comment]
included in db
