### ISSUE TITLE
Add "Tamron SP AF 150-600mm F/5-6.3 Di VC USD G2" to slr-tamron.xml

### ISSUE THREAD

**Issue by mharnis** [lensfun/lensfun#1382]
Please add the attached lens data to the lensfun data base.
[lensfun.xml.zip](https://github.com/lensfun/lensfun/files/6103601/lensfun.xml.zip)

You can find the raw files and calibration data at issue https://github.com/lensfun/lensfun/issues/1383

**Comment by gnl21** [comment]
I was going to add this lens but we have another submission for the same lens that doesn't seem to match. @mharnis, could you upload the original images somewhere so that I can test the different calibrations? (I don't have access to the calibration service uploads at the moment, but I'm working on that)

**Comment by mharnis** [comment]
https://drive.google.com/file/d/1QsCs98XGEchB8Rr7on3jY72lOdryQso4/view?usp=sharing

**Comment by gnl21** [comment]
That's perfect, thanks. I'll compare the different calibrations on these images and hopefully that'll suggest what to do.

**Comment by mharnis** [comment]
If not, let me know when I should take new pictures.

**Comment by gnl21** [comment]
The calibration looks fine. Thanks for the contribution. I'm just going to ask the other person who supplied data for this lens to check that this works for them as well.

**Comment by mharnis** [comment]
> The calibration looks fine. Thanks for the contribution. I'm just going to ask the other person who supplied data for this lens to check that this works for them as well.

No problem, it was a pleasure to contribute my part to the project.
