### ISSUE TITLE
Add "Nikon_AF-S_VR_Zoom-Nikkor_200-400mm_f/4G_IF-ED" to slr-nikon.xml

### ISSUE THREAD

**Issue by talmholt** [lensfun/lensfun#1384]
This file adds support for vignetting and distortion of the Nikon 200-400mm F/4 VR (1) lens.

Here is compressed version of the XML document to include into slr-nikon.xml

[lensfun_200-400mm_F4.zip](https://github.com/lensfun/lensfun/files/6133429/lensfun_200-400mm_F4.zip)

**Comment by tuxfanx** [comment]
if I had some images (e.g. the images used to generate the data) to test, I could put your data to the Db

**Comment by tuxfanx** [comment]
...no pictures found?

**Comment by talmholt** [comment]
Sorry about the delay in getting these images uploaded. I have uploaded them now using the tool, here is the link that it created for me. (Calibration upload 73a934 #1940) 

Regards,
Thomas
