### ISSUE TITLE
Add support for "Nikon AF-S Nikkor 50mm f/1.8G"

### ISSUE THREAD

**Issue by talmholt** [lensfun/lensfun#1387]
There is only support for TCA compensation for this lens in the lensfun database, here is distortion and vignetting.

[slr-Nikon.zip](https://github.com/lensfun/lensfun/files/6134982/slr-Nikon.zip)

**Comment by talmholt** [comment]
Is there anything I can do to accelerate the inclusion of this data into the public releases?

**Comment by Sturmflut** [comment]
I could only find an entry for the Nikon AF-S Nikkor 50mm f/1.8G that had only distortion, but no TCA. The linked pull request replaces the existing distortion data with your corrections and adds the vignetting data.
