### ISSUE TITLE
Add support for "Canon EF 24-105mm f/4L IS II USM"

### ISSUE THREAD

**Issue by navpp** [lensfun/lensfun#1390]
Please add support for "Canon EF 24-105mm f/4L IS II USM". You can find calibration files and results for distortion and tca in issue "Calibration upload 7a5773 #1319".

I am using the correction files now for 3 months and they seem to be fine.

Thanks and best regards, Bernhard

**Comment by tuxfanx** [comment]
lens data vor tca and distortion included in DB
