### ISSUE TITLE
Correction of mount in calibration data on Canon EF 24-105mm f/4L IS II USM for APS-C

### ISSUE THREAD

**Issue by navpp** [lensfun/lensfun#1391]
Hi, 

I just found out that the Canon EF 24-105mm f/4L IS II USM had been calibrated already but is listed wrong regarding its mount. It is an **EF** lens, not an **EF-s** Lens although the calibrator used an APS-C camera body. 

This is the entry in the data:

>   
      <lens>
         <maker>Canon</maker>
        <model>Canon EF 24-105mm f/4L IS II USM</model>
         <mount>Canon EF-S</mount>
         <cropfactor>1.605</cropfactor>
         <calibration>
             
             <distortion model="ptlens" focal="24" a="0.00188" b="-0.00884" c="-0.00325"/>
             <distortion model="ptlens" focal="35" a="0.00107" b="-0.0002" c="0.00016"/>
             <distortion model="ptlens" focal="50" a="0.00062" b="0.00184" c="0.00406"/>
             <distortion model="ptlens" focal="70" a="0.00053" b="0.00185" c="0.0047"/>
             <distortion model="ptlens" focal="85" a="0" b="0.00434" c="0"/>
             <distortion model="ptlens" focal="105" a="0" b="0.00352" c="0"/>
             <tca model="poly3" focal="24" vr="1.0005030" vb="0.9999680"/>
             <tca model="poly3" focal="35" vr="1.0002470" vb="1.0000232"/>
             <tca model="poly3" focal="50" vr="1.0001016" vb="0.9999803"/>
             <tca model="poly3" focal="70" vr="0.9999769" vb="0.9998732"/>
             <tca model="poly3" focal="85" vr="0.9998491" vb="0.9998315"/>
             <tca model="poly3" focal="105" vr="0.9997316" vb="0.9998092"/>
         </calibration>
     </lens>

This is how I think it should look like:
>
    <lens>
        <maker>Canon</maker>
        <model>Canon EF 24-105mm f/4L IS II USM</model>
        <mount>Canon EF</mount>
        <cropfactor>1.605</cropfactor>
        <calibration>
            
            <distortion model="ptlens" focal="24" a="0.00188" b="-0.00884" c="-0.00325"/>
            <distortion model="ptlens" focal="35" a="0.00107" b="-0.0002" c="0.00016"/>
            <distortion model="ptlens" focal="50" a="0.00062" b="0.00184" c="0.00406"/>
            <distortion model="ptlens" focal="70" a="0.00053" b="0.00185" c="0.0047"/>
            <distortion model="ptlens" focal="85" a="0" b="0.00434" c="0"/>
            <distortion model="ptlens" focal="105" a="0" b="0.00352" c="0"/>
            <tca model="poly3" focal="24" vr="1.0005030" vb="0.9999680"/>
            <tca model="poly3" focal="35" vr="1.0002470" vb="1.0000232"/>
            <tca model="poly3" focal="50" vr="1.0001016" vb="0.9999803"/>
            <tca model="poly3" focal="70" vr="0.9999769" vb="0.9998732"/>
            <tca model="poly3" focal="85" vr="0.9998491" vb="0.9998315"/>
            <tca model="poly3" focal="105" vr="0.9997316" vb="0.9998092"/>
        </calibration>
    </lens>

Anyway, just FYI, at least on my test pictures it looks like the barrel distortion on the wide side is a little "under corrected" but the tele side looks quite fine. 

Best regards
Bernhard

**Comment by gnl21** [comment]
I agree this looks like an obvious mistake. I'll push a fix now.
