### ISSUE TITLE
Add Tamron 17-28 mm F2.8 Di III RXD Sony E

### ISSUE THREAD

**Issue by xasi37** [lensfun/lensfun#1395]
Please add Tamron 17-28 mm F2.8 Di III RXD Sony E
Thank you

**Comment by axeleroy** [comment]
Hi @xasi37,

Just to let you know, there is a profile that is yet to be added in lensfun in #1430. I'm using it without issue.

Also, I'm not sure if you are aware of the profile creation process, but [you can provide pictures to help the developers](https://wilson.bronger.org/calibration) create a calibration profile for your desired lenses.

Have a good day!

**Comment by xasi37** [comment]
Hi Axel

Thank you for your information.
Where can I get that profile?
I already uploaded photos to the developers some weeks ago. It seems to take a lot of time to process them.

Have a good day
Alexander

**Comment by xasi37** [comment]
…
Just found the profile ;-)
Thank you
…
