### ISSUE TITLE
Add GoPro Hero9 Black

### ISSUE THREAD

**Issue by convolutionbbs** [lensfun/lensfun#1398]
Hello,
I would like to see GoPro Hero9 Black support for raw images in darktable.   I uploaded 3 new raw files from a new GoPro Hero9 Black to pixls.us. One outdoor with significant distortion, one outdoor with wide panorama, and one indoor for noise capture. I can take more as needed. The Hero4 gets fairly close, but it would be good to get the Hero9. With raw, you can't shoot linear and it's difficult to adjust the distortion on every image.

I posted over on darktable, but was told this is upstream item for lensfun.

Thanks!

**Comment by gnl21** [comment]
This is the upstream for lensfun, but I can't quite tell what you're asking for. If you're looking for distortion correction (the 'lens correction' module) then this is the right place, and if you link to the distortion file here then someone will have a look at calibrating it at some point. (The current backlog is quite large, though). If you want raw processing support then this isn't the right project, I'm afraid.

**Comment by convolutionbbs** [comment]
Yes - looking for lens distortion correction.  The raw format that GoPro uses is similar to DNG and darktable opens it just fine.  

I'm not sure what is needed beyond the raw file.  I submitted here: https://raw.pixls.us/

Here is the link to the specific raw file - I can, of course, generate any other information to get it on the backlog.

https://raw.pixls.us/getfile.php/4483/nice/GoPro%20-%20HERO9%20Black%20-%2016bit%20(4:3).GPR

Thanks!

**Comment by tuxfanx** [comment]
The picture is not suitable for calibration. Please [read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how it has to be taken
