### ISSUE TITLE
Nikon Z lenses: 14-30mm f4, 24-70mm f2.8, 70-200mm f2.8 (vignetting only)

### ISSUE THREAD

**Issue by BeakyBuzz** [lensfun/lensfun#1404]
Took me about 8 hours the first time, to install and figure out everything but I did what I wanted, and that is record the vignetting characteristics of my Z mount lenses. All done in a controlled environment using a flash bounced off a wall through a 1.5mm plastic white diffuser panel in contact with the front of the lens, focused at infinity. Managed to make it work in Darktable, sorry but I won't do a distortion or TCA correction. By the way, the 14-30 vignettes like crazy, lightroom did corrections automatically, no option to disable them.
[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/6304599/lensfun_calibration.zip)

**Comment by trougnouf** [comment]
Can this be combined with #1054 ? (distortion and TCA for the Nikkor 14-30 mm)

**Comment by Sturmflut** [comment]
I linked a pull request that has the data from this issue plus the TCA for the 14-30mm F4 lens from issue #1054. I left out distortion since since distortion data was not deemed good enough by its creator.

**Comment by Sturmflut** [comment]
There are now three different issues with data for this lens: this, #1200 and #1054. Each has partial data. Is someone maybe able to find out which combination of distortion, tca and vignetting data from the three data sets is the best?

**Comment by Sturmflut** [comment]
...and there is also a fourth one, #1494.

**Comment by Sturmflut** [comment]
The new pull request has the partial data for the Nikon Z 24-70mm f2.8 and 70-200mm f2.8 lenses provided in this issue.

**Comment by Sturmflut** [comment]
NIKKOR Z 14-30mm f/4 S merged in lensfun@c39ccac780ffec1a5d6e835f1b328ef44f77bdbe
