### ISSUE TITLE
Add support for the Fuji XF 16-80 F4

### ISSUE THREAD

**Issue by tcnsdca** [lensfun/lensfun#1414]
Please add support for the Fuji XF 16-80 F4

**Comment by gnl21** [comment]
In order to add a lens to the database we need some calibration images taken with the lens. If you have a copy of the lens and could supply some images the instructions are here: https://wilson.bronger.org/calibration

**Comment by tuxfanx** [comment]
is as FUJIFILM XF 16-80mm f/4 R OIS WR available with all calibration data in the database --> closed
