### ISSUE TITLE
Add support for Nikon Nikkor Z 70-200/2.8

### ISSUE THREAD

**Issue by Rematix** [lensfun/lensfun#1420]
It would be great if this fantastic lens could be added as well. If there is anything I can help pls let me know. Thanks!

**Comment by neuronmaker** [comment]
Yeah I was disappointed by that. If you have one of those maybe submit some RAW files for calibration. I am going to look for a grid-like pattern like a building with windows to at least give them the geometric distortion measurements.

**Comment by Sturmflut** [comment]
You can help by taking the necessary pictures if you have one, see

https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by neuronmaker** [comment]
> You can help by taking the necessary pictures if you have one, see
> 
> https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

I can take the images (barely) but due to time constraints that is already beyond my abilities. Time is short.

**Comment by Sturmflut** [comment]
I'm afraid that there's nothing that can be done until someone submits calibration images or the final calibration data.

**Comment by neuronmaker** [comment]
> I'm afraid that there's nothing that can be done until someone submits calibration images or the final calibration data.

I have sumitted some images for calibration that I think might just work. When I find the time I will take some more that are of a better subject and maybe try to run the program myself. For now I will hope the ones I submitted are sufficient.
