### ISSUE TITLE
Add support for "Sigma 35mm F/2 DG DN | C"

### ISSUE THREAD

**Issue by wwizark** [lensfun/lensfun#1426]
Please add support for the new Sigma lens. I couldn't get hugin to work as intended, the parameters I generated appeared to be incorrect.

**Comment by tuxfanx** [comment]
please upload pictures for calibration [here](https://wilson.bronger.org/calibration) and read how they should be created [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
