### ISSUE TITLE
DJI Air 2S - vignetting calibration data

### ISSUE THREAD

**Issue by ndesmoul** [lensfun/lensfun#1435]
Please find in attachment calibration data (vignetting only) for the DJI Air 2S.

[DJI_AIR2S_lensfun.zip](https://github.com/lensfun/lensfun/files/6642331/DJI_AIR2S_lensfun.zip)

**Comment by tuxfanx** [comment]
cropfactor 1.0? It has a 1 inch sensor, hasn't it? Could you upload your calibration pictures here?
