### ISSUE TITLE
Add support for Sony FE 24mm F2.8 G

### ISSUE THREAD

**Issue by k0a8t1o6** [lensfun/lensfun#1445]
This recent lens, released in March 2021, is not in the database. 
Please add it to the repository. I am happy to work on it based on an instruction available, if any.

**Comment by payano** [comment]
If you can create the lens calibration data, it would be great! More info down below.

[Lens calibration for Lensfun](https://wilson.bronger.org/lens_calibration_tutorial/)
[Upload calibration pictures](https://wilson.bronger.org/calibration)

**Comment by k0a8t1o6** [comment]
Uploaded data as below. Thank you.
https://github.com/lensfun/lensfun/issues/1463
