### ISSUE TITLE
add two compact cameras models (with calibration uploads)

### ISSUE THREAD

**Issue by jiemdev** [lensfun/lensfun#1455]
Hi, is it possible to add these cameras please? I plan to send soon pictures for lens calibration.
- Panasonic Lumix DMC-FH3 (EXIF Make = 'Panasonic', Camera Model Name = 'DMC-FH3')
- Samsung Digimax S600 (EXIF Make = 'Samsung Techwin', Camera Model Name = '<Digimax S600 / Kenox S600 / Digimax Cyber 630>', Image Description = '<Digimax S600 / Kenox S600 / Digimax Cyber 630>'

Thanks

**Comment by jiemdev** [comment]
Here are the files for calibration.
I could not upload them the normal way, sorry.

=> Panasonic DMC-FH3 compact camera.
Started to calibrate myself, not finished.
Please let me know if new pictures are needed.
This camera dont produce RAW and archive is rejected by automatic sending system.
Link : https://filesender.renater.fr/?s=download&token=d194311b-d9a3-4537-b18e-eeb818c7a99b
Note : this archive expires on 22th of August.

=> Samsung Digimax S600 compact camera.
Started to calibrate myself, not finished.
Please let me know if new pictures are needed.
This camera dont produce RAW and archive is rejected by automatic sending system.
Link : https://filesender.renater.fr/?s=download&token=c8ddc446-b466-4531-97e0-950c97a8917d
Note : this archive expires on 22th of August.

**Comment by tuxfanx** [comment]
links are expired / jpeg-Pictures are useless

**Comment by jiemdev** [comment]
So, lensfun project target only cameras capable of raw formats?
Compact cameras are often not very good regarding distortions and chromatic aberrations, I think it is worth it to calibrate them, even if we process jpegs then.
