### ISSUE TITLE
Canon RF 28-70mm f2 L USM

### ISSUE THREAD

**Issue by Sarastro40** [lensfun/lensfun#1465]
This recent lens is not in the database. Please add it. Many Thanks 

https://github.com/lensfun/lensfun/blob/master/data/db/mil-canon.xml

**Comment by PeterWem** [comment]
Have you taken the raw files needed? 
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
up to now no pictures --> closed
