### ISSUE TITLE
Voigtländer 12mm f/5.6 Monture Sony FE

### ISSUE THREAD

**Issue by ArnaultPhoto** [lensfun/lensfun#1469]
Hi,

This Lens is not in the data base, could you please add it.

Many thanks !

Arnault

**Comment by tuxfanx** [comment]
You have to [upload pictures](https://wilson.bronger.org/calibration) for that. Please [see here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) how they have to be taken

**Comment by tuxfanx** [comment]
no answer and no pictures --> closed

**Comment by ArnaultPhoto** [comment]
Hello,

TY for your answer and the link. I'll open a new one when I can take the
pictures.


Le jeu. 17 mars 2022 à 18:16, Joachim Daehnke ***@***.***> a
écrit :
