### ISSUE TITLE
Please add X-T4 to mil-fujifilm.xml

### ISSUE THREAD

**Issue by bachrocks** [lensfun/lensfun#1470]
Dear lensfun team

Please add the following text to the file, mil-fujifilm.xml. Only then, the X-T4 will be displayed as a camera model. The X-T4 has been supported by darktable since about a year or so.

I put the text to add in blockquote.

<blockquote>

<camera>
<maker>Fujifilm</maker>
<model>X-T4</model>
<mount>Fujifilm X</mount>
<cropfactor>1.5</cropfactor>
</camera>

</blockquote>

Kind regards,
Martin

**Comment by tuxfanx** [comment]
the automatic recognition and also the display of the camera works perfectly with darktable 3.8, database version 1, debian11
