### ISSUE TITLE
Calibration for "Canon EF 80-200mm f/4.5-5.6 II" identified as "Canon EF 80-200mm f/4.5-5.6"

### ISSUE THREAD

**Issue by John55h** [lensfun/lensfun#1484]
Calibration for "Canon EF 80-200mm f/4.5-5.6 II" is labelled "Canon EF 80-200mm f/4.5-5.6"
(Uploaded in https://github.com/lensfun/lensfun/issues/1173)
The lensfun calibration appears to be using exiv2 Exif.CanonCs.LensType (an integer from exif  tag) as the lens identifier. This resulting string is made up (by exiv2). Unfortunately both exiv2 and exiftool report an identical string for LensType 28 and 38 ("Canon EF 80-200mm f/4.5-5.6" is  28 and "Canon EF 80-200mm f/4.5-5.6 II" is 38).

```
$ exiv2 -pt  IMG_9824.jpg |grep -ai lens
Exif.CanonCs.LensType                        Short       1  Canon EF 80-200mm f/4.5-5.6
Exif.CanonCs.Lens                            Short       3  80.0 - 200.0 mm
Exif.Canon.LensModel                         Ascii      70  EF80-200mm f/4.5-5.6 II
Exif.Photo.LensSpecification                 Rational    4  80/1 200/1 0/0 0/0
Exif.Photo.LensModel                         Ascii      70  EF80-200mm f/4.5-5.6 II
Exif.Photo.LensSerialNumber                  Ascii      12  0000000000'
```

If the lens data is really for version II of the lens the database entry should indicate that.

Going forward it would be better to use the following tags in the priority order below:
Exif.Photo.LensModel  (Canon string from Exif 2.32)
Exif.Canon.LensModel (Canon string from makernote)
Exif.CanonCs.LensType (integer translated to a string by exiv2)

Please see: https://github.com/Exiv2/exiv2/issues/1906#issuecomment-925312454 for a more detailed explanation of the exif tags involved.

**Comment by tuxfanx** [comment]
Unfortunately, the uploaded pictures are no longer available and I couldn't find any on the internet either. Could you upload a raw image here for a test?

**Comment by tuxfanx** [comment]
no pictures uploaded. Exiv2 should be corrected.
