### ISSUE TITLE
Calibration data for Canon RF24-240mm F4-6.3 IS USM and RF50mm F1.8 STM

### ISSUE THREAD

**Issue by aadm** [lensfun/lensfun#1492]
Please add the attached lens data to the lensfun data base.
[lensfun_calibration_RF24-240-RF50.zip](https://github.com/lensfun/lensfun/files/7318340/lensfun_calibration_RF24-240-RF50.zip)

**Comment by Arie530** [comment]
Thanks Alessandro.  I have your profile for the 24-240 working in Affinity Photo.  It does an excellent job on the corrections.  Cheers, Arie

**Comment by EC1000** [comment]
Thanks for the calibration data @aadm. However, I think model names are missing "Canon" at the beggining (see issue https://github.com/lensfun/lensfun/issues/1504 and PR https://github.com/lensfun/lensfun/pull/1442). 

```
<model>Canon RF 24-240mm F4-6.3 IS USM</model>
(...)
<model>Canon RF 50mm F1.8 STM</model>
```
instead of:
```
<model>RF 24-240mm F4-6.3 IS USM</model>
(...)
<model>RF 50mm F1.8 STM</model>
```

**Comment by aadm** [comment]
> Thanks Alessandro. I have your profile for the 24-240 working in Affinity Photo. It does an excellent job on the corrections. Cheers, Arie

Well I didnt know Affinity Photo uses lensfun for correction! Glad it was useful also for other apps.

I havent had time to do vignetting correction (I need to get a piece of translucid glass or plastic first) but the distortion effects on this lens are remarkable and you really really need corrections.

**Comment by aadm** [comment]
> Thanks for the calibration data @aadm. However, I think model names are missing "Canon" at the beggining (see issue #1504 and PR #1442).
> 
> ```
> <model>Canon RF 24-240mm F4-6.3 IS USM</model>
> (...)
> <model>Canon RF 50mm F1.8 STM</model>
> ```
> 
> instead of:
> 
> ```
> <model>RF 24-240mm F4-6.3 IS USM</model>
> (...)
> <model>RF 50mm F1.8 STM</model>
> ```

I have corrected the names in the lensfun.xml and reattached the zipped file here. I hope this will be included soon in master (I have now realized that I uploaded the original files back in October and since then it has been left on its own... not sure what else I need to do?).

[lensfun_calibration_RF24-240-RF50_updated_names.zip](https://github.com/lensfun/lensfun/files/7656554/lensfun_calibration_RF24-240-RF50_updated_names.zip)

**Comment by Sturmflut** [comment]
The data for the RF 24-240mm F4-6.3 IS USM lens looks good, it matches on RAW images I found online.

There is a strange problem with the RF50mm F1.8 STM lens and exiv2 0.27.5 though:

```
$ exiv2 -pa /tmp/1G9A6157.cr3 | grep -i lens
Exif.Photo.LensSpecification                 Rational    4  50/1 50/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      16  RF50mm F1.8 STM
Exif.Photo.LensSerialNumber                  Ascii      11  9401004466
Exif.CanonCs.LensType                        Short       1  Canon RF 50mm F1.2 L USM
Exif.CanonCs.Lens                            Short       3  50.0 mm
Exif.CanonFi.RFLensType                      SShort      1  (280)
Exif.Canon.LensModel                         Ascii     138  RF50mm F1.8 STM
```

The sample files I have have been taken with the RF50mm F1.8 STM on a Canon EOS R6, which is correctly set in the Exif.Photo.LensModel and Exif.Canon.LensModel tags. But the Exif.CanonCs.LensType tag is wrong. At least darktable 3.8.0 picks up the wrong entry (Canon RF 50mm F1.2 L USM) and doesn*t match the lens.

If I set the RF50mm F1.8 STM profile manually, the corrections seem to be good.

**Comment by Sturmflut** [comment]
Merged in lensfun@de18df11cf5d8bb2d4317f7ba865b94263f1ec18 , but someone has to open a bug report for exiv2 for the RF50mm F1.8 STM lens.

**Comment by sarunasb** [comment]
@Sturmflut What do you see with `exiv -pv` (uninterpreted values)?

This might be a case of non-unique lens IDs used by manufacturers, an issue, which exiv2 refuses to fix, except offering users to maintain their own local .exiv2 catalogs. For example, https://github.com/Exiv2/exiv2/issues/397. exiv2/src/canonmn_int.cpp has the types and names data array and Canon RF 50mm F1.8 STM seems to be in a large pool of lenses with the same LensType…

**Comment by aadm** [comment]
@sarunasb @Sturmflut I have just checked with my brand new installation of darktable 3.8 + exiv2 0.27.5 and I see the same problem mentioned above for the RF50mm f1.8:

```
$ exiv2 -pa 20211208_CRP3776.cr3 | grep -i lens
Exif.Photo.LensSpecification                 Rational    4  50/1 50/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      16  RF50mm F1.8 STM
Exif.Photo.LensSerialNumber                  Ascii      11  9501002125
Exif.CanonCs.LensType                        Short       1  Canon RF 50mm F1.2 L USM
Exif.CanonCs.Lens                            Short       3  50.0 mm
Exif.CanonFi.RFLensType                      SShort      1  (280)
Exif.Canon.LensModel                         Ascii     138  RF50mm F1.8 STM
```

If I do `-pv` instead:

``
$ exiv2 -pav 20211208_CRP3776.cr3 | grep -i lens
0xa432 Photo        LensSpecification           Rational    4  50/1 50/1 0/1 0/1
0xa434 Photo        LensModel                   Ascii      16  RF50mm F1.8 STM
0xa435 Photo        LensSerialNumber            Ascii      11  9501002125
0x0016 CanonCs      LensType                    Short       1  61182
0x0017 CanonCs      Lens                        Short       3  50 50 1
0x003d CanonFi      RFLensType                  SShort      1  280
0x0095 Canon        LensModel                   Ascii     138  RF50mm F1.8 STM
```

**Comment by Sturmflut** [comment]
Checked the Canon RF 24-240mm F4-6.3 IS USM profile against images from #1065. Distortion does not correct perfectly. Looking into it.

**Comment by Sturmflut** [comment]
As described in #992, the Canon RF 24-240mm F4-6.3 IS USM has some optical pecularities that make it very hard to correct distortion with just three parameters (a, b, c). I re-tried to do distortion for 24mm, but it doesn't really get any better than what is already provided in this issue. TCA also looks fine.

**Comment by tuxfanx** [comment]
Both lenses have been added to the database for some time now. The 50mm lens is correctly recognized by Darktable
