### ISSUE TITLE
Calibration data for NIKKOR Z 14-30mm f4 S

### ISSUE THREAD

**Issue by outdoorbits** [lensfun/lensfun#1494]
Please add the attached lens data to the lensfun data base.
[NIKKOR_Z_14-30mm_f__4_S.zip](https://github.com/lensfun/lensfun/files/7367996/NIKKOR_Z_14-30mm_f__4_S.zip)

Thank you!

**Comment by Sturmflut** [comment]
I linked three other issues that have (partial) data for this lens. Is someone maybe able to find out which combination of distortion, tca and vignetting data from the four data sets is the best?

**Comment by Sturmflut** [comment]
Merged in lensfun@c39ccac780ffec1a5d6e835f1b328ef44f77bdbe
