### ISSUE TITLE
Samsung Mobile Phones (Additional Models Required)

### ISSUE THREAD

**Issue by Funky-Monkey-MoHawk** [lensfun/lensfun#1499]
Hello,
I've noticed that the lens data for Samsing mobile phones is somewhat lacking.
I have the S20+  and there doesn't seem to be anything available.

Is there a possibilty of more recent Samsung handsets being added please?

**Comment by Sturmflut** [comment]
Someone has to provide reference images for the cameras. You can follow the tutorial at https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ to create them.
