### ISSUE TITLE
Model name for Canon RF lenses

### ISSUE THREAD

**Issue by EC1000** [lensfun/lensfun#1504]
In mil-canon.xml, two lenses are named without 'Canon' at the beginning: 
`<model>RF24-105mm F4 L IS USM</model>`
`<model>RF70-200mm F2.8 L IS USM</model>`

In darktable, used with exiv2 v0.27.4, and cytrinox cr3 branch for rawspeed (https://github.com/darktable-org/rawspeed/pull/271), it causes the lens not to be found (for the 24-105, but I supposed it is the same for the other one).  

Adding 'Canon' at the beginning allows the lens to be properly detected: 
`<model>Canon RF24-105mm F4 L IS USM</model>`

It is already like this for: 
- this other RF lens : `<model>Canon RF85mm F1.2L USM</model>`
- all other Canon lenses (EF mount), for example: `<model>Canon EF 35-105mm f/4.5-5.6</model>`

Could this be changed? 
Thanks!

**Comment by EC1000** [comment]
I searched for related bug before submitting this one, but forgot to looked at PR. 
This is already taken care by https://github.com/lensfun/lensfun/pull/1442 (well, "will be" when merged!).

**Comment by gnl21** [comment]
This should have been resolved by #1442. Please reopen if there are still issues here.
