### ISSUE TITLE
Question about vignette correction

### ISSUE THREAD

**Issue by cedricp** [lensfun/lensfun#1507]
Hi, I'm using this library for a raw video tool I'm coding, the distortion is working well, but I'm wondering if there's any kind of tone mapping applied (gamma correction) on vignetting correction.
To speed up process, I give Lensfun a floating point image filled with value 1.0f, then I use that baked map with a GLSL compute shader as a scalar map. Is it a correct way of doing it ? (I feel like the borders are too bright)
Just another little question, is it possible to shift the lens center ?
Best regards.

**Comment by seebk** [comment]
I think it is documented somewhere in the manual https://lensfun.github.io/manual/latest/index.html but cannot find it right now. As far as I remember TCA and vignetting profiles are retrieved from linear RGB RAW data whenever a camera supports RAW files. For other camereas, profiles are based on default JPEG settings. 

So in your case you should try to apply vignetting correction as early as possible and before any gamma correction.

**Comment by seebk** [comment]
Regarding the lens center: Yes there is a `CenterX` and `CenterY` parameter in the `lfLens` class. [lfLens ](https://lensfun.github.io/manual/latest/structlfLens.html#ab4c9227e83a649614a642b986e77c2e9)

**Comment by cedricp** [comment]
That's exactly what I do, but I need to apply an inverse gamma correction (1/2.2) to my scene linear color data to get an acceptable result. I looked in the code, but did not find something useful.
Oh, and yes, I found the X-Y lens shift, thanks !

**Comment by cedricp** [comment]
Perhaps the problem is I don't use native sensor aspect ratio (as I work with MagicLantern MLV files), I have a 1:1 (square) pixel AR, but a frame AR of 16:9... What do you think ?

**Comment by seebk** [comment]
Yes this could be a problem. Ideally, all lensfun corrections have to be applied to the uncropped image with the dimensions from the camera sensor. This is how the profiles have been measured.

**Comment by cedricp** [comment]
Doing some images operations to get the camera sensor aspect ratio seems to fix the problem, thank you.

**Comment by Sturmflut** [comment]
Can this issue be closed?

**Comment by cedricp** [comment]
So far, so good. Closing
