### ISSUE TITLE
Calibration data upgrade for Sigma 18-50mm f/2.8 EX DC

### ISSUE THREAD

**Issue by pahervin** [lensfun/lensfun#1510]
I added TCA calibration for the Sigma 18-50mm f/2.8 EX DC lens (see the attached zip).
I redid the distortion calibration for more focal lengthes, and check the calibration with darktable.
The calibration was generated  with the Andreas Schneider script.

I suggest  to modify the delivered slr-sigma.xml like below. I removed the useless mounts for the crop factor. With this setting darktable properly get lens calibration.
```xml
<lens>
    <maker>Sigma</maker>
    <model>Sigma 18-50mm f/2.8 EX DC</model>
    <mount>Sigma SA</mount>
    <mount>Nikon F AF</mount>
    <!-- Average crop factor of non-Canon APS-C cameras -->
    <cropfactor>1.53</cropfactor>
    <calibration>
        <distortion model="ptlens" focal="18" a="0.012979" b="-0.036394" c="0"/>
        <distortion model="ptlens" focal="23" a="0.007147" b="-0.017687" c="0"/>
        <distortion model="ptlens" focal="28" a="0" b="0" c="0"/>
        <distortion model="ptlens" focal="34" a="0" b="0.001032" c="0"/>
        <distortion model="ptlens" focal="50" a="0" b="0.002512" c="0"/>
    </calibration>
</lens>
<lens>
    <maker>Sigma</maker>
    <model>Sigma 18-50mm f/2.8 EX DC</model>
    <mount>Canon EF</mount>
    <!-- Average crop factor of Canon APS-C cameras -->
    <cropfactor>1.611</cropfactor>
    <calibration>
        <distortion model="ptlens" focal="18" a="0.011366" b="-0.034328" c="0"/>
        <distortion model="ptlens" focal="21" a="0.006142" b="-0.017401" c="0"/>
        <distortion model="ptlens" focal="24" a="0.0048" b="-0.013589" c="0"/>
        <distortion model="ptlens" focal="28" a="0" b="0" c="0"/>
        <distortion model="ptlens" focal="35" a="0" b="0.002094" c="0"/>
        <distortion model="ptlens" focal="43" a="0" b="0.002878" c="0"/>
        <distortion model="ptlens" focal="50" a="0" b="0.003021" c="0"/>
     </calibration>
</lens>
```

[lensfun.zip](https://github.com/lensfun/lensfun/files/7566617/lensfun.zip)

If needed , i can upload the RAW files.

**Comment by Sturmflut** [comment]
I agree about removing the Canon EF mount from the 1.53 crop factor entry, but there is a model of this lens for Pentax KAF and the new entry you submitted also has a `<mount>Pentax KAF</mount>` tag.

I'll attach a pull request that has the change.

**Comment by pahervin** [comment]
> I agree about removing the Canon EF mount from the 1.53 crop factor entry, but there is a model of this lens for Pentax KAF and the new entry you submitted also has a `<mount>Pentax KAF</mount>` tag.
> 
> I'll attach a pull request that has the change.

I did the calibration for the new entry with a Pentax. But I dont permit myself to merge it with Nikon calibration.
The crop factor for Pentax it 1.5. That also why I did not merge the claibration.

**Comment by Sturmflut** [comment]
Data for this lens was identical for all mounts and not great to begin with. If the distortion data improves the situation on Pentax KAF, it most likely also improves it on Nikon F and Sigma SA.

**Comment by pahervin** [comment]
> Data for this lens was identical for all mounts and not great to begin with. If the distortion data improves the situation on Pentax KAF, it most likely also improves it on Nikon F and Sigma SA.

Ok, I will merge datas for the 3 mounts, and I will notice you.

**Comment by pahervin** [comment]
> > Data for this lens was identical for all mounts and not great to begin with. If the distortion data improves the situation on Pentax KAF, it most likely also improves it on Nikon F and Sigma SA.
> 
> Ok, I will merge datas for the 3 mounts, and I will notice you.

Here is the merge of the lense calibration for the lense.

[lensfun-Sigma-18-50.zip](https://github.com/lensfun/lensfun/files/7846122/lensfun-Sigma-18-50.zip)

**Comment by Sturmflut** [comment]
The pull request has the merged data.

**Comment by tuxfanx** [comment]
@pahervin: could you please upload [here](https://wilson.bronger.org/calibration) some sample pictures for a test? 
Couldn't find any.
