### ISSUE TITLE
Lens Profile "M.Zuiko Digital ED 12‑45mm F4 PRO" for Affinity Photo

### ISSUE THREAD

**Issue by StraightHorizon** [lensfun/lensfun#1514]
Hi Support,

As far as I can determine, there doesn't yet appear to be any lens correction available for "M.Zuiko Digital ED 12‑45mm F4 PRO" in Affinity Photo via the lensfun database.

Are there plans to add support for the 12-45 in the calibration database?

Many thanks.

Steven

**Comment by sarunasb** [comment]
Distortion and TCA corrections pushed to Lensfun DB (mil-olympus.xml).
Calibration upload a2d5f6_luismavseabra.

**Comment by andyrtr** [comment]
Does this fully resolve https://github.com/lensfun/lensfun/issues/1345 ?

**Comment by sarunasb** [comment]
Lens is correctly identified by darktable 3.6.1 (Ubuntu 21.10).

This changes nothing for exiv2 0.27.3.

**Comment by sarunasb** [comment]
#1345 has a much fuller correction parameter set for 12-45mm f/4 Pro. Testing it with calibration images from upload a2d5f6.

**Comment by sarunasb** [comment]
Pushed as commit b7ea8e8.
