### ISSUE TITLE
Sony FE 24mm 2.8 G distortion

### ISSUE THREAD

**Issue by learnintocode** [lensfun/lensfun#1517]
I saw there was a correction request that sent in images back in early July, but still no correction profile for the crazy distortion on this lens.  New to all of this, but is there any fix incoming soon?

**Comment by PeterWem** [comment]
It may be faster for you to create it yourself meanwhile waiting for #1463 
https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/

**Comment by Sturmflut** [comment]
> https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/

I would suggest to go straight for https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ instead. The page mentioned before is unclear on important things, e.g. when to take the pictures for vignetting correction and how to expose them correctly.

**Comment by tuxfanx** [comment]
distortion and tca data are in DB included --> close

**Comment by uchrisu** [comment]
I would suggest to change the coefficient to

            <distortion model="ptlens" focal="24" a="0.00998124592333708" b="-0.059476125385851814" c="0.015512336522357898" />
            <tca model="poly3" focal="24" vr="1.0003896183233933" cr="0.0002103335109420862" br="-0.00023809829391298307" vb="0.9999755575322654" cb="-0.0005144022628139341" bb="0.00037842875101582124" />

The result (especially distortion) is much better.

I created a pull request #1658

**Comment by Sturmflut** [comment]
> I would suggest to change the coefficient to
> 
> ```
>         <distortion model="ptlens" focal="24" a="0.00998124592333708" b="-0.059476125385851814" c="0.015512336522357898" />
>         <tca model="poly3" focal="24" vr="1.0003896183233933" cr="0.0002103335109420862" br="-0.00023809829391298307" vb="0.9999755575322654" cb="-0.0005144022628139341" bb="0.00037842875101582124" />
> ```
> 
> The result (especially distortion) is much better.
> 
> I created a pull request #1658

Question on the side: how do you generate values with such high precision? My Hugin seems to output at most four digits after the decimal point.

**Comment by sarunasb** [comment]
Do we know how much of a precision makes sense in lensfun? Wouldn't 5–6 significant digits be more than enough?

**Comment by uchrisu** [comment]
Yes, probably you are right. I extracted the data from the exifs and fitted a curve. 
On the other side I would say that the few additional bytes are not so "expensive" anymore. Maybe I can truncate the numbers after lets say 7 digits in the future?

**Comment by sarunasb** [comment]
> Yes, probably you are right. I extracted the data from the exifs and fitted a curve. On the other side I would say that the few additional bytes are not so "expensive" anymore. Maybe I can truncate the numbers after lets say 7 digits in the future?

Yes, 7 digits should suffice, as much as I understand.

**Comment by tuxfanx** [comment]
merged --> close
