### ISSUE TITLE
Calibration data for Fujifilm XF16-80mmF4 R OIS WR

### ISSUE THREAD

**Issue by tuhlmann** [lensfun/lensfun#1519]
Please add the attached lens data to the lensfun data base.

[Fujifilm_XF16-80mmF4_R_OIS_WR.zip](https://github.com/lensfun/lensfun/files/7632770/Fujifilm_XF16-80mmF4_R_OIS_WR.zip)

Thank You!

**Comment by Ozerthaye** [comment]
I see lot of data and some commits for this specific lens in github and I would really appreciate it being added. Is there anything needed like additional images or xml's that I could assist with?
Cheers, ozer

**Comment by tuhlmann** [comment]
@Ozerthaye The images I used to calculate chromatic aberrations could be improved. I didn't really find images with high contrast edges throughout the image. If you could provide them according to the "Chromatic Aberrations (TCA)" section in https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ I could add them and recalculate TCA.

Also, I'm using the calibration data installed in my local directory, that way I can use it even without being added to lensfun and then to Darktable (that's what I'm using it with).
The local directory on Linux would be `~/.local/share/lensfun` and I attach the XML I'm using here for reference:

[lensfun.zip](https://github.com/lensfun/lensfun/files/7796040/lensfun.zip)

**Comment by tuxfanx** [comment]
complete correction is in DB included -> closed
