### ISSUE TITLE
Vignetting for Tamron 17-28mm F/2.8 Di III RXD

### ISSUE THREAD

**Issue by dopro17** [lensfun/lensfun#1520]
[lensfun.zip](https://github.com/lensfun/lensfun/files/7644730/lensfun.zip)
Please add the attached lens data to the lensfun data base.

Full data with vignneting pdf charts [Tamron_1728_F2.8_Di_III_RXD.zip](https://cloud.dweiss.com.br/s/rLGHLunArJB3Af1)

PS. Won't work in darktable with lens firmware 1.0 (shipped with a lot of lenses) so need to update the lens firmware.

Thanks

**Comment by dopro17** [comment]
Cant upload files!!!! Help

**Comment by PeterWem** [comment]
Do you have Exif of the lens before and after firmware update?

**Comment by dopro17** [comment]
Yeah. As you can see in the first attachment, the focus distance is stuck at low values with v1.0 firmware. [
[tamron1728_exif_dump.txt](https://github.com/lensfun/lensfun/files/7654361/tamron1728_exif_dump.txt)
](url)
And with v3.0 firmware.
[tamron1728_exif_dump_v3.0.txt](https://github.com/lensfun/lensfun/files/7654373/tamron1728_exif_dump_v3.0.txt)
But this problem is related to darktables when processing wrong exif data from tamron, the vignetting correction is working as expected after the firmware update.

**Comment by dopro17** [comment]
Is this done?

**Comment by PeterWem** [comment]
I am just a user like you. I can try to send a pull request with your vignetting correction, but nothing else that I have sent to Lensfun has been aprpoved. Now when you have taken vignetting correction, don't you want to add distortion correction and tca correction also before sending it in?
I found a grey fence with white background very useful for tca corrections https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/

**Comment by dopro17** [comment]
> I am just a user like you. I can try to send a pull request with your vignetting correction, but nothing else that I have sent to Lensfun have been approved. Now when you have taken vignetting correction, don't you want to add distortion correction and tca correction also before sending it in? I found a grey fence with white background very useful for tca corrections https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/
I saw that distortion correction was already done for this lens in the development version. Hope they add my data.
The gray fence idea is really cool, I hadn't thought of it. Thanks!

**Comment by PeterWem** [comment]
I see. I thought the one in the database was the first Tamron version and this one in this isse the third version, III. A bit confused from the name. 
Take the picture need for tca correction and publish it here, or upload the raw file, and I will try to add everyting in a pull request.

**Comment by tuxfanx** [comment]
@dopro17: with some focal lengths the vignetting correction is clearly noticeable with other focal lengths hardly or not at all. I have tested this with raw pictures [from the Internet](https://www.dpreview.com/sample-galleries/6261005114/tamron-17-28mm-f2-8-di-iii-rxd-sample-gallery/). However, the settings of these are not known to me in part. Maybe you could upload us your shots for vignetting calibration and some pictures for checking.
