### ISSUE TITLE
Sharing my Canon RF14-35 f/4 lensfun.xml

### ISSUE THREAD

**Issue by pszaban** [lensfun/lensfun#1528]
Hello,
    Thanks so much for creating and supporting lensfun!  Here's the lensfun.xml I created for my Canon RF14-35 F4 L IS USM lens. Feel free to use or discard it as you choose. I had to convert my camera's .CR3 raw files to .DNG before running calibrate.py, but that is probably part of the workflow anyone would perform for now, until .CR3 files are natively supported better on Linux.  I had to rename lensfun.xml to lensfun_xml.txt to be able to upload the file.
[lensfun_xml.txt](https://github.com/lensfun/lensfun/files/7704643/lensfun_xml.txt)

**Comment by PeterWem** [comment]
Why is 35mm distortion showing             <distortion model="poly3" focal="35" k1="0.000"/>

**Comment by pszaban** [comment]
PeterWen: Thanks for checking that.! Sorry, I made a typo in lenses.txt, and left out one comma on the 35mm distortion line... It should have been:
distortion(35mm) = 0.002, -0.002, -0.005
    I attached the new xml file
[lensfun_xml.txt](https://github.com/lensfun/lensfun/files/7711701/lensfun_xml.txt)

**Comment by PeterWem** [comment]
https://youtu.be/_p0fR-nH6cU?t=299 You get more exact values like this.

**Comment by pszaban** [comment]
PeterWem: I followed  the instructions in the link you sent; it is slightly different from the other instructions I previously found. There are many more significant digits now. I attached the updated .xml file.  Please let me know if there are any problems, I will be happy to try to fix them. Once I get the procedure correct, I will do this again for my other lens.THANK YOU!
[lensfun_xml.txt](https://github.com/lensfun/lensfun/files/7714684/lensfun_xml.txt)

**Comment by pszaban** [comment]
PeterWem: I ran hugin again on ALL the distortion images, and added my other lens.  The latest lensfun.xml is attached for BOTH of my lenses.  It seems strange to me that the distortion numbers are so different from two runs  I probably selected different horizontal lines on the second run.

[lensfun_xml.txt](https://github.com/lensfun/lensfun/files/7720772/lensfun_xml.txt)

**Comment by PeterWem** [comment]
Did a pull request here https://github.com/lensfun/lensfun/pull/1505/commits/33165f7715e8378be39a8ba8f9253306887e72fd

**Comment by pszaban** [comment]
Cool!   Thank You!
