### ISSUE TITLE
calibration data for Fujifilm X100V and X100V with WCL-X100 / TCL-X100

### ISSUE THREAD

**Issue by tuxfanx** [lensfun/lensfun#1529]
Here are my lensfun.xml for the Fujifilm X100V. The file contains the correction data for the revised 23mm fix standard lens itself and the data for use with the two converter lenses WCL-X100 and TCL-X100.
Fujifilm has revised the previous standard lens of the X100 series (X100, X100S, X100T, X100F) for the X100V for the first time. Now, in the X100V, the 23mm fix Lens contains one more aspherical lens ( https://fujifilm-x.com/en-gb/products/cameras/x100v/ ). For this reason I have introduced a new mount "fujix100v2" for the X100V in my lensfun.xml. The X100V is currently still entered with the mount "fujix100", which is intendet for the previous X100-series lens, in the official lensfun-database.
I generated the calibration-data by using calibrate.py. I tested the calibration with darktable.
My calibration directory with all files can be viewed here: https://jonani1.my-router.de/nextcloud/index.php/s/BCisJGepLLjyz8Y  with the password: x100v2021

[lensfun.zip](https://github.com/lensfun/lensfun/files/7721790/lensfun.zip)

**Comment by tuxfanx** [comment]
changed tca to complex-tca in lensfun.xml

**Comment by Sturmflut** [comment]
Isn't it enough to call the new mount "fujix100v"?

If the commit in Sturmflut/lensfun@4a9b7a4b56c4d21c3a4658c94c14bb30da4871f2 is okay, I can turn it into a pull request.

**Comment by tuxfanx** [comment]
> Isn't it enough to call the new mount "fujix100v"?
> 
> If the commit in [Sturmflut/lensfun@4a9b7a4](https://github.com/Sturmflut/lensfun/commit/4a9b7a4b56c4d21c3a4658c94c14bb30da4871f2) is okay, I can turn it into a pull request.

Excuse me, I forgot to close this Issue after sending my own PR 1553 for the X100V, so there will be 2 PR's for the same if you turn your commit to a PR. I am sorry about my mistake, I'm new to github.

fujix100v would be working too. I thought of "version 2" when I got v2 as an appendix for the new mount. Fuji has added a Roman two to the engraving on the lens. In the future it could be, that Fuji brings out more cameras of the X100 series with the new version-II lens. 
I will close this issue. My PR contains a few minor changes (white spaces and blank lines) from my data in this issue. It awaiting approval now because It is my first PR. Are you a contributer or maintainer of the lensfun projekt?
What do we do now?

**Comment by tuxfanx** [comment]
I generated a PR for this case.

**Comment by Sturmflut** [comment]
I'm just a contributor and also waiting for my pull requests to be merged. In this case I'll cancel my PR.
