### ISSUE TITLE
Calibration update Leica Summicron-TL 1:2/23 Asph.

### ISSUE THREAD

**Issue by tuxfanx** [lensfun/lensfun#1536]
Please replace the correction data I created in December 2018 with the new data. The new file contains the correction data for vignetting and a slightly better distortion correction. 
I generated the calibration-data by using calibrate.py and tested the calibration with darktable.
My calibration directory with all files can be viewed here: https://jonani1.my-router.de/nextcloud/index.php/s/3Q8Rj5kmcBYr5js 
with the password: leicacl2021
[lensfun.zip](https://github.com/lensfun/lensfun/files/7757366/lensfun.zip)

**Comment by Sturmflut** [comment]
I've linked a pull request that has the data.

**Comment by tuxfanx** [comment]
> I've linked a pull request that has the data.
Thank's
