### ISSUE TITLE
Bug with MIL-Olympus.xml file

### ISSUE THREAD

**Issue by regor250** [lensfun/lensfun#1544]
The "Olympus M.Zuiko Digital ED 40-150mm f/2.8 Pro + 1.4x converter" lens profile is preventing all other profiles then after from showing up in ACDSee Ultimate.  Several issues are present.  None of the lens models use the EXIF Lens Model name, hence preventing automatic detection.  The 30mm lens is missing Distortion profile, hence preventing the profile to be available for use even if no distortion correction is needed. The attached file includes the needed corrections to work properly in ACDSee.
[mil-olympus_v3.zip](https://github.com/lensfun/lensfun/files/7775185/mil-olympus_v3.zip)

**Comment by Sturmflut** [comment]
This doesn't seem to be a bug in the database, but in ACDSee. I guess the exceptionally long name?

The file seems to be based on an older database version. It looks like you replaced the

`<model>Olympus M.Zuiko Digital ED 40-150mm f/2.8 Pro + 1.4x converter</model>`

with

`<model>M.40-150mm F2.8 + MC-14</model>`

is that correct? Do you know what exactly causes the problem in ACDSee, does a slightly shorter name (e.g. `Olympus M.Zuiko Digital ED 40-150mm f/2.8 Pro + MC-14 conv.`) also fix it?

**Comment by regor250** [comment]
Hello Sturmi,

I have since been able to determine that what made the database file fail in ACDSee was not the long English (en) Model for the lens, but the Dutch (de) version of the Model for that lens.  Most likely an ACDSee issue, but once I removed the extra Dutch(de) Model description, the file worked OK.  Another issue with the file is that few of the Model names corresponded to the EXIF Metadata version of the same, hence preventing auto-detection.  The attached file has the corrected Model, and “English” Model of the lenses models that correspond to EXIF and Olympus Lens Map description of the lenses (Olympus is not consistent in how it refers to its lenses, which is frustrating!).  Another issue, again perhaps with ACDSee, is that it didn’t work if a lens model has no Distortion data (30mm macro), adding Distortion data with zero values resolved that issue.  Last but not least, and this is an ACDSee issue also I believe, it will not take any version of the database other than 1.0; changing the version value from 2.0 to 1.0 resolved that issue.   I raised these issues with ACDSee.  Don’t pay attention to the version of the file attached, it’s a local tracking number for myself.

Cheers,

Roger





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Sturmflut** [comment]
Hi Roger,

"de" is German, not Dutch :)

I cross-referenced it with some sample shots from the Internet, and you're right. As a German national I also think the German model name does not add anything over the English description.

The linked pull request has the necessary changes.
