### ISSUE TITLE
Calibration data for Sony FE 100-400mm GM OSS

### ISSUE THREAD

**Issue by zemumu** [lensfun/lensfun#1547]
Hello,

Here is data with vignetting for Sony FE 100-400mm f/4.5-5.6 GM OSS
The calibration was generated with the Torsten Bronger’s python script.

Thanks to add the lens data to the lensfun data base.

best regards
Vincent

`<lensdatabase>

    <lens>
        <maker>Sony</maker>
        <model>FE 100-400mm f/4.5-5.6 GM OSS</model>
        <mount>Sony E</mount>
        <cropfactor>1</cropfactor>
        <calibration>
            
            <distortion model="poly3" focal="100" k1="0.00301"/>
            <distortion model="poly3" focal="158" k1="0.00698"/>
            <distortion model="poly3" focal="198" k1="0.00727"/>
            <distortion model="poly3" focal="294" k1="0.0072"/>
            <distortion model="poly3" focal="400" k1="0.00661"/>
            <tca model="poly3" focal="100" vr="1.0001317" vb="1.0000276"/>
            <tca model="poly3" focal="158" vr="1.0001303" vb="0.9999412"/>
            <tca model="poly3" focal="198" vr="1.0000913" vb="0.9999411"/>
            <tca model="poly3" focal="294" vr="0.9999624" vb="0.9999690"/>
            <tca model="poly3" focal="400" vr="0.9998627" vb="0.9998931"/>
            
            <vignetting model="pa" focal="100" aperture="4.5" distance="10" k1="-0.1770" k2="-0.3459" k3="0.2428"/>
            <vignetting model="pa" focal="100" aperture="4.5" distance="1000" k1="-0.1770" k2="-0.3459" k3="0.2428"/>
            <vignetting model="pa" focal="100" aperture="5.6" distance="10" k1="0.0717" k2="-0.6123" k3="0.3333"/>
            <vignetting model="pa" focal="100" aperture="5.6" distance="1000" k1="0.0717" k2="-0.6123" k3="0.3333"/>
            <vignetting model="pa" focal="100" aperture="8" distance="10" k1="-0.1051" k2="-0.1628" k3="0.0636"/>
            <vignetting model="pa" focal="100" aperture="8" distance="1000" k1="-0.1051" k2="-0.1628" k3="0.0636"/>
            <vignetting model="pa" focal="100" aperture="11" distance="10" k1="-0.3151" k2="0.4502" k3="-0.4904"/>
            <vignetting model="pa" focal="100" aperture="11" distance="1000" k1="-0.3151" k2="0.4502" k3="-0.4904"/>
            <vignetting model="pa" focal="100" aperture="16" distance="10" k1="-0.2705" k2="0.2094" k3="-0.1963"/>
            <vignetting model="pa" focal="100" aperture="16" distance="1000" k1="-0.2705" k2="0.2094" k3="-0.1963"/>
            <vignetting model="pa" focal="100" aperture="22" distance="10" k1="-0.1967" k2="-0.0747" k3="0.0577"/>
            <vignetting model="pa" focal="100" aperture="22" distance="1000" k1="-0.1967" k2="-0.0747" k3="0.0577"/>
            <vignetting model="pa" focal="133" aperture="5" distance="10" k1="-0.2493" k2="-0.1740" k3="0.1413"/>
            <vignetting model="pa" focal="133" aperture="5" distance="1000" k1="-0.2493" k2="-0.1740" k3="0.1413"/>
            <vignetting model="pa" focal="133" aperture="5.6" distance="10" k1="0.1594" k2="-0.9370" k3="0.5523"/>
            <vignetting model="pa" focal="133" aperture="5.6" distance="1000" k1="0.1594" k2="-0.9370" k3="0.5523"/>
            <vignetting model="pa" focal="133" aperture="8" distance="10" k1="-0.1259" k2="-0.1709" k3="0.0657"/>
            <vignetting model="pa" focal="133" aperture="8" distance="1000" k1="-0.1259" k2="-0.1709" k3="0.0657"/>
            <vignetting model="pa" focal="133" aperture="11" distance="10" k1="-0.2120" k2="0.1168" k3="-0.1105"/>
            <vignetting model="pa" focal="133" aperture="11" distance="1000" k1="-0.2120" k2="0.1168" k3="-0.1105"/>
            <vignetting model="pa" focal="133" aperture="16" distance="10" k1="-0.1581" k2="-0.0800" k3="0.0645"/>
            <vignetting model="pa" focal="133" aperture="16" distance="1000" k1="-0.1581" k2="-0.0800" k3="0.0645"/>
            <vignetting model="pa" focal="133" aperture="22" distance="10" k1="-0.1546" k2="-0.0866" k3="0.0686"/>
            <vignetting model="pa" focal="133" aperture="22" distance="1000" k1="-0.1546" k2="-0.0866" k3="0.0686"/>
            <vignetting model="pa" focal="198" aperture="5.6" distance="10" k1="-0.4008" k2="0.1768" k3="-0.0594"/>
            <vignetting model="pa" focal="198" aperture="5.6" distance="1000" k1="-0.4008" k2="0.1768" k3="-0.0594"/>
            <vignetting model="pa" focal="198" aperture="8" distance="10" k1="-0.0057" k2="-0.0261" k3="-0.1968"/>
            <vignetting model="pa" focal="198" aperture="8" distance="1000" k1="-0.0057" k2="-0.0261" k3="-0.1968"/>
            <vignetting model="pa" focal="198" aperture="11" distance="10" k1="-0.1546" k2="0.0500" k3="-0.0458"/>
            <vignetting model="pa" focal="198" aperture="11" distance="1000" k1="-0.1546" k2="0.0500" k3="-0.0458"/>
            <vignetting model="pa" focal="198" aperture="16" distance="10" k1="-0.1212" k2="-0.0623" k3="0.0511"/>
            <vignetting model="pa" focal="198" aperture="16" distance="1000" k1="-0.1212" k2="-0.0623" k3="0.0511"/>
            <vignetting model="pa" focal="198" aperture="22" distance="10" k1="-0.1163" k2="-0.0716" k3="0.0561"/>
            <vignetting model="pa" focal="198" aperture="22" distance="1000" k1="-0.1163" k2="-0.0716" k3="0.0561"/>
            <vignetting model="pa" focal="300" aperture="5.6" distance="10" k1="-0.5808" k2="0.5793" k3="-0.2978"/>
            <vignetting model="pa" focal="300" aperture="5.6" distance="1000" k1="-0.5808" k2="0.5793" k3="-0.2978"/>
            <vignetting model="pa" focal="300" aperture="8" distance="10" k1="0.0123" k2="-0.3562" k3="0.1329"/>
            <vignetting model="pa" focal="300" aperture="8" distance="1000" k1="0.0123" k2="-0.3562" k3="0.1329"/>
            <vignetting model="pa" focal="300" aperture="11" distance="10" k1="-0.0797" k2="0.0277" k3="-0.2201"/>
            <vignetting model="pa" focal="300" aperture="11" distance="1000" k1="-0.0797" k2="0.0277" k3="-0.2201"/>
            <vignetting model="pa" focal="300" aperture="16" distance="10" k1="-0.1622" k2="0.2277" k3="-0.2183"/>
            <vignetting model="pa" focal="300" aperture="16" distance="1000" k1="-0.1622" k2="0.2277" k3="-0.2183"/>
            <vignetting model="pa" focal="300" aperture="22" distance="10" k1="-0.0944" k2="-0.0292" k3="0.0198"/>
            <vignetting model="pa" focal="300" aperture="22" distance="1000" k1="-0.0944" k2="-0.0292" k3="0.0198"/>
            <vignetting model="pa" focal="400" aperture="5.6" distance="10" k1="-0.3322" k2="0.0654" k3="-0.0652"/>
            <vignetting model="pa" focal="400" aperture="5.6" distance="1000" k1="-0.3322" k2="0.0654" k3="-0.0652"/>
            <vignetting model="pa" focal="400" aperture="8" distance="10" k1="-0.4347" k2="0.2989" k3="-0.0712"/>
            <vignetting model="pa" focal="400" aperture="8" distance="1000" k1="-0.4347" k2="0.2989" k3="-0.0712"/>
            <vignetting model="pa" focal="400" aperture="11" distance="10" k1="0.2513" k2="-1.7000" k3="0.9763"/>
            <vignetting model="pa" focal="400" aperture="11" distance="1000" k1="0.2513" k2="-1.7000" k3="0.9763"/>
            <vignetting model="pa" focal="400" aperture="16" distance="10" k1="0.1836" k2="-0.7831" k3="0.1696"/>
            <vignetting model="pa" focal="400" aperture="16" distance="1000" k1="0.1836" k2="-0.7831" k3="0.1696"/>
            <vignetting model="pa" focal="400" aperture="22" distance="10" k1="-0.1409" k2="0.4461" k3="-0.6751"/>
            <vignetting model="pa" focal="400" aperture="22" distance="1000" k1="-0.1409" k2="0.4461" k3="-0.6751"/>
        </calibration>
    </lens>

</lensdatabase>
`

**Comment by Sturmflut** [comment]
I've linked a pull request that has the data.
