### ISSUE TITLE
RF 100-500 wrongly identified as RF 100-500 + RF2x

### ISSUE THREAD

**Issue by piratenpanda** [lensfun/lensfun#1548]
And I can't use .exiv2rc as all RF lenses share the same lens type number. Is there some change in exiv2 regarding RF lenses that hasn't made it into a release or is this a bug?

**Comment by piratenpanda** [comment]
ah most likely https://github.com/Exiv2/exiv2/pull/1729

**Comment by gnl21** [comment]
Is this still an issue or is it resolved now that the RF lens name changes have been merged?

**Comment by piratenpanda** [comment]
Has this been backported to stable releases already? Arch uses 0.27.5

**Comment by gnl21** [comment]
You mean the exiv2 change? I think that's in 0.27.5. That's the version that I've got from the darktable OBS build and it's working for me.

**Comment by piratenpanda** [comment]
The images still get incorrectly identified in darktable then it seems. Even if I reset metadata in darktable it's still the same. eviv2 -pv reports 
```
0xa434 Photo        LensModel                   Ascii      30  RF100-500mm F4.5-7.1 L IS USM
0x0095 Canon        LensModel                   Ascii     138  RF100-500mm F4.5-7.1 L IS USM
```
yet darktable thinks it's that + RF2x. I thought darktable just uses what exiv2 reports?

**Comment by gnl21** [comment]
Darktable stores the name that was queried from exiv in the database (or at least, it used to), so does it still do this with a newly imported image? I thought that darktable just used the exiv2 names as well.

**Comment by piratenpanda** [comment]
Yes it stores the value from reading. You can refresh this by going to the metadata tab in light table and press "refresh exif data". Doesn't change it here

**Comment by sarunasb** [comment]
darktable uses what Exiv2 reports to query Lensfun.
