### ISSUE TITLE
Only 7 calibrations open!  Some remarks

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#155]
@lensfun/calibrators In the future, I personally will handle all very old calibrations and anything exceeding 10 open calibrations.

Please mention the ticket number in the commit of the data.

Thank you so much for your work!

**Comment by junkyardsparkle** [comment]
Good way to start the year... I should be able to get to more calibrating in the near future, myself, [knock on wood](https://en.wikipedia.org/wiki/Knocking_on_wood).
