### ISSUE TITLE
"Samyang 16mm f/2.0 ED AS UMC CS": also available for <mount>Pentax KAF</mount>

### ISSUE THREAD

**Issue by misttsim** [lensfun/lensfun#1552]
Please add the 
_Pentax KAF_ mount 
to the lens section of the 
_Samyang 16mm f/2.0 ED AS UMC CS_
in slr-samyang.xml. Got it recently and I'm using darktable. Yes, I know, I can select some other camera, but it would be nice if the Camera/Lens combination Pentax KAF/Samyang 16mm would be recognized.
Thanks in advance,
 Michael

**Comment by Sturmflut** [comment]
Have you tested if doing so produces correct results? You can add the `<mount>Pentax KAF</mount>` tag in your local database to try it.

**Comment by misttsim** [comment]
On 08/01/2022 00:17, Sturmi wrote:
> Have you tested if doing so produces correct results? You can add the
> |<mount>Pentax KAF</mount>| tag in your local database to try it.
>

Hi, sure, already did that, works fine. Thanks for taking it up!
Best regards,
	Michael


--
Michael Staats
***@***.***

**Comment by Sturmflut** [comment]
The linked pull request has the change.
