### ISSUE TITLE
Add two camera and a lens

### ISSUE THREAD

**Issue by zakfm** [lensfun/lensfun#1579]
Hello,
Could you add the Nikon D500 and the AF-S Nikkor 200-500mm f5.6E ED VR. 
And also the Panasonic Lumix DMC FZ300.
Thank you.

**Comment by sarunasb** [comment]
Both cameras and the lens are already in the database.

**Comment by zakfm** [comment]
Perfect! I came to lensfun using Darktable. And I don't see them on https://lensfun.github.io/lenslist/.

**Comment by sarunasb** [comment]
That is unfortunately outdated.

**Comment by zakfm** [comment]
Here I am reassured on this side. Now I have to see with Darktable
![Darktable-Correction des objectifs](https://user-images.githubusercontent.com/97454437/149380457-81cf9fe0-3dd4-413e-ad8d-452a7643adcb.jpg)

**Comment by sarunasb** [comment]
Your local Lensfun DB needs to be updated. If using Linux, run
`lensfun-update-data`

**Comment by zakfm** [comment]
A big thank you!
At first install liblensfun-bin,
then lensfun-update-data
And now :
![lensfun-update-data](https://user-images.githubusercontent.com/97454437/149382374-0e925a19-a5c3-478d-9374-34d7d4980047.jpg)
