### ISSUE TITLE
Calibration data for Canon RF16mm F2.8 STM and Canon RF24-105mm F4-7.1 IS STM

### ISSUE THREAD

**Issue by BodoHobbit** [lensfun/lensfun#1584]
Please add the attached lens data to the lensfun data.
[lensfun.zip](https://github.com/lensfun/lensfun/files/7875674/lensfun.zip)

The lensfuns_calibration.tar.xz as generated by the lens_calibrate.py script is packed with zip and attached to this issue. It contains the calibration data (distprtion,tca and vignetting for two Canon RF lenses.

**Comment by PeterWem** [comment]
Added in PR https://github.com/lensfun/lensfun/pull/1505/commits/ab9a299d942a3c65c8931a391566d53909a93be5

**Comment by BodoHobbit** [comment]
@PeterWem Thanks! Is there anything I need to update in my uploaded data? Sorry for asking, but I am new to Github.

**Comment by PeterWem** [comment]
Not really, but if you want more exactly values of distortion correction, check here https://github.com/lensfun/lensfun/issues/1528

**Comment by BodoHobbit** [comment]
@Sturmflut Thank you for authoring the Canon RF 24-105mm F4-7,1 IS STM 2 days ago. After updating my lensfun database, I compared the values in the  release of "mil-canon.xml" with the values I have provided with this isssue. I just recognized that there are some fifference:

-  The distortion values for focal length 24mm are different
- My XML contains far more entries for vignetting - the official release somehow ends at focal length 70mm and apetrure 6.3, whereas I have provided vignetting data for all focal length and aperture values

Besides that, both files contain the smae values. Is there any reason fot this or did you take the values from other sources?

Moreover, I also provided the data for the Canon RF 16mm F2.8 STM as part of this issue. Could this also be added to the mil-canon.xml?

Thx

**Comment by PeterWem** [comment]
I have added above 70mm for 24-105 4-7.1 in this pull request and all the other RF lenses. https://github.com/lensfun/lensfun/pull/1603

Sturmflut changed 24 mm distortion. I hope it looks better. I don't own the lens so I can't check.

**Comment by tuxfanx** [comment]
RF24-105mm F4-7.1 IS STM data are meanwhile completely included in the db.
for RF16mm F2.8 STM the vignetting data are not yet included, only distortion and tca data.
I would like to update the missing data. I need a few raw images to be able to check how the data from this issue works. Unfortunately there are no more pictures on the upload server.

**Comment by BodoHobbit** [comment]
@Tuxfan I have only provided the calibartion data that I have generated locally (distortion, tca and vignetting) but never uploaded the raw images. I can still provide the raw images, but then I need an upload server as well as the creadentials. You just need the Raws for vignetting?

**Comment by tuxfanx** [comment]
Thanks for your answer!
You can [upload the pictures here](https://wilson.bronger.org/calibration). If you still have the pictures from the calibration, feel free to upload them there. Normal pictures taken with different apertures are also useful. It's just a matter of checking the effect of the calibration. Also for the RF24-105mm you are welcome to upload pictures for a comparison. You are also welcome to make your own comparisons of the different calibrations and suggest improvements.

**Comment by BodoHobbit** [comment]
Will do! Just allow for some time to generate some tar-files to pack the RAWs logically.

**Comment by BodoHobbit** [comment]
@tuxfanx Which format do you prefer? Canon CR3 or TIFF? Will use Darktable to convert to TIFF if needed.

**Comment by tuxfanx** [comment]
@BodoHobbit CR3 is ok, I'll convert it to DNG.

**Comment by BodoHobbit** [comment]
Got an Error message about Missing EXIF Data - can you please check

**Comment by tuxfanx** [comment]
> Got an Error message about Missing EXIF Data - can you please check
All arrived well, however I'm a little worried about the bright spots on the vignetting images, they look like reflections. I'll see if they have an effect.

**Comment by tuxfanx** [comment]
@BodoHobbit 
Thank's for the upload. Unfortunately, the vignetting correction is too strong. This affects shots with open apertures in particular, but it is still visible in shots with larger aperture values. Vignetting correction is difficult with wide-angle lenses.

![Screenshot_16mm_f28_not_corrected](https://user-images.githubusercontent.com/95431163/159984253-34479563-726b-4dfd-aa4d-ffe055f0ebf3.png)
![Screenshot_16mm_f28_corrected](https://user-images.githubusercontent.com/95431163/159984270-ae8ebb6d-7eb2-4487-9e83-51af00e2169e.png)

**Comment by BodoHobbit** [comment]
@tuxfanx Ok, anything I can do about this? Or does it mean, vignetting will not be added to DB? Whatever statement it is, it's fine for me. I just wanted to help and really appreciate the work everybody is contributing in  free time.

**Comment by tuxfanx** [comment]
I would add the vignetting correction to the db if it would work better. Uniform illumination with a good diffuser is important. The center of the image should be illuminated as brightly as possible (e.g. +2EV) but not overexposed (zebra mode). If nothing helps, you can try not to take the pictures at infinity but at close range. Vignetting is often strongest at infinity.
I'm sorry I can't take care of the calibration like this. Many thanks for your cooperation!
