### ISSUE TITLE
New Lens  Request - Sony FE 28-60mm F4-5.6

### ISSUE THREAD

**Issue by peterstevensau** [lensfun/lensfun#1599]
Hi

Could the new Sony FE 28-60mm F4-5.6 lens please be added to the development database.

https://www.sony.com.au/electronics/camera-lenses/sel2860

Thanks

**Comment by tuxfanx** [comment]
Have you already taken photos for the calibration?
If not, please see pages below:
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/
https://wilson.bronger.org/lens_calibration_tutorial/

**Comment by peterstevensau** [comment]
Unfortunately I’m not able to do a calibration for this lens, however it is the kit lens for all Sony A7C cameras, hopefully someone can contribute these results as it’s a fairly common lens

**Comment by sarunasb** [comment]
@peterstevensau You don't have to do calibration. Just take pictures suitable for calibration and upload them: https://wilson.bronger.org/calibration

**Comment by tuxfanx** [comment]
Hi sarunasb,
I offered my help for the calibration service to T. Bronger a few weeks ago but received no response. Is T. Bronger's email address still the right one for such requests or is there no need for further help? I would just like to know why I am not getting any response at all. Maybe you can enlighten me.

**Comment by sarunasb** [comment]
@tuxfanx You are getting response right now. To help with adding lens calibration data to Lensfun DB, you could take pictures suitable for calibration and upload them as explained here https://wilson.bronger.org/calibration.

**Comment by tuxfanx** [comment]
> You are getting response right now
...thank's, but already knew that. My question was about working on calibration requests as  explained here https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst

**Comment by sarunasb** [comment]
@tuxfanx Sorry for misunderstanding. Unfortunately I can't answer about Torsten, nor I have admin access to uploads service.

**Comment by Sturmflut** [comment]
AFAICT there are no images for this lens in the calibration uploads yet.

**Comment by piratenpanda** [comment]
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ I found this tutorial to work better as its not so outdated as Torsten's. Also creating a pull request by editing the files on github will make it much faster to get included and you'll learn during the process of calibrating yourself.

**Comment by piratenpanda** [comment]
Btw how do I contact @seebk I'd love to help as well

**Comment by tuxfanx** [comment]
Unfortunately no pictures up to now --> closed
