### ISSUE TITLE
Canon EF lens with <mount>Canon EF-S</mount> in slr-canon.xml

### ISSUE THREAD

**Issue by rebio** [lensfun/lensfun#1650]
While sorting the database (#1616, #1649) I saw two Canon EF lenses that are tagged with <mount>Canon EF-S</mount>.
I did not see that anywhere else, so I want to ask if this is correct.

**The lenses are:**
- Canon EF 24mm f/2.8 IS USM (line 6789 in slr-canon.xml)
- ~~Canon EF 70-300mm f/4-5.6 IS USM (line 3482 in slr-canon.xml)~~ The error was in the f/4-5.6 IS**L** variant
- Canon EF 70-300mm f/4-5.6L IS USM (line 5452 in slr-canon.xml)

I found two other lenses with the same issue:
- Canon EF 22-55mm f/4-5.6 USM (line 6854 in slr-canon.xml)
- EF35mm f/1.4L II USM (750) (line 2132 in slr-canon.xml)

https://lensfun.github.io/manual/v0.3.2/el_lens.html says "<mount>string</mount> Lens mount. There can be multiple <mount> entries if the same lens is manufactured with several mounts, or it has a variable mount (e.g. Tamron Adaptall)."

My guess for this one is that it's the mount the lens is build on (so EF for the examples) and not the it was tested on (eg. Canon EOS 100D with EF/EF-S mount)

**Comment by Sturmflut** [comment]
There is a variant of the 24mm f/2.8 for the EF-S mount, but it's called "EF-S 24mm f/2.8 STM" and not "EF 24mm f/2.8 IS USM". The 70-300mm f/4-5.6 does not exist for the EF-S mount.

So both entries should be marked as `<mount>Canon EF</mount>`, yes.

**Comment by rebio** [comment]
> So both entries should be marked as `<mount>Canon EF</mount>`, yes.

I found two more lenses with the same issue and updated the lenses in my fork. I can create a pull request, but there are also the add+remove edits from Canon lenses with empty calibration. Not sure how 'clean' this repo wants to be on this.
