### ISSUE TITLE
Objectif Nikkor 24-120F/4 (S)

### ISSUE THREAD

**Issue by cailles** [lensfun/lensfun#1725]
Bonjour,
J'utilise Darktable...
L'objectif Nikkor 24-120F/4 (S) pour les boîtier Z sortie en octobre 2021 n'est toujours pas dans la base, le sera-t-il bientôt ?
Merci !

Hello,
I use Darktable...
The Nikkor 24-120F/4 (S) lens for Z bodies released in October 2021 is still not in the base, will it be soon?
Thank you !

![Nikkor_24-120F4(S) ](https://user-images.githubusercontent.com/44798605/158143341-0cdf9614-b4c1-4e49-9dac-b950f462d046.png)

**Comment by tuxfanx** [comment]
That depends on yourself. 
You can upload the necessary images for a calibration [here](https://wilson.bronger.org/calibration), or do the calibration yourself and upload your correction data in an issue or generate a pull request. You can read everything you need to know [on this website](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/).
