### ISSUE TITLE
Variable in the wrong spot in mil-samyang.xml

### ISSUE THREAD

**Issue by rebio** [lensfun/lensfun#1800]
Origin: https://github.com/lensfun/lensfun/discussions/1799

The problem for RawTherapee is caused by the "Samyang 8mm f/2.8 UMC Fish-eye" lens by the `real-focal="8.405"` entry. If this is removed, RT works like expected.
As far as I have seen it, this variable is only grouped as such: ` <real-focal-length focal="90" real-focal="88.35" />`

Is this entry correct? Should it be there? (is the problem caused by RT or by the database?)

Please also drop a note here: https://github.com/Beep6581/RawTherapee/issues/6463

**Comment by tuxfanx** [comment]
please see[ here](https://lensfun.github.io/manual/latest/elem_calibration.html#real-focal) and [here](https://wilson.bronger.org/lensfun/elem_calibration.html). It depends on the database version being used.
