### ISSUE TITLE
Add 2 lines to mil-panasonic.xml to fix autodetection of Panasonic Lumix G Vario 14-140mm lens in darktable

### ISSUE THREAD

**Issue by eherle** [lensfun/lensfun#1801]
darktable was not able to autodetect my Panasonic Lumix G Vario 14-140mm lens in the lens correction module. I was able to fix this by adding line 1792 and 1883 to the attached mil-panasonic.xml file. I do not have a clue how to add these lines to the source file, I have no experience wiht Github. Can somebody take care of adding these two lines to mil-panasonic.xml, please?

[mil-panasonic.zip](https://github.com/lensfun/lensfun/files/8556844/mil-panasonic.zip)

**Comment by tuxfanx** [comment]
Could you please [upload a raw image here](https://wilson.bronger.org/calibration) for test purposes? A picture with any subject or with the lens cap on would do. Then please create a reference to the upload here.
