### ISSUE TITLE
Tamron SP AF 150-600mm versions

### ISSUE THREAD

**Issue by evanrabeck** [lensfun/lensfun#1802]
I'm an end-user so I'm not sure whose issue this is, but I suspect it's a data issue. I used to use the A011 and now use the A022 so I have files created with each. I dropped the current devel version of slr-tamron.xml into the configuration for ON1 Photo Raw on my Mac, replacing the version that they distributed because the releases don't have the A022 model yet. 

I was able to select either lens manually but the A022 would match as the A011 if I left it on automatic. The values the application gets in the EXIF for my raw files are:

Tamron SP AF 150-600mm f/5-6.3 VC USD (A011)
and 
Tamron SP 150-600mm F/5-6.3 Di VC USD G2

Locally I edited the lens entries to remove the secondary name for the A011 and added the name for the A022 which does not put the model number in the string (guessing Tamron decided to just move to generation numbers).

    <lens>
        <maker>Tamron</maker>
        <model>Tamron SP AF 150-600mm f/5-6.3 Di VC USD (A011)</model>
        

    <lens>
        <maker>Tamron</maker>
        <model>Tamron SP AF 150-600mm F/5-6.3 Di VC USD G2 (A022)</model>
        <model lang="en">Tamron SP 150-600mm F/5-6.3 Di VC USD G2</model>

**Comment by tuxfanx** [comment]
Could you please [upload one raw image taken with each lens here](https://wilson.bronger.org/calibration) for test purposes? A picture with any subject or with the lens cap on would do. Then please create a reference to the upload here.

**Comment by evanrabeck** [comment]
Uploaded images are in https://github.com/lensfun/lensfun/issues/1825

**Comment by tuxfanx** [comment]
Thank's for the pictures!
The lenses are 2 different optics. On my OS (Linux with darktable) the two lenses are automatically recognized correctly. A Canon image from the internet was also recognized correctly for the G2 (A022) lens.
However, for the G2 (A022) version there is only one profile with a cop factor of 1 in the db, which would probably not lead to a sufficiently good correction for APS-C images. So there is actually no APS-C profile for the G2 (A022) lens in the db. At the moment I don't see any reason to change the existing profiles in the db.
If you want, you can provide us with pictures for creating an APS-C profile. [Here is a description](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) of how the pictures have to be taken.
