### ISSUE TITLE
AppVeyor takes too long time and fails

### ISSUE THREAD

**Issue by payano** [lensfun/lensfun#1805]
Maybe we should remove appveyor as a build system and run githubs windows container instead.

What do you think, should I investigate this further?

**Comment by eherle** [comment]
Yes, please, it seems to be blocking the resolution of #1801. And probably other issues as well.

**Comment by tuxfanx** [comment]
I'm neither a programmer nor do I know the internals of Github very well. So the technical background of your proposal must be evaluated by others, but as a user and calibrator of the project, I welcome your proposal. The unnecessary error messages irritated me at first and other newcomers will probably feel the same way.

**Comment by payano** [comment]
I'll try to come up with some solution. I don't think it would be necessary to compile the windows version against that many targets. I don't know what we want to achieve by doing that?
I will use: 
"Visual Studio 17 2022" 
And run on latest windows version.
If you want more build targets, please let me know :)

**Comment by payano** [comment]
By the way, we are only building against ubuntu-latest and default settings for Linux.

**Comment by payano** [comment]
PR: #1809
