### ISSUE TITLE
Add Lumix G X Vario 12-35mm f/2.8 Asph. Power OIS II (duplicate it from first version)

### ISSUE THREAD

**Issue by dmoltisanti** [lensfun/lensfun#1807]
Hi all,

the Panasonic lens `Lumix G X Vario 12-35mm f/2.8 Asph. Power OIS II` is not in lensfun's database. However, it is optically identical (as far as I know, at least) to its previous version, which is in the database.

What I did to fix this is to just duplicate the entry in the `mil-panasonic.xml` file

```xml
<lens>
        <maker>Panasonic</maker>
        <model>Lumix G X Vario 12-35mm f/2.8 Asph. Power OIS</model>
        <model lang="en">Lumix G X Vario 12-35mm f/2.8</model>
...
</lens>
```

to

```xml
<lens>
        <maker>Panasonic</maker>
        <model>Lumix G X Vario 12-35mm f/2.8 Asph. Power OIS II</model>
        <model lang="en">Lumix G X Vario 12-35mm f/2.8 II</model>
...
</lens>
```
This work flawlessly in Darktable which recognises the lens and applies the right lens corrections. 

I noticed a similar hack was recently done for the lens `LUMIX G VARIO 35-100/F2.8II`. I used to duplicate this too in my local copy of lensfun, but after updating to Darktable 3.8.1 (sorry I don't know how to tell which version of lensfun it uses) I noticed the 35-100 2.8 II was already there:

```xml
<lens>
        <maker>Panasonic</maker>
        <model>LUMIX G VARIO 35-100/F2.8II</model>
        <!-- same optic as LUMIX G VARIO 35-100/F2.8 -->
        <model lang="en">LUMIX G X VARIO 35-100 mm f/2.8 II POWER OIS</model>
```

Thanks in advance for your help and your great work!

**Comment by tuxfanx** [comment]
Could you please [upload a raw image here](https://wilson.bronger.org/calibration) for test purposes? A picture with any subject or with the lens cap on would do. Then please create a reference to the upload here.

**Comment by dmoltisanti** [comment]
Sure thing, here it is: https://github.com/lensfun/lensfun/issues/1813

Thanks!
