### ISSUE TITLE
Incorrect crop factor for Canon Powershot G1X Mark III

### ISSUE THREAD

**Issue by weltyj** [lensfun/lensfun#1810]
Currently in the database, the crop factor listed for the G1X mark iii is 1.608

The sensor size is 22.3 x 14.9 mm, with a diagonal of 26.82, which gives a crop factor of 1.613

This makes a quite noticeable difference if images are being exported for creation of panoramas.

I have independently checked the distortion parameters in lensfun for the 15mm focal length, and they look correct if the cropfactor is simply changed to 1.613

I can give more details if needed.

Cheers,
Jeff Welty

**Comment by sarunasb** [comment]
Can you verify corrections at other focal lengths, TCA and vignetting with 1.613?

**Comment by weltyj** [comment]
I don't have the images at the moment to do that, the only other sets I have are at 22mm, which isn't an exact match for the current focal lengths in lensfun.   The images I have weren't taken for calibration, they were taken for normal panoramas.  I got curious though when the darktable distortion correction looked noticeably off when I loaded images into hugin.   So I refit the distortion in hugin (with an excellent fit,  hundreds of control points, worst error < 1 pixel).   I was using a 15mm FL and a cropfactor of 1.613 in hugin, and when I looked back at the lensfun xml file, I noticed the difference in the cropfactor.  I then compared the distortion equation using the parameters from lensfun, vs the parameters from the hugin optimization, and the results were virtually the same.

I just looked and have some other panoramas at 45mm, which is a match for what's in lensfun.   I'll take a look at those and report back what I find for distortion.
---

For TCA, darktable 3.8 has a feature to override TCA correction parameters.   My images are mountains with snow and dark trees, so I can easily see when the TCA parameters are correct as I adjust them.  I'll go back and look at those with the 1.608 crop factor as well as the 1.613 cropfactor.  And I'll check the vignetting parameters too.

**Comment by sarunasb** [comment]
OK, thank you. I don't mean a full check, just a bit more refrence points, to make sure correction params still work with the changed crop factor. And yes, 1.613 seems to be correct for G1 X MkIII.

**Comment by weltyj** [comment]
From the samples I have (15 and 45mm), everything looks good at a CF of 1.613, except for TCA @ 15mm, which I didn't look good at CF of 1.608 either (but it did improve the TCA compared to no correction).   Is it possible I could get access to the calibration image(s) used for 15mm that are in lensfun?  If I could compare an "original" 15mm image with the parameters I found best with my image, it'd be helpful to understand if there is something different between the orginal image vs the image I used for TCA.

There were are no vignetting parameters in the xml file for the G1 X MkIII

Jeff

**Comment by sarunasb** [comment]
There don't seem to be original images in calibration uploads anymore. There are G1X MkIII images in upload 9da84a #533. They are suitable for checking distortion parameters. Distortion correction looks good with crop factor changed to 1.613.

**Comment by sarunasb** [comment]
Commit [3a5b58c](https://github.com/lensfun/lensfun/commit/3a5b58c0473682f72158b6238e5e370bb16a0cb7).

**Comment by weltyj** [comment]
Distortion looks good now.   I suspect that TCA may need more than one parameter based on my limited data from my copy of this camera.   To refine TCA will take a lot more time and images, if I come up with a better fit I will let you know.

Thank you!
Jeff Welty

**Comment by sarunasb** [comment]
@weltyj Thank you. If you make a set of images suitable for TCA and/or vignetting measurement, please upload them at https://wilson.bronger.org/calibration, which will create a new issue.
