### ISSUE TITLE
LUMIX G VARIO 45-200/F4.0-5.6II

### ISSUE THREAD

**Issue by ckchow** [lensfun/lensfun#1835]
The lens mentioned in the title is a mkII version of the original lens (sans the II at the end), and I think it has the same optics as the mkI version. (At least per this article: https://camerastuffreview.com/en/review-panasonic-45-200mm-ii/). 

Could one of the maintainers duplicate the calibration for the mkI for the mkII lens?

**Comment by sarunasb** [comment]
Please show the output of:
```exiv2 -pt <image> | grep -i lens```

Or please supply an image sample, preferably RAW.

**Comment by ckchow** [comment]
`exiv2 -pt ./20220530_0088.ORF | grep -i lens`

```
Exif.OlympusEq.LensType                      Byte        6  2 0 49 16 0 16
Exif.OlympusEq.LensSerialNumber              Ascii      32  21060400313
Exif.OlympusEq.LensModel                     Ascii      32  LUMIX G VARIO 45-200/F4.0-5.6II
Exif.OlympusEq.LensFirmwareVersion           Long        1  4608
Exif.OlympusEq.LensProperties                Short       1  49472
Exif.OlympusEq.ConversionLens                Ascii      32
Exif.Photo.LensSpecification                 Rational    4  45/1 200/1 40/10 56/10
Exif.Photo.LensModel                         Ascii      32  LUMIX G VARIO 45-200/F4.0-5.6II
```

**Comment by sarunasb** [comment]
Commit [ce361a7](https://github.com/lensfun/lensfun/commit/ce361a7406e709d802bd93c584717b30fc335557)
