### ISSUE TITLE
Calibration data for SIGMA 56mm F1.4 DC DN | Contemporary 018 (Fuji mount)

### ISSUE THREAD

**Issue by cschreib** [lensfun/lensfun#1846]
Please add the attached lens data to the lensfun data base.
[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/8985539/lensfun_calibration.zip)

**Comment by cschreib** [comment]
I think the distortion correction isn't right, I'll try to create a better version.

**Comment by tuxfanx** [comment]
It seems to me that correction data for the lens are already [included in the database](https://github.com/lensfun/lensfun/blob/master/data/db/mil-sigma.xml) (line 97). Do you need to update your database?

**Comment by cschreib** [comment]
I had tried that indeed. If use `lensfun-update-data` to pull the latest data (I checked the lines you refer to are included in the data I get), then Darktable reports "camera/lens not found". The name of the lens I get in my picture's EXIF is `SIGMA 56mm F1.4 DC DN | Contemporary 018`, which doesn't seem to match any of the two names listed in the database:
 - `56mm F1.4 DC DN | Contemporary 018`
 - `Sigma 56 mm F1.4 DC DN | C 018`

If I then manually select the lens, the correction that is applied is not perfect. You can compare, for example by looking at the top-most or bottom-most horizontal lines (the picture was taken with a slight tilt) in the images below. The entry in the current database was apparently calibrated on a Sony camera; it is possible that the lens with Fuji mount does not have exactly the same optical property?

**Included in the database:**
![DSCF8578](https://user-images.githubusercontent.com/2236577/179053536-6f9adb77-fbea-4540-b0e3-cb81e7f0b4f7.jpg)

**My custom calibration:**
![DSCF8578_01](https://user-images.githubusercontent.com/2236577/179053740-36f83941-a023-425d-9054-362abe6b244d.jpg)

**Comment by tuxfanx** [comment]
You're right, the distortion correction values in the db do not seem to work sufficiently on your images. From what distance did you take the photos?
I found some [raw lens photos online](https://www.dpreview.com/sample-galleries) that were taken with a Sony camera. If the model name would be changed to "<model>Sigma 56mm F1.4 DC DN | Contemporary 018</model>", the automatic lens detection would work for both, the Sony images and the Fuji images.
It would be helpful if you could upload your raw images that you used for calibration [here](https://wilson.bronger.org/calibration).

**Comment by cschreib** [comment]
FYI the upload of the RAWs was rejected because the vignetting correction images (which I attached for completeness) were taken with a Fuji X-M1, while the rest was taken with an X-T20. Are you able to access the uploaded data, or should I try to send a new package with just the distortion data?

**Comment by sarunasb** [comment]
To improve already existing distortion data, one would need the best possible calibration images. 
https://wilson.bronger.org/lens_calibration_tutorial/
For distortion: trustworthy straight lines, one of them very close to the long edge of the frame. Extending through entire frame width. An object like contemporary building, so from good distance.

I can't identify your upload among automatically created issues. But perhaps it shouldn't be there, if it was rejected...

**Comment by tuxfanx** [comment]
Unfortunately I could not find the pictures on the server. Please only send the images from the distortion calibration again.
While searching I found a picture that was taken with a Sony APS-C camera and the Sigma lens. The distortion on this picture is corrected a little better, compared to the red lines, with the DB values.

without correction:
![Sigma 56mm F1 4 DC DN | C--056mm--5 6_DSC02710](https://user-images.githubusercontent.com/95431163/179372567-29b00caf-09db-421c-9839-71e9f56a6417.jpg)

correction with db values:
![Sigma 56mm F1 4 DC DN | C_database](https://user-images.githubusercontent.com/95431163/179372039-14c9c099-9148-4008-847f-0437aaf4ec39.jpg)

correction with cschreib values:
![Sigma 56mm F1 4 DC DN | C_c_schreib](https://user-images.githubusercontent.com/95431163/179372193-131cb153-3a25-43a0-bdca-6f36c8b581b2.jpg)

**Comment by cschreib** [comment]
I have re-uploaded the images I used: https://github.com/lensfun/lensfun/issues/1856.
You are definitely right that the DB values work better with the picture from the Sony camera. I suspect it might come down to the lens being slightly different on Sony vs Fuji? Is that a thing?

**Comment by cschreib** [comment]
I think I take it back. Seeing the main difference happens at the top of the frame in your samples above, I tried to replicate that with the straightest line I had nearby, and was able to reproduce the trend from your pictures. So it would appear that the correction in the DB is actually the best, and better than the builtin correction applied to the camera JPEG! Test shots below.

I am not sure why my initial test showed otherwise; perhaps it was taken too close. But I think now it is just a matter of fixing the lens model name, so the lens can be recognized automatically.

Correction using current DB:
![lines_DSCF8699_db](https://user-images.githubusercontent.com/2236577/179393562-e8f0e8c5-540d-4537-9a0a-ed435afa39f9.jpg)

Correction using my values:
![lines_DSCF8699_cschreib](https://user-images.githubusercontent.com/2236577/179393576-c5796634-5925-48c8-8523-255d8fe414eb.jpg)

Camera JPEG correction:
![lines_DSCF8699_camera](https://user-images.githubusercontent.com/2236577/179393599-5951a3fb-6c8d-4dc0-bdf4-f25b7e9cc835.JPG)

**Comment by tuxfanx** [comment]
Ok, let's leave the correction values in the DB unchanged. I will do a PR for the model name change.
[See this discussion](https://github.com/lensfun/lensfun/discussions/1640) for more info.
