### ISSUE TITLE
"ILCE-7RM4A" with "FE 24-105mm f/4 G OSS" not identified properly

### ISSUE THREAD

**Issue by Kinzis85** [lensfun/lensfun#1849]
Since I changed my camara body from Sony "ILCE-7" to "ILCE-7RM4A", the "FE 24-105mm f/4 G OSS" is not identified properly in Darktable. The the lens is found, the camara not. I always must manual select the Sony Alpha 7R IV (=ILCE-7RM4) and the "FE 24-105mm f/4 G OSS".
The "ILCE-7RM4**A**" is the replacement for the ILCE-7RM4 with another Display.

**Comment by sarunasb** [comment]
Please upload RAW from your ILCE-7RM4A to somewhere and post the link to it here.

**Comment by Kinzis85** [comment]
https://drive.google.com/file/d/1yUlSyEEuLfL73OO2uvqP5xDmcPFGRTUc/view?usp=sharing

**Comment by sarunasb** [comment]
Thank you @Kinzis85. New camera added to Lensfun DB ([c7ca3c9](https://github.com/lensfun/lensfun/commit/c7ca3c96a8c727b7762578b619e2b0f1a2924ba8)).
