### ISSUE TITLE
Lens Support Request: Compact Sony ZV-1's fixed zoom lens f1.8-2.8 24-70mm

### ISSUE THREAD

**Issue by prg318** [lensfun/lensfun#1869]
Hello,

I don't see support for the ZV-1's lens in the lensfun database, so I wanted to open an issue to track potential progress.  Although marketed as a zlogging camera, the ZV-1 is a surprisingly capable evf-less stills camera and it would be great to be able to lens correct the RAW files from this camera with software that uses lensfun.

I'm not yet ready to contribute calibrations, but have read about the process and may give it an attempt in the future.

If there's any helpful information I can provide in the meantime, please let me know.

**Comment by tuxfanx** [comment]
You don't have to do the calibration yourself. You can [upload the necessary raw images for the calibration here](https://wilson.bronger.org/calibration).  Then someone else can do the calibration.
Please read [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and [here](https://wilson.bronger.org/calibration) (section "How should test shots look like?") how the pictures have to be taken.
