### ISSUE TITLE
OwnCloud server will not be updated temporarily

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#1873]
The OwnCloud server for sharing RAW images for calibrations will not be updated for a couple of days. The website for uploading calibration images will be offline during the same period of time.

I move to another location and thus my private server has a downtime. When the server is up and running again in the new apartment, I close this ticket.

**Comment by ptilopteri** [comment]
tks for the info and your efforts.  much appreciated.

**Comment by bronger** [comment]
The service is running again.
