### ISSUE TITLE
Sigma 70-200 mm F2.8 missing on Pentax mount

### ISSUE THREAD

**Issue by PaoloAst** [lensfun/lensfun#1881]
I'm using Darktable for raw developing and I've noticed that the Sigma 70-200m F2.8 isn't included in the supported lens list.

Looking at the database file, I've tried to insert the Pentax KAF2 in the allowed mounts for this lens and it apparently works.

**Comment by tuxfanx** [comment]
Several Sigma lenses with 70-200mm f/2.8 are listed in the[ lens list](https://wilson.bronger.org/lensfun_coverage.html). Please state the complete model name and the crop factor.

**Comment by PaoloAst** [comment]
Hi Joachim,

I'm using "Sigma 70-200mm F2.8 APO EX DG OS HSM" on a Pentax K-3 II and 
on a Pentax K-5. I suppose the crop factor could be 1.534
In lens list I've found the "Sigma 70-200mm f/2.8 EX DG OS HSM 1.534", 
but Pentax mount is not allowed. I've tried to modify the file and 
_bingo!_ it seems work

Il 21/08/2022 23:19, Joachim Daehnke ha scritto:

**Comment by tuxfanx** [comment]
Thanks Paolo, I am going to create a PR.
