### ISSUE TITLE
Really Need  Panasonic LUMIX S 24-105mm F/4 Macro OIS Lens Correction

### ISSUE THREAD

**Issue by BernardoSliva** [lensfun/lensfun#1884]
I really hope Affinity Photo supports the lens  correction for this Panasonic 24-105mm, or is it actually supported and I just couldn't find it? Can the staff or other guy answer it?

**Comment by tuxfanx** [comment]
The lens is not yet included in lensfuns database as you can see [here](https://wilson.bronger.org/lensfun_coverage.html) and [here](https://github.com/lensfun/lensfun/blob/master/data/db/mil-panasonic.xml).
To generate the correction data, we need raw pictures that can be uploaded [here](https://wilson.bronger.org/calibration).
[Here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) in section _"Taking pictures"_ and [here](https://wilson.bronger.org/calibration) in section _"How should test shots look like?"_ it is described how the pictures have to be taken.

**Comment by tuxfanx** [comment]
answered and no reaction --> closed
