### ISSUE TITLE
Lens correction not applied correctly for mobile phone ultra wide lens

### ISSUE THREAD

**Issue by lintujuh** [lensfun/lensfun#1887]
**Describe the bug/issue**
I have created distortion correction data for OnePlus 10 Pro mobile phone's cameras. For the ultra wide lens, the correction parameters provide different results in Hugin than it does in darktable.

**To Reproduce**
1. Create the distortion correction parameters as instructed for lensfun db for OnePlus 10 Pro ultra wide lens
2. Verify the parameters in Hugin
![image](https://user-images.githubusercontent.com/5797282/188008943-bb242f73-e851-4361-8357-4d800960c447.png)
3. Create an .xml-file for the lens (with correct focal length 2.3mm)
4. Start darktable and apply the lens correction
![image](https://user-images.githubusercontent.com/5797282/188008623-9bb35161-66f5-4b79-9c28-b3ae9549a9d1.png)
5. Edit the lensfun .xml file for the camera, and change the focal length to 2.1mm (this value slightly over corrects, but shows the issue)
![image](https://user-images.githubusercontent.com/5797282/188011073-404e1eef-4b42-4fe6-9bc1-d35ab541943b.png)

**Expected behavior**
The correct focal length could be used in the lensfun database.

**Platform**
* darktable version : 4.0.0
* OS                :  Windows 10
* OpenCL installed  :  yes
* OpenCL activated  : both active and inactive

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version 4.1.0**
 - lensfun defintions [oneplus.txt](https://github.com/darktable-org/darktable/files/9473432/oneplus.txt)
 - see also the discussion in [Pixls.us](https://discuss.pixls.us/t/how-to-enable-dt-recognize-the-correct-smartphone-lens/32168)
 - issue first reported in [darktable github
](https://github.com/darktable-org/darktable/issues/12423)

**Comment by tuxfanx** [comment]
Did you follow the instructions for distortion calibration as described [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/), [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://www.youtube.com/watch?v=ci0BY9Bljzk)?
Do your pictures for calibration meet the requirements described there?

**Comment by lintujuh** [comment]
I followed the instructions in the first link.

The image in the bug report is the image I used for calibration. It is not perfect, I'm planning to take a better image, when I master the process better.

Attached is the TIFF and the Hugin file I have created.
[IMG20220816123041.zip](https://github.com/lensfun/lensfun/files/9485045/IMG20220816123041.zip)

**Comment by tuxfanx** [comment]
Ok!
You should also add "<aspect-ratio>4:3</aspect-ratio>" to your calibration file.

**Comment by lintujuh** [comment]
Thank you @tuxfanx ! That was the issue.
