### ISSUE TITLE
Canon R10 not recognized in lens correction module (DT 4.0.1) (windows10)

### ISSUE THREAD

**Issue by CptPotassium** [lensfun/lensfun#1904]
- I posted this message in the darktable hub, and was told this would be relevant here:

(Apologies in advance if this is a known/being worked on issue, I did some scouting but couldn't find a clear answer)
I just got a brand new canon R10, unfortunately the lens correction module is not detecting it. I was previously running DT 4.0.0, and updated it to be able to use it with the new camera, I've read that the latest version supports it, so that's why I suspect it might be an issue with my system(?

I have tried a variety of lenses
I have tried using both RAW and cRAW formats.
I am willing to provide any files or info you might need, given enough patience since I'm not too tech savvy.

![darktable_9TulBrVPfT](https://user-images.githubusercontent.com/114697484/193142380-c7c35dde-36aa-4935-abac-3cc4fb3e3370.png)

Thank you to all the devs working on this project :)

**Comment by sarunasb** [comment]
Please give a link to a RAW file.

**Comment by CptPotassium** [comment]
> Please give a link to a RAW file.

File is 25.8mb when zipped
[IMG_0139.zip](https://github.com/lensfun/lensfun/files/9679185/IMG_0139.zip)

For now here's a CRAW image

**Comment by CptPotassium** [comment]
> Please give a link to a RAW file.

https://drive.google.com/file/d/1rywSQ8UMqYisW15zu4QnG9kyjJVmxGbG/view?usp=sharing

RAW file, properly exposed, not sure if that's relevant right now :)

**Comment by sarunasb** [comment]
Thank you for providing RAW files. Canon EOS R10 camera added to Lensfun database,  commit [44d268e](https://github.com/lensfun/lensfun/commit/44d268ecabefbece63691aeedbd774c1434acf4e).

**Comment by CptPotassium** [comment]
Pasted the new lines to darktable\share\lensfun\version_1\mil-canon, which solved the issue. thank you very much!

**Comment by kmilos** [comment]
You might as well add the R7 (also APS-C) in the same fashion, as well as the R3 (FF).

**Comment by sarunasb** [comment]
R# and R7 added by 9f02a74.
