### ISSUE TITLE
Lensfun doesn't find a previous found camera

### ISSUE THREAD

**Issue by SchoenerWolf** [lensfun/lensfun#1905]
Hi,

I  have Darktable 4.01 on Mint 20.3 una. In lens correction a D750 is not found although in prior version it was possible.

GIMP-Lensfun is installed and .local/share doesn't display lensfun.  The command lensfun-update-data is not available and not found in the repositories.

**Comment by tuxfanx** [comment]
The Nikon D750 is included in the current databases and can also be found under Darktable 4. You probably reinstalled some things and an outdated database was installed.
lensfun-update-data belongs to the liblensfun-bin package. Once the package has been installed, you should find lensfun-update-data in /usr/bin/
In a new installation, the installed database is either under /var/lib/... or under /usr/share/... If the lensfun database is installed there, lensfun-update-data must be run with root rights for an update, e.g. sudo /usr/bin/lenfun-update-data.

**Comment by SchoenerWolf** [comment]
Hi tuxfanx,
the Database is in _/usr/share_. _which lensfun-update-data_ displays nothing; even _find . -iname lensfun*_ too.

I'm perplexed. How to fix this?

**Comment by SchoenerWolf** [comment]
Soory, I found it:

Install liblensfun-bin

Installing liblensfun-bin package on Ubuntu is as easy as running the following command on terminal:

sudo apt-get update
sudo apt-get install liblensfun-bin
