### ISSUE TITLE
Neither Update URL works anymore...

### ISSUE THREAD

**Issue by butcherg** [lensfun/lensfun#1923]
Reference the two read_locations this line:

https://github.com/lensfun/lensfun/blob/master/apps/lensfun-update-data#L135

**Comment by Halogenek** [comment]
Yep. Both services are down.
Can we do something to make the database more reliable? I could try and help.

**Comment by sarunasb** [comment]
https://lensfun.sourceforge.net/db/ worked when I tried.

**Comment by butcherg** [comment]
Ah, my code was still using http instead of https, which works for lensfun.sourceforge.net.  wilson.bronger.org still refuses connection.

**Comment by sarunasb** [comment]
It might make sense to host version_x.tar.bz2 on https://github.com/lensfun/lensfun. Not sure where the scripts that send database updates to SF and wilson are. Don't see them among Github actions.

**Comment by tuxfanx** [comment]
https://wilson.bronger.org is online again

**Comment by bronger** [comment]
My private server wilson.bronger.org was down due to a mismanaged SSD failure, however, I still have issues updating the Sourceforge location. See https://sourceforge.net/p/forge/site-support/23980/ for the issue report at SF.

**Comment by bronger** [comment]
The SourceForge issue is fixed.
