### ISSUE TITLE
Should I upload data for obscure lenses?

### ISSUE THREAD

**Issue by Faandyy** [lensfun/lensfun#1934]
I own quite a few less common lenses from the film era, I wonder if you (the people who work on the database) would appreciate if I uploaded data regarding some of those. I personally use them so being able to correct them would benefit me, but I don't want to be selfish.
From the more common ones I would like to eventually do the Macro Takumars, the 100/4 and 50/4 versions. I think that could help some people using these as cheap macro lenses to get more clinically accurate images. But I have some pretty obscure lenses like the Volna 9 or Porst 35mm WW f/1.8. Wondering if I should eventually do those too.
Thanks.

**Comment by tuxfanx** [comment]
Personally, I usually only profile lenses that I expect will be used by many photographers. Very few people currently do this work for the lensfun database in their free time.
It would be much better if you did the calibration of such rarely used lenses yourself and then made your results available to the lensfun project.
Of course you can still provide us with the pictures, but the probability of receiving a profile in the near future is rather small.

**Comment by Faandyy** [comment]
> Personally, I usually only profile lenses that I expect will be used by many photographers. Very few people currently do this work for the lensfun database in their free time. It would be much better if you did the calibration of such rarely used lenses yourself and then made your results available to the lensfun project. Of course you can still provide us with the pictures, but the probability of receiving a profile in the near future is rather small.

Ok, will do, thank you.

**Comment by tuxfanx** [comment]
answered --> closed
