### ISSUE TITLE
Olympus 12-45mm f/4 Pro lens

### ISSUE THREAD

**Issue by UraniumLollipop** [lensfun/lensfun#1941]
Hi!
Can you add lens calibration profile for this lens?
Thank you!

**Comment by sarunasb** [comment]
Distortion, TCA and vignetting corrections are already in Lensfun for Olympus M.Zuiko ED 12-45mm f/4.0 Pro.

You may need to update your local Lensfun, XML database part and for this particular lens — data/db/mil-olympus.xml file. You can download it from Github or, on Linux systems, use `lensfun-update-data` command.

**Comment by UraniumLollipop** [comment]
Thank you!
