### ISSUE TITLE
Sigma 24mm f/1.4 DG HSM [A] not recognized by darktable

### ISSUE THREAD

**Issue by redglobuli** [lensfun/lensfun#1946]
lensfun db has

<model>Sigma 24mm f/1.4 DG HSM [A]</model>

exiv2 shows on the Canon EOS 6D:

Exif.Canon.LensModel                         Ascii      74  24mm F1.4 DG HSM | Art 015
Exif.Photo.LensModel                         Ascii      27  24mm F1.4 DG HSM | Art 015

**Comment by redglobuli** [comment]
thanks for your hint, didn't know that. But i don't have a LensId number:

exiv2 -pv --grep lens/i IMG_4985.JPG

0x0016 CanonCs      LensType                    Short       1  368
0x0017 CanonCs      Lens                        Short       3  24 24 1
0x0095 Canon        LensModel                   Ascii      74  24mm F1.4 DG HSM | Art 015
0xa432 Photo        LensSpecification           Rational    4  24/1 24/1 0/1 0/1
0xa434 Photo        LensModel                   Ascii      27  24mm F1.4 DG HSM | Art 015
0xa435 Photo        LensSerialNumber            Ascii      11  0000000000

**Comment by sarunasb** [comment]
Different cameras' firmwares may represent the same lens differently… Calibration for this lens was done using samples from Nikon camera.

What if you replace

```<model>Sigma 24mm f/1.4 DG HSM [A]</model>```

with

```
<model>Sigma 24mm f/1.4 DG HSM | [A] Art 015</model>
<model lang="en">Sigma 24mm f/1.4 DG HSM | A</model>
```

?

**Comment by redglobuli** [comment]
this works:

        <model>Sigma 24mm f/1.4 DG HSM [A]</model>
        <model lang="en"> Sigma 24mm F1.4 DG HSM | Art 015</model>
