### ISSUE TITLE
Calibration data for the Canon RF-S 18-150mm f/3.5-6.3 IS STM

### ISSUE THREAD

**Issue by mdjnewman** [lensfun/lensfun#1950]
Please add the attached lens data to the Lensfun database.

I believe this is the first RF-S submission, let me know if I did anything incorrectly.

Contains distortion corrections only.

Created from original photos following steps at https://wilson.bronger.org/lens_calibration_tutorial/.

[lensfun.xml.zip](https://github.com/lensfun/lensfun/files/10264226/lensfun.xml.zip)

**Comment by tuxfanx** [comment]
Would it be possible for you to provide us with some pictures for testing? I couldn't find any pictures on the internet.
[Here you could upload the pictures](https://wilson.bronger.org/calibration).

**Comment by mdjnewman** [comment]
I went out to take some more test photos, and realised that I've done something wrong in the calibration - this set looks pretty terrible in Darktable 😂

I'll close this for now until I head into the city and can get a better range of training and test photos, then upload the photos and the new `lensfun.xml`.

Sorry for the noise, and I appreciate the rigour!

**Comment by mdjnewman** [comment]
Okay, I've taken a few new images and redone the distortion calibration:

```
    <lens>
        <maker>Canon</maker>
        <model>Canon RF-S 18-150mm F3.5-6.3 IS STM</model>
        <mount>Canon RF</mount>
        <cropfactor>1.6132</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="18" a="0.02183" b="-0.06929" c="0.02884"/>
            <distortion model="ptlens" focal="30" a="0.00895" b="-0.01157" c="0.003"/>
            <distortion model="ptlens" focal="43" a="0.00435" b="0.00077" c="-0.00205"/>
            <distortion model="ptlens" focal="62" a="0.00475" b="-0.01177" c="0.02703"/>
            <distortion model="ptlens" focal="100" a="0.00621" b="-0.01709" c="0.03355"/>
            <distortion model="ptlens" focal="135" a="0.00646" b="-0.03293" c="0.07117"/>
            <distortion model="ptlens" focal="150" a="0.00185" b="-0.00696" c="0.02205"/>
        </calibration>
    </lens>
```

I've uploaded all the images I think would be useful to test with, but received an error - https://wilson.bronger.org/calibration/results/6face5_mdjnewman. I'm not sure if they're usable to you given this error, let me know if I should share them some other way.

Happy holidays!

**Comment by tuxfanx** [comment]
In the meantime, someone else has already provided pictures for the lens and I added a profile to the database yesterday. In the 18-24mm focal length range, the distortion changes from barrel to pincushion. Unfortunately, the lens does not provide any other focal length values between 18-24mm. This leads to incorrect corrections with some settings in this area. In darktable it is possible to correct this manually. 
In addition, the ptlens model for some superzoom lenses does not always produce good corrections over the entire image area.
Attached you will find my correction profile for comparison.

[lensfun.zip](https://github.com/lensfun/lensfun/files/10319620/lensfun.zip)

**Comment by mdjnewman** [comment]
Ah interesting, that's good to know. Thanks for the info - all this is quite new to me!

I compared the two profiles and yours does a better job for sure 👍
