### ISSUE TITLE
Calibration data for Fujifilm 18-55 2.8/4 R LM OIS (vignetting)

### ISSUE THREAD

**Issue by J-F-M** [lensfun/lensfun#1952]
The lens is already in the database, I’ve just added the vignetting calibration. The complete data (XML) for that lens is attached.
Unfortunately I deleted the calibration files before running the ship script, hopefully you can simply sanity-check the XML data.

[fujifilm_x_1855_284_l_rm_ois.zip](https://github.com/lensfun/lensfun/files/10295381/fujifilm_x_1855_284_l_rm_ois.zip)

**Comment by tuxfanx** [comment]
Vignetting correction for this lens is already included in the current database. See [here](https://wilson.bronger.org/lensfun_coverage.html) and [here](https://github.com/lensfun/lensfun/blob/master/data/db/mil-fujifilm.xml)
