### ISSUE TITLE
Vignetting: color correction?

### ISSUE THREAD

**Issue by WiLars** [lensfun/lensfun#1963]
Hello,

first, thanks for this great project!

I recently got a DJI drone, which has some really bad vignetting in the raw images, due to the small lens. For a start I tried to only do the vignetting correction. 

So i downloaded the lens_calibrate.py script and generated my own profile.

When applying it to the raw in darktable, the brightness of the vignette seems fine, but the lens seems to also have a lot of color-shift in off-angles, so the corrected image is reddish in center and blueish in the vignette area.

Before:
![image](https://user-images.githubusercontent.com/42647983/211198098-7f7c7e36-e31d-41a7-a685-508a0d17793a.png)

After:
![image](https://user-images.githubusercontent.com/42647983/211198113-525d523c-7f4a-49a5-9bbb-778af8c1d16b.png)

Is the color also supposed to be corrected and I messed up creating the calibration data, or is this expected?

Thanks!

**Comment by tuxfanx** [comment]
To me it looks like the vignetting hasn't been corrected enough or the center of the image has been overexposed. I had similar problems with the lens_calibrate.py script. I therefore only use the script [calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/). I can't say anything about the color effects.

**Comment by sarunasb** [comment]
It looks to me that vignetting correction model works for overall intensity (luminosity), not individual color channels.

**Comment by bronger** [comment]
This can be corrected using flatfields. I am personally affeted by purple corners in my NEX-7 with short focal lengths. Some Leica models suffer from the “Italian flag syndrome”. Flatfields can correct ordinary vignetting and sensor dust as well.

Was on my todo list long ago … and indeed, the current vignetting correction is not able to do this.

**Comment by WiLars** [comment]
Thanks for all your answers!

@tuxfanx: From the histogram, the image is not overexposed. I just tried also calibrate.py. It looks like the correction is stronger, but the blue halo remains:

![image](https://user-images.githubusercontent.com/42647983/211214294-864d81d1-4538-462e-8ecc-3deb0f9026da.png)

@bronger: I looked a bit into flatfields. While it seems conceptually not too complicated, i understood that this is neither supported in lensfun nor darktable right? Only substantial thing I found for darktable was a discussion you were involved in from 9 years ago...

**Comment by bronger** [comment]
I haven’t followed the discussion/development since then, I’m afraid.

**Comment by WiLars** [comment]
I did some more research, just for reference, short summary:

Above vignetting is in DNG raws from a DJI Mini 3 [Standard, not pro]. In DNG files, vignetting (and other correction data) can already be embedded. There are two versions of this correction opcodeList2 and opcodeList3.

corrections from opcodeList2 where implemented into Darktable 4.0 (darktable-org/darktable/issues/8728), which seems to be sufficient for most smartphone raw files. This basically covers the luminance part of vignetting.

For DJI drones, also instructions from opcodeList3 are needed to correct the color shift, but this has not been implemented yet: [post at pixls.us](https://discuss.pixls.us/t/looking-for-samples-smartphone-dngs-with-embedded-gainmap/27296/88)

Thanks again for clarifying that this cannot be corrected using lensfun!
