### ISSUE TITLE
Lens Profile for Panasonic Lumix G Vario 100-300mm f4.0-5.6 OIS II vs. non-II version

### ISSUE THREAD

**Issue by knoedelsalat** [lensfun/lensfun#1965]
Hi,
I was wondering for a while why Darktable wouldn't recognize my Pana 100-300 mm, although it's in the list of supported lenses. UNTIL I figured out I actually own the Mark II version.. :)
Couldn't find much info on this but it seems to be pretty much identical constructionwise.
Has anybody else come across this?
Hope this is the right place to post this issue.. I'd happily provide sample pictures for testing if that's helpful.
Thanks in advance!

**Comment by tuxfanx** [comment]
It actually seems to be optically the same lenses. As far as I have researched, version II only has an improved OIS.
Send us the data that Exiv2 reports on the lens or, even better, upload some photos[ here](https://wilson.bronger.org/calibration) with reference to this issue. 

![Pana1](https://user-images.githubusercontent.com/95431163/211377240-a398678f-55dd-467f-9821-92f996b49dd8.jpg)

![Pana2](https://user-images.githubusercontent.com/95431163/211377256-010b5be3-d924-47bc-ab92-742771c1138c.jpg)

**Comment by knoedelsalat** [comment]
Hey and thanks for the response.
Took some quick test shots across the largest room around here and uploaded them to the site.
It's night time here currently so if you need some better quality / lower iso raws let me know and i'll grab some tomorrow.
Thanks and all the best!

**Comment by IlyaDiallo** [comment]
> It actually seems to be optically the same lenses. As far as I have researched, version II only has an improved OIS. 

Yes they are optically identical

**Comment by tuxfanx** [comment]
...added a copy of the "Mega O.I.S" model for the lens to the database

**Comment by knoedelsalat** [comment]
Now that was fast :) Awesome, thanks!!!

**Comment by knoedelsalat** [comment]
After calling
`sudo /usr/bin/lensfun-update-data`
I can confirm the lens is now correctly identified as **Lumix G Vario 100-300mm F4-5.6 II Power O.I.S.** in Darktable.
Great stuff..
