### ISSUE TITLE
cmake-windows and make-lenslist stopped working properly

### ISSUE THREAD

**Issue by tuxfanx** [lensfun/lensfun#1971]
For some time now, the cmake-windows and make-lenslist build routines have stopped working properly and are throwing error messages when merging. Unfortunately, I don't have enough knowledge myself to eliminate the errors. Who can help?
Perhaps @bronger,  @sarunasb, @payano, @Sturmflut ?

**Comment by sarunasb** [comment]
make-lenslist issue is (expired?) credentials to pull/push website repo. @seebk ?
