### ISSUE TITLE
Calibration data for 3 Fujifilm G Mount lenses

### ISSUE THREAD

**Issue by twbaumann** [lensfun/lensfun#1974]
I managed to diligently calibrate my three Fujifilm G lenses

- GF23mmF4 R LM WR
- GF45mmF2.8 R WR
- GF110mmF2 R LM WR

on my GFX100S. The resulting lensfun.xml file is attached, gzip'ed. I tested the data with darktable 4.2.0 on some calibration and other images and found no issues.

First I tried to use [lens_calibrate.py](https://gitlab.com/cryptomilk/lens_calibrate/-/blob/master/lens_calibrate.py), but I could not satisfy all dependencies on MacOS 10.14.6 with MacPorts, even using the virtual environment hack for pip. Then I chose [calibrate.py](https://github.com/lensfun/lensfun/blob/master/tools/calibrate/calibrate.py) which worked ok after fixes for dcraw_emu (see [PR #1973](https://github.com/lensfun/lensfun/pull/1973)).

Remarks concerning the existing entries in mil-fujifilm.xml:
- The camera model 'GFX 100S' should be changed to 'GFX100S' without space as reported by exif data.
- The crop factor for both 'GFX 50R' and 'GFX100S' should be 0.79 instead of 0.8, in fact you get 0.790 when you take the specified sensor sizes of 43.8 x 32.9 mm.
- There is yet no entry for the Fuji G mount at the top of the file. Should it be added?
- There is an existing entry for 'GF45mmF2.8 R WR', distortion only, taken with GFX 50R.

Thanks, Thomas

[lensfun.xml.gz](https://github.com/lensfun/lensfun/files/10489372/lensfun.xml.gz)

**Comment by sarunasb** [comment]
Thank you for contributing calibration data.

Your four remarks seem to be correct. 

Could you create corresponding pull request(s) instead?

**Comment by tuxfanx** [comment]
@sarunasb I just added the lenses to the db and changed the crop factor.

**Comment by sarunasb** [comment]
Fujifilm seems to have changed to squashed names with GFX100S, there is no space in the “official” name on  https://fujifilm-x.com.  (GFX 50R is still spelled with a space.) 

Same for lens names, where focal length and aperture are squashed into one string without spaces...

**Comment by twbaumann** [comment]
Thank you for this speedy implementation. There are obviously no compatible mounts, I was just not sure if an empty mount list is formally needed.

**Comment by sarunasb** [comment]
On 24/01/2023 15.27, Joachim Daehnke wrote:
> @sarunasb <https://github.com/sarunasb> Thanks, I have changed it.
> I did not add the mentioned compat list. I'm not sure if one is 
> necessary now.

All seems to work without explicit definition of Fujifilm G mount (just 
using it in lens elements works). However for comletness sake, perhaps 
it's worth having the mount declared? I can't suggest the `<compat>` 
entries. There are adapters to G available from most other mounts, but 
how practical would their use be I don't know. Perhaps only those from 
other medium format cameras' mounts?
