### ISSUE TITLE
fujifilm lens missing affinity photo

### ISSUE THREAD

**Issue by niko800** [lensfun/lensfun#1976]
fujifilm xf 90mm f/2 r lm wr
fujifilm xf 23mm f/1.4 r lm wr

**Comment by tuxfanx** [comment]
Appropriate pictures are required for a lens calibration. You can then do the calibration yourself and provide us with your data and pictures, or just upload the pictures and ask us to do the calibration. On these websites you will find the necessary informations.
[https://pixls.us/articles/create-lens-calibration-data-for-lensfun/](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[https://wilson.bronger.org/lens_calibration_tutorial/](https://wilson.bronger.org/lens_calibration_tutorial/)
[https://wilson.bronger.org/calibration](https://wilson.bronger.org/calibration)
