### ISSUE TITLE
Calibration data for the Canon EF-M 18-150mm f/3.5-6.3 IS STM

### ISSUE THREAD

**Issue by jeremie-martin** [lensfun/lensfun#1988]
I didn't follow any guide to compute calibration data, and I was wondering if integrating the results of the method I used to lensfun was possible.

I only discovered this project today, so I would like first to make sure we are on the same page. Finding model parameters requires both the original image and a "target" one, as well as some metrics to evaluate how close the corrected image is to the target. From my understanding, taking shots of a building with several parallel straight lines implicitely allows for implicitely getting target images. Since we know that the ground truth is an image with parallel straight lines, we can optimize for it.

I don't have a tripod and I don't feel comfortable making a distortion model (following [pixls.us/articles/create-lens-calibration-data-for-lensfun/](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)) without a one. I don't have a diffuser to create vignetting model either.

What I do have, however, is a Canon (M50) camera applying various lens corrections to the RAWS in order to render JPGs. In other words, I have both original (RAW, with distortion and aberration) images and target images (the JPGs produced by my camera). I used [fulla](https://wiki.panotools.org/Fulla) to apply corrections from the command line, and [mealpy](https://pypi.org/project/mealpy/) to search for parameters (with neat metaheuristics) that minimize the difference (RMSE) between the corrected photo and the target JPG.

To put it differently, I'm trying to find parameters resulting in corrected images that are as close as possible to the JPGs. The distortion and vignetting calibrations were performed separately. Assuming that the lens corrections applied by the camera are good, I don't think this idea is too far-fetched. The optimisation scheme yielded the following calibration data:

```xml
    <lens>
        <maker>Canon</maker>
        <model>Canon EF-M 18-150mm f/3.5-6.3 IS STM</model>
        <mount>Canon EF-M</mount>
        <cropfactor>1.613</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="18" a="0.00905" b="-0.02848" c="-0.00818"/>
            <distortion model="ptlens" focal="24" a="0.00048" b="0.01360" c="-0.03005"/>
            <distortion model="ptlens" focal="35" a="0.00266" b="0.00407" c="-0.00106"/>
            <distortion model="ptlens" focal="50" a="-0.00029" b="0.00599" c="0.00561"/>
            <distortion model="ptlens" focal="70" a="-0.00191" b="0.01081" c="-0.00178"/>
            <distortion model="ptlens" focal="100" a="-0.00024" b="0.00377" c="0.00649"/>
            <distortion model="ptlens" focal="150" a="-0.00077" b="0.00762" c="-0.00346"/>
            <vignetting focal="18.000000" model="pa" aperture="3.5" distance="10" k1="0.04696" k2="0.00985" k3="-0.49919" />
            <vignetting focal="18.000000" model="pa" aperture="22" distance="10" k1="0.00197" k2="-0.05294" k3="0.12181" />
            <vignetting focal="24.000000" model="pa" aperture="4" distance="10" k1="-0.10420" k2="-0.08344" k3="0.06890" />
            <vignetting focal="24.000000" model="pa" aperture="22" distance="10" k1="-0.00292" k2="0.00767" k3="0.00649" />
            <vignetting focal="35.000000" model="pa" aperture="5" distance="10" k1="0.51104" k2="-1.40645" k3="0.77008" />
            <vignetting focal="35.000000" model="pa" aperture="22" distance="10" k1="0.28663" k2="-0.34990" k3="-0.06909" />
            <vignetting focal="50.000000" model="pa" aperture="5.6" distance="10" k1="0.14994" k2="0.01512" k3="-0.36314" />
            <vignetting focal="50.000000" model="pa" aperture="32" distance="10" k1="0.11565" k2="0.16804" k3="-0.17441" />
            <vignetting focal="70.000000" model="pa" aperture="6.3" distance="10" k1="0.07902" k2="0.00251" k3="-0.16930" />
            <vignetting focal="70.000000" model="pa" aperture="32" distance="10" k1="0.24362" k2="-0.03176" k3="-0.18571" />
            <vignetting focal="100.000000" model="pa" aperture="6.3" distance="10" k1="0.24429" k2="-0.40847" k3="0.02193" />
            <vignetting focal="100.000000" model="pa" aperture="32" distance="10" k1="0.23152" k2="0.02350" k3="-0.00149" />
            <vignetting focal="150.000000" model="pa" aperture="6.3" distance="10" k1="0.61443" k2="-1.10638" k3="-0.02177" />
            <vignetting focal="150.000000" model="pa" aperture="32" distance="10" k1="0.08703" k2="0.10821" k3="0.00581" />
        </calibration>
    </lens>
```

The [sample.zip](https://github.com/lensfun/lensfun/files/10772917/sample.zip) archive contains two JPGs produced by the camera, the corresponding original RAWs, and the RAWs with lens corrections (using the above configuration). These photos weren't used for calibrating the distortion and vignetting models. I think the results are pretty decent.

Have you ever considered this kind of approach? What do you think of it? Would you consider using such a method for calibration?

Kind regards,
Jérémie

**Comment by tuxfanx** [comment]
Thank you for your interesting contribution.
I work in this project as a calibrator. So I generate the correction data from the images uploaded by others [here](https://wilson.bronger.org/calibration) or check pullrequests and merge the data.
Unfortunately, I don't have the time and the necessary theoretical knowledge to assess your calibration procedure. So others have to check whether your calibration method is a suitable alternative for the lensfun project. From my experience, I can only point out that the corrected jpeg images from the manufacturers are not always completely corrected.

Unfortunately, I cannot transfer your attached calibration data to the lensfun database. Your sample images are not suitable for an assessment of your correction data.
To check the distortion correction, I need images in raw format, as we use them for the conventional calibration method (straight lines at the edges of the image across the entire width of the image with different focal lengths).
To check the vignetting correction, I need raw images of evenly illuminated areas without coarse structures at different f-stops as [described here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/). There are too few f-stops in your data.
A tripod is not necessary to take the pictures if the lighting conditions allow sufficiently sharp pictures.

**Comment by sarunasb** [comment]
@jeremie-martin Thank you for proposing the new technique. I don't think I ever explicitly used fulla or mealpy. It is conceivable that correction parameters might be created this way, and, as long as the parameters satisfy Lensfun requirements and provide good corrections, Lensfun “doesn't care” how they are obtained... However it will take quite some testing to verify corrections provided by the new technique. I can't think of another way, but to also take images (same camera+lens) suitable for traditional calibrations by Hugin as already mentioned by @tuxfanx (or [here](https://wilson.bronger.org/lens_calibration_tutorial/)). Then to apply your corrections to these images to check how they work.

**Comment by mateuszmonas1** [comment]
Hi @jeremie-martin, can you explain how are you using fulla and mealpy to create the correction data? I am not familiar with those tools, but I want to create lens correction data for canon RF-S 18-45mm F4.5-6.3 IS STM

**Comment by tuxfanx** [comment]
outdated --> closed
