### ISSUE TITLE
TCA Data for Nikon AF-S DX Nikkor 18-140mm f/3.5-5.6G ED VR lens

### ISSUE THREAD

**Issue by JohannMaierhofer** [lensfun/lensfun#1990]
Hello,
I have created TCA data for the Nikon AF-S DX Nikkor 18-140mm f/3.5-5.6G ED VR in the slr-nikon-xml file. I tested it now with a lot of pictures and it looks good. Please add them to the official file.
The data is as folloows:

            <tca model="poly3" focal="18" br="-0.0001916" vr="1.0009998" bb="0.0001285" vb="0.9997426"/>
            <tca model="poly3" focal="20" br="-0.0001891" vr="1.0009404" bb="0.0001793" vb="0.9996954"/>
            <tca model="poly3" focal="22" br="-0.0001837" vr="1.0008932" bb="0.0001324" vb="0.9997418"/>
            <tca model="poly3" focal="24" br="-0.0001577" vr="1.0008288" bb="0.0001143" vb="0.9997407"/>
            <tca model="poly3" focal="26" br="-0.0001465" vr="1.0007831" bb="0.0000824" vb="0.9998015"/>
            <tca model="poly3" focal="30" br="-0.0001306" vr="1.0007034" bb="0.0000894" vb="0.9997340"/>
            <tca model="poly3" focal="35" br="-0.0000929" vr="1.0005827" bb="0.0000756" vb="0.9997086"/>
            <tca model="poly3" focal="40" br="-0.0000959" vr="1.0005443" bb="0.0000250" vb="0.9997541"/>
            <tca model="poly3" focal="45" br="0.0000092" vr="1.0003605" bb="-0.0000167" vb="0.9997551"/>
            <tca model="poly3" focal="50" br="0.0000045" vr="1.0003880" bb="-0.0000683" vb="0.9997559"/>
            <tca model="poly3" focal="56" br="-0.0000485" vr="1.0002527" bb="-0.0000445" vb="0.9997916"/>
            <tca model="poly3" focal="60" br="0.0000522" vr="1.0001988" bb="-0.0000928" vb="0.9997309"/>
            <tca model="poly3" focal="66" br="0.0000171" vr="1.0001340" bb="-0.0001165" vb="0.9998056"/>
            <tca model="poly3" focal="75" br="-0.0000092" vr="1.0000965" bb="-0.0000882" vb="0.9997899"/>
            <tca model="poly3" focal="85" br="-0.0000344" vr="1.0000424" bb="-0.0000398" vb="0.9998374"/>
            <tca model="poly3" focal="90" br="-0.0000007" vr="1.0000097" bb="-0.0001575" vb="0.9998096"/>
            <tca model="poly3" focal="100" br="0.0000275" vr="0.9999155" bb="-0.0001050" vb="0.9997124"/>
            <tca model="poly3" focal="105" br="-0.0000095" vr="0.9999045" bb="-0.0001107" vb="0.9997393"/>
            <tca model="poly3" focal="116" br="-0.0000267" vr="0.9998839" bb="-0.0000935" vb="0.9996854"/>
            <tca model="poly3" focal="122" br="-0.0000332" vr="0.9998680" bb="-0.0000387" vb="0.9996507"/>
            <tca model="poly3" focal="130" br="-0.0000278" vr="0.9997975" bb="-0.0000941" vb="0.9996551"/>
            <tca model="poly3" focal="140" br="-0.0000292" vr="0.9997377" bb="-0.0000136" vb="0.9994377"/>

**Comment by tuxfanx** [comment]
@JohannMaierhofer 
Can you tell me which camera model you used?

**Comment by JohannMaierhofer** [comment]
I was a Nikon D5500
