### ISSUE TITLE
Package building --- a (probably silly) problem. 

### ISSUE THREAD

**Issue by Rmano** [lensfun/lensfun#200]
Hi --- 
I was trying to use this version of lensfun (which is correctly supporting my lenses) with Darktable without having to rebuild it, which is a bit, let say, a big deal ;-). 

Lensfun compiles beatifully; the only problem is that when you build the binary packages, it creates a `liblensfun1` package, even if the library is 0.3.2. What happens is that in this way there is no way to "upgrade" the lib.so links for the (standard, old) `liblensfun0` (linking to 0.2.8), because: 

- if I remove the `liblensfun0` package, the system asks to remove darktable (and a lot of other things) too. 

- if I just install both packages, then I have to manually link `liblensfun.so.0` to the new version, and every update will restore the old link. 

Is there a way to make the `build packages` generate a `liblensfun0` package? In that way it would just override the 0.2.8 one and all will beautifully work (I think, at least). 

Thanks a lot, Romano

PS the installed package has a problem, too; it seems that the python libraries are not installed, and that leads to `lensfun-update-data` not working... with a `missing lensfun module` message.

**Comment by junkyardsparkle** [comment]
To whatever extent this is a lensfun issue (it sounds like it might be more a distro/packaging issue) it might be better addressed at the mailing list:
 https://lists.sourceforge.net/lists/listinfo/lensfun-users
I'm not sure if the scope of this repository extends beyond lens profiles, currently.

**Comment by bronger** [comment]
I also suggest to copy-and-paste it to the mailing list.  Alternatively, open an issue on https://sourceforge.net/p/lensfun/bugs/.  This repository is for calibration work only.
