### ISSUE TITLE
MinGW cross compiling under Linux for Windows target 64 bits is broken since few days

### ISSUE THREAD

**Issue by cgilles** [lensfun/lensfun#2001]
Hi all,

While cross compiling whole digiKam Windows installer, Lensfun compilation is broken since few days (probably it miss a header somewhere in source code)

-- Build files have been written to: /mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/build.mxe
[100%] Performing build step for 'ext_lensfun'
[  6%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj
[ 20%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/cpuid.cpp.obj
[ 20%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.obj
[ 26%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.obj
[ 33%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj
[ 40%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse.cpp.obj
[ 46%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord-sse.cpp.obj
[ 53%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse2.cpp.obj
[ 60%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color.cpp.obj
[ 66%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-subpix.cpp.obj
[ 73%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord.cpp.obj
[ 80%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-pc.cpp.obj
[ 86%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/modifier.cpp.obj
[ 93%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.obj
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Load(const char*, const char*, size_t)':
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:826:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:826:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:827:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:827:59: error: expected ')' before numeric constant
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:827:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:858:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
  858 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Save(char*&, size_t&) const':
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:901:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:901:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:902:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:902:59: error: expected ')' before numeric constant
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:902:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/database.cpp:1144:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
 1144 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
libs/lensfun/CMakeFiles/lensfun.dir/build.make:91: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj' failed
make[6]: *** [libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj] Error 1
make[6]: *** Waiting for unfinished jobs....
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp: In member function 'void lfLens::GuessParameters()':
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:178:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  178 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:178:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  178 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:179:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:179:59: error: expected ')' before numeric constant
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:179:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  179 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
/mnt/data/temp.build/ext_lensfun/ext_lensfun-prefix/src/ext_lensfun/libs/lensfun/lens.cpp:271:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
  271 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
libs/lensfun/CMakeFiles/lensfun.dir/build.make:106: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj' failed
make[6]: *** [libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj] Error 1
CMakeFiles/Makefile2:130: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/all' failed
make[5]: *** [libs/lensfun/CMakeFiles/lensfun.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make[4]: *** [all] Error 2
ext_lensfun/CMakeFiles/ext_lensfun.dir/build.make:85: recipe for target 'ext_lensfun/ext_lensfun-prefix/src/ext_lensfun-stamp/ext_lensfun-build' failed
make[3]: *** [ext_lensfun/ext_lensfun-prefix/src/ext_lensfun-stamp/ext_lensfun-build] Error 2
CMakeFiles/Makefile2:1165: recipe for target 'ext_lensfun/CMakeFiles/ext_lensfun.dir/all' failed
make[2]: *** [ext_lensfun/CMakeFiles/ext_lensfun.dir/all] Error 2
CMakeFiles/Makefile2:1172: recipe for target 'ext_lensfun/CMakeFiles/ext_lensfun.dir/rule' failed
make[1]: *** [ext_lensfun/CMakeFiles/ext_lensfun.dir/rule] Error 2
Makefile:345: recipe for target 'ext_lensfun' failed
make: *** [ext_lensfun] Error 2
FAILED COMMAND: ${MXE_BUILD_TARGETS}-cmake --build . --config RelWithDebInfo --target ext_lensfun -- -j$CPU_CORES

Note : we cross compile under Linux using MXE (https://mxe.cc/)

Gilles Caulier

**Comment by cgilles** [comment]
Note code compiled come from master branch

**Comment by sarunasb** [comment]
> Note code compiled come from master branch

Thank you for reporting. It is a know issue, as you found. Perhaps use latest release instead of development branch?

**Comment by cgilles** [comment]
Ah, i don't seen that a new stable release is out, since a very long time (:-)))... 

Do you plan to release more frequently the library as stable ? If yes, i can drop the rolling release workflow to compile digiKam bundles.

Gilles Caulier

**Comment by cgilles** [comment]
Just tested. lensfun from git/master compile fine now under MinGW
