### ISSUE TITLE
dcraw and exiv2, and both don’t support CR3 files yet - calibration submission

### ISSUE THREAD

**Issue by jayray-git** [lensfun/lensfun#2039]
Getting the following message when submitting calibration request.

Sorry, we use dcraw and exiv2, and both don’t support CR3 files yet.

I think dcraw and exiv2 has supported CR3 for a while now.

**Comment by jonas-ott** [comment]
Similar to https://github.com/lensfun/lensfun/issues/1139 

Replacing dcraw with dcraw_emu in `tools/calibration_webserver/utils.py` and removing the error handling in `tools/calibration_webserver/process_upload.py` should work.
However, I couldn't get the webserver to start and didn't test it.

**Comment by salmo6** [comment]
I just tried to upload data from a new lens and I'm getting the same error. I use dcraw and exiv2 in my daily photo editing and CR3 files have been supported for some time now.

**Comment by jayray-git** [comment]
So, when will the upload page be updated with the fixes? Still getting the message "Sorry, we use dcraw and exiv2, and both don’t support CR3 files yet."

**Comment by bronger** [comment]
I have physical access to the ownCloud computer tomorrow and will try an update of ownCloud and the upload service.
