### ISSUE TITLE
Converting lens correction data

### ISSUE THREAD

**Issue by aaeneas** [lensfun/lensfun#2045]
Apparently my Canon EF 70-300mm f/4-5.6 IS II USM is NOT among those supported by the standard LensFun Version 1 database.  I have noticed that there is supposed to be a way to convert Adobe LCP files such that the result can be used with LensFun.  I've tried that but it does NOT seem to work.

This causes me to think that there could be an even better way to convert lens correction data into the format used by LensFun.  In my case, Canon provides lens correction data that it's software (Canon Digital Photo Professional 4) downloads for that purpose.  Why NOT convert that data for use in LensFun?  Might that be what Adobe is doing?  If possible how is done?

**Comment by sarunasb** [comment]
Why not take a look at that data from Canon's software and see how it correlates with the model used by Lensfun?

**Comment by MStraeten** [comment]
> In my case, Canon provides lens correction data
Does canon really provide these data for public use? If they do then it doesn't make sense to use lensfun with converted data instead of implementing specific correction algorithms ...

**Comment by aaeneas** [comment]
Not sure exactly what "public use" means in this context.  I haven't studied all the Ts&Cs real carefully.  The data being referenced is furnished without charge as part of using the software that Canon supplies.  I'm sure the software is proprietary but as best I can tell anyone can download it.  One would expect, and based on my experience I would say, that the software is designed such as to support Canon products.  I'd also say it is doubtful that many, if any, users would want to use this software if not in conjunction with Canon products.  When it comes to the use of the data in question I'd say the same thing is true.  In that, it is hard to imagine why Canon would object to their customers using Lensfun in support of their products.

One idea I'm pursuing is using the Canon software to produce a preliminary image (in .tif format) with lens correction applied and then process the resulting .tif image file with other software.  Obviously this involves extra work, which is NOT desirable, but I do NOT yet have an opinion to offer regarding the quality of the resulting image files.

Also, I have now followed the advice on the Lensfun website for taking and submitting pictures to be used for including this lens in the standard Lensfun database.  However, I haven't learned whether or NOT anything has been done with respect to making that happen.

**Comment by MStraeten** [comment]
public use means a well documented format and accessibility outside closed software… if it’s as well made public available as the cr3 file format then don’t hold your breath ;)

**Comment by sarunasb** [comment]
> Also, I have now followed the advice on the Lensfun website for taking and submitting pictures to be used for including this lens in the standard Lensfun database. However, I haven't learned whether or NOT anything has been done with respect to making that happen.

@aaeneas Did you try to upload images for calibration? I don't see EF 70-300 among calibration uploads.

**Comment by aaeneas** [comment]
***
> 
> @aaeneas _Did you try to upload images for calibration? I don't see EF 70-300 among calibration uploads._

Yes!  However, I tried again just now and was sent a notification saying that Canon CR3 file types are NOT supported.  However, I would point out that another lens of mine (Canon RF 24-105mm F4 L IS USM) is supported.  It can only be mounted on Canon's newer mirror-less cameras that, I think, produce only CR3 format files.

It looks to me like the Lensfun database uses different files for different types of cameras.  For example, the file named slr-canon.xml refers to dSLR type cameras whereas the file named mil-canon.xml refers to mirror-less cameras.  I'm thinking that all of Canon's mirror-less cameras produce CR3 format files.  Therefore, I would deduce that all of the cameras referenced in the file name mil-canon.xml use CR3 format files.  Sounds like that might mean there is another way to acquire and process the data used to calibrate lens.  What's going on here?

**Comment by MStraeten** [comment]
Some RF lensfun data were generated and contributed by users having a toolchain built with cr3 support. The toolchain of the lensfun service is quite old…
you might have a look at https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/

**Comment by aaeneas** [comment]
Another thought that comes to mind.  My 70-300mm lens that is missing correction data is being used on a camera with a crop sensor.  As it happens I do have a full frame camera that also uses the same Canon EF lens mount.  This means I could mount this 70-300mm lens on a different camera that does produce CR2 format files.  However, my inclination is to think that the lens distortion on a full frame sensor will differ from a crop sensor.  What about that?

**Comment by MStraeten** [comment]
the lens correction data generated on full frame sensor can’t be used for a crop sensor.

**Comment by aaeneas** [comment]
That is what I suspected.

Another thought, I believe the problem with CR3 files has to do with extracting metadata and NOT the raw sensor data.  At least that is the case with other software when processing CR3 format files.  Insofar as I have and use ExifTool I can easily extract the metadata and include it as sidecar files in the zip archive that is submitted.  ExifTool does offer a variety of formats where plain text is one possibility that is pretty easy for people to read.  If I knew which metadata items were needed I'd also be willing to filter it down to just those.  What about this possibility?

**Comment by MStraeten** [comment]
no need reasoning if that’s file format or metadata ;) if you want to make use of the calibration service you need to wait until that is able to cope with cr3 file format. 
see https://github.com/lensfun/lensfun/pull/2040

**Comment by sarunasb** [comment]
@aaeneas Until calibration service is update, feel free to share your calibration images somewhere online and I'll see if I can measure correction data.

**Comment by tuxfanx** [comment]
Pictures uploaded in  #2053 not suitable for calibration --> closed

**Comment by tuxfanx** [comment]
Vignetting data generated from #1234 and added to db
