### ISSUE TITLE
Calibration data for Sony 20-70mm f/4 - SEL2070G

### ISSUE THREAD

**Issue by zemumu** [lensfun/lensfun#2046]
Hi,

I'm creating the new Sony 20-70mm f/4 lensfun datas.

But, with the hugin distortion datas, lensfun used from darktable increases the distortion instead of reducing it.

I check the result of hugin by making hugin generates corrected picture. It's ok.
I check if I've a problem of lensfun version but other lenses are ok.

Do you have any idea that wold explains this behavior ?

By the way, to have more precision with hugin data, I recommend to save lens data in a ini file ...

Regards
Vincent
![pb-lensfun-Sony2070](https://github.com/lensfun/lensfun/assets/94993213/271a0151-3013-4b7e-8cc6-59f40ed9ca82)
[Lensfun calibration Sony SEL2070G.zip](https://github.com/lensfun/lensfun/files/11772608/Lensfun.calibration.Sony.SEL2070G.zip)

**Comment by zemumu** [comment]
Hi,
I've understand my error : I've indicated poly3 instead of ptlens as model for distortion !
With the right model, it works fine.
![lensfunok](https://github.com/lensfun/lensfun/assets/94993213/6037ce19-05d1-49ff-803b-2fbf7139e377)

I'll check the other corrections and I will soon give you the final file for integration in the next lensfun release.
Regards
Vincent

**Comment by zemumu** [comment]
I've verified my datas.

Here is the file with parameters for Sony FE 20-70mm f/4 G - SEL2070G
[mil-sony-2070.zip](https://github.com/lensfun/lensfun/files/11803680/mil-sony-2070.zip)
.
The calibration was generated with the Torsten Bronger’s python script.

Thanks to add the lens data to the lensfun data base.

best regards
Vincent

**Comment by zemumu** [comment]
Hi,
You can download the files here : https://www.dropbox.com/sh/y2hxqwepy22tgdu/AADyHLm3t4FOHi_E6Od1Wq1ra?dl=0
I find the lensfun correction better than autocorrection of jpg files or than metadata correction of darktable ... 
Regards
Vincent

**Comment by sarunasb** [comment]
@zemumu Thank you for calibrating the lens and for sample images. Lensfun DB updated with your correction parameters, commit [3da9c0a](https://github.com/lensfun/lensfun/commit/3da9c0a58085ebdebaf517bb6092d01ffe8dcbbd).

Yes, indeed, your measured corrections are better, than the ones in RAW metadata from manufacturer.
