### ISSUE TITLE
Lensfun does not recognize the Olympus EP7

### ISSUE THREAD

**Issue by ghostwheelVa** [lensfun/lensfun#2075]
The Olympus EP7 is a standard micro 4/3's camera (same sensor and form factor as the EM1mkiii and EM5mkiii.  

Can it be added so that it is recognized automatically.

**Comment by sarunasb** [comment]
Thanks for noting. E-P7 added in [6d6b9f3](https://github.com/lensfun/lensfun/commit/6d6b9f3954db205b0ccf872a5b888871b4336e16).
