### ISSUE TITLE
Calibration Request Viltrox 13mm F1.4 AF E

### ISSUE THREAD

**Issue by xyzianz** [lensfun/lensfun#2082]
I have a calibration wish for _Viltrox 13mm F1.4 AF_ for Sony E mount. If needed I may help with sample photos, but with some delays.

**Comment by tuxfanx** [comment]
For a calibration we need the raw images. [Please read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (in section "Taking pictures") how to take the pictures.
