### ISSUE TITLE
Sigma 14mm f/2.8 EX Aspherical HSM not identified

### ISSUE THREAD

**Issue by urbach** [lensfun/lensfun#2084]
The "Sigma 14mm f/2.8 EX Aspherical HSM" is not identified in 'darktable' with 'lensfun' version 0.3.3. I think this is a labeling issue, because I assume what is called "Sigma 14mm f/2.8 EX" in 'lensfun' is the very same lens. If so, is there a way that this is identified correctly?
If not, I'd be happy to provide calibration pictures. If needed and useful, I can do this anyhow for the EOS R7, I think there is no correction data available for this crop factor.

Thank you very much for this great software!

**Comment by sarunasb** [comment]
Yes, please provide calibration pictures.

**Comment by urbach** [comment]
It seems the calibration service of lensfun (fantastic that this exists!) does not yet work for 'CR3'. So I did it myself. I hope, the corresponding calibration profile (distortion and TCA) is okay, I haven't done this before. The resulting corrected photos look reasonable, but again, I don't have much experience.
Shall I create a pull request or provide the XML file here? Thanks!

**Comment by tuxfanx** [comment]
@urbach 
You can provide your XML file here. Please [upload](https://wilson.bronger.org/calibration) your pictures too. IF CR3 does not work you can upload converted pictures ([dng](https://helpx.adobe.com/de/camera-raw/using/adobe-dng-converter.html) or tiff)

**Comment by kmilos** [comment]
> IF CR3 does not work

Wasn't this enabled recently in https://github.com/lensfun/lensfun/pull/2040

**Comment by urbach** [comment]
> > IF CR3 does not work
> 
> Wasn't this enabled recently in https://github.com/lensfun/lensfun/pull/2040?

CR3 works in lensfun, I think, but not in the upload service... (I have a
workflow, if needed...)

**Comment by tuxfanx** [comment]
upload is working --> closed
