### ISSUE TITLE
How can I use lensfun with darktable automatically with a crop lens on a fullframe camera in crop mode?

### ISSUE THREAD

**Issue by ethpi** [lensfun/lensfun#2085]
I'd like to use my Nikon DX lenses on the fullframe camera Nikon D850, because in the first time after my upgrade from DX to FX I only have very less FX lenses.

If I open an image (crop lens on fullframe camera in crop mode)  and acitvate lens correction, darktable tells me "_camera/lens not found"_.  
If I add the line `<cropfactor>1.5</cropfactor>` in `~/.local/share/lensfun/updatex/version_1/slr-nikona.xml` in the camera section for the Nikon D850 it works properly. But an update with `lensfun-update-data` may overwrite my personal hack.

Is there any permanent solution for this?

**Comment by sarunasb** [comment]
Lensfun will read its XML files in `~/.local/share/lensfun/` as well. These are not overwritten by updates. However setting cropfactor for a camera there will override it globally, so your D850 will become a DX camera: for images taken with FX lenses Lensfun will not automatically find corrections.

**Comment by ethpi** [comment]
Thanks for your reply.

I deleted the line `<cropfactor>1.5</cropfactor>` in  `~/.local/share/lensfun/updatex/version_1/slr-nikona.xml ` to restore the initial state. Afterwards I added a file with 

```
<lensdatabase version="1">
    <camera>
        <maker>Nikon Corporation</maker>
        <maker lang="en">Nikon</maker>
        <model>Nikon D850</model>
        <model lang="en">D850</model>
        <mount>Nikon F AF</mount>
        <cropfactor>1</cropfactor>
        <cropfactor>1.5</cropfactor>
    </camera>
</lensdatabase>
```
in `~/.local/share/lensfun/`. Everyworks fine now. FX- **and** DX-lenses are found. Maybe because of the both cropfactors in the file.
