### ISSUE TITLE
Nikon Coolpix A1000 RAW camera support

### ISSUE THREAD

**Issue by ukmark62** [lensfun/lensfun#2099]
Hi,
Would it be possible to add support for the Nikon Coolpix A1000 camera? This would be to remove any vignetting at wide angle and lens corrections etc? I have the camera and would provide any samples required.

I believe "lensfun" is used by Topaz Photo AI for raw processing. It would be great if the A1000 was supported. Many thanks for your time.

**Comment by tuxfanx** [comment]
For this we need correctly taken pictures. How to take these pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://wilson.bronger.org/calibration). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). The calibration can then be carried out by the members of this project. 
The other option is to do the calibration yourself (preferably on a Linux operating system) and make the data available to this project.

Here you will find some hints:
[calibration with lens_calibrate.py and taking pictures](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[calibration and taking pictures](https://wilson.bronger.org/calibration)
[video 1 calibration with Hugin](https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/)
[video 2 calibration with Hugin](https://www.youtube.com/watch?v=_p0fR-nH6cU)
[lensfuns coverage](https://wilson.bronger.org/lensfun_coverage.html)
[lensfuns database](https://github.com/lensfun/lensfun/tree/master/data/db)
[calibration with calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/)

**Comment by ukmark62** [comment]
Thanks for getting back. Luckily, I downloaded Nikon's free "NX Studio" software, which handles A1000 RAW files and corrects any lens distortion automatically. This can then be exported as a TIFF and then loaded into Topaz Denoise AI.
