### ISSUE TITLE
 Vignetting data for Samyang 20mm f/1.8 ED AS UMC

### ISSUE THREAD

**Issue by zemumu** [lensfun/lensfun#2100]
Hello,

I've just completed the calibration data of Samyang 20mm f/1.8 ED AS UMC in the file slr-samyang.xml with vignetting correction.

Regards
Vincent
[lensfun_Samyang_20mm_f_1_8_ED_AS_UMC.zip](https://github.com/lensfun/lensfun/files/12407125/lensfun_Samyang_20mm_f_1_8_ED_AS_UMC.zip)

**Comment by tuxfanx** [comment]
@zemumu 
Thanks for the data!
Could you [upload some sample pictures](https://wilson.bronger.org/calibration) for a test? Could not find any.

**Comment by zemumu** [comment]
Hello,
Here are the files : https://www.dropbox.com/scl/fo/z8gw6fkxajc0jo3xg3gcg/h?rlkey=0m0w9i5yxqvhm3usdhiezt9vl&dl=0
Regards

**Comment by zemumu** [comment]
Hello,

I've just update my linux system and I some problem with lensfun, with 
lenses I try to modify the correction datas.

Before the update, I did it without any problem and I can see my 
modified lenses into Dartable.

But now they don't appear in the lenses list.

I've copied the data in the files in /usr/share/lensfun/version_1/, I've 
launched the command lensfun-update-data , I've rebooted my computer but 
the modified lense doesn't appear in the list.

Do you have any idea ?

Best regards

Vincent

Le 2023-08-30 18:09, Joachim Daehnke a écrit :

> Thanks!
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/lensfun/lensfun/issues/2100#issuecomment-1699462529
[2]
