### ISSUE TITLE
Fujifilm XF27mm F/2.8 WR Not Recognized

### ISSUE THREAD

**Issue by etrigan63** [lensfun/lensfun#2106]
Lensfun currently has the Fujifilm XF27mm f/2.8 but the newer model adds Weather Resistance and is designated Fujifilm XF27mm F/2.8 WR. These are identical lenses. Please add the new name to the database.

**Comment by tuxfanx** [comment]
@etrigan63 
Did you mean Fujifilm XF 27mm F2.8 **R** WR?

**Comment by etrigan63** [comment]
Yes. My bad for not including the extra R.
