### ISSUE TITLE
DJI mini 3 pro corrections, how

### ISSUE THREAD

**Issue by Cobert0** [lensfun/lensfun#2111]
proposed lens corrections on dji mini 3 pro, how i do?

lensdatabase version="1">
    <camera>
        <maker>DJI</maker>
        <model>FC3582</model>
        <model>Mini 3 Pro</model>
        <mount>djiFC3582</mount>
        <cropfactor>3.6</cropfactor>
    </camera>
    <lens>
        <maker>DJI</maker>
        <model>FC3582 &amp; compatibles</model>
        <model lang="en">FC3582 fixed lens</model>
        <mount>djiFC3582</mount>
        <cropfactor>3.6</cropfactor>
        <aspect-ratio>4:3</aspect-ratio>
        <calibration>
            <distortion model="ptlens" focal="6.7" a="-0.0075" b="0.026" c="-0.0027"/>
            <tca model="poly3" focal="6.7" vr="1.0000350" vb="0.9999842"/>
            <vignetting model="pa" focal="6.7" aperture="1.7" distance="10" k1="-2.7528" k2="3.9587" k3="-2.0068"/>
            <vignetting model="pa" focal="6.7" aperture="1.7" distance="1000" k1="-2.7528" k2="3.9587" k3="-2.0068"/>
        </calibration>
    </lens>
</lensdatabase>

**Comment by Cobert0** [comment]
It was xml text in the issue... why lensfun xml cannot be attached ?

**Comment by sarunasb** [comment]
Rename it to .txt for attachment. We will also need some sample images to check the corrections. You can share images anywhere in the Internet.

**Comment by Cobert0** [comment]
Thanks for answer,
A link to photos used for calibration and samples, and the lensfun.xml correction file.
https://drive.google.com/drive/folders/1RM5h3HLllFIIDfz45mwJkxy8dLrdeUZ0?usp=sharing
Vignetting correction is not optimal because red channel is very different than green and blue but better than nothing.

**Comment by Cobert0** [comment]
Hello,
is samples images link OK ? or have to use https://wilson.bronger.org/calibration?
regards.

**Comment by sarunasb** [comment]
Thank you for correction data and samples. Corrections added to Lensfun DB.

**Comment by tuxfanx** [comment]
fixed --> closed
