### ISSUE TITLE
[error] lensfun 0.3.4_rc1 and lensfun-update-data 

### ISSUE THREAD

**Issue by AxelG-DE** [lensfun/lensfun#2112]
I might be an issue on my Distro (Gentoo with python3.11) but currently hard to tell.

when I invoke lensfun-update-data, I get:

```
Traceback (most recent call last):
  File "/usr/bin/lensfun-update-data", line 46, in <module>
    import lensfun
ModuleNotFoundError: No module named 'lensfun'
```

**Comment by sarunasb** [comment]
It's a known Gentoo emerge issue.
You can try adding Lensfun Python library in some other way.
If anything can be improved regarding this on Lensfun side, please reopen the issue.
