### ISSUE TITLE
Lens profile submission for Viltrox 13/1.4 AF for Fujifilm X mount (also good for Sony E and Nikon Z)

### ISSUE THREAD

**Issue by bachrocks** [lensfun/lensfun#2115]
Hi Lensfun community

Attached please find a profile for the Viltrox 13/1.4 that I created and tested. 

I would kindly like to ask you to add this profile to misc.xml.

The profile should also work for the Sony E and Nikon Z versions of this lens.
[Vitrox 13 AF Lens Profile.odt](https://github.com/lensfun/lensfun/files/12791672/Vitrox.13.AF.Lens.Profile.odt)

One comment. The lens maker and model according to evix2 -pv are
- maker: VILTROX - I did not spell it in capitals as misc.xml already contains a Viltrox lens where Viltrox is spelled in normal letters. But you may change the maker to VILTROX is you want.
- model: AF 13/1.4 XF for the Fujifilm version - But this syntax does not work with my install of darktable. The lens is (i) not recognized automatically and (ii) if I manually select it, the correction is not applied. So far I found no solution. I chose an own model name; this works perfectly, I just need to select the lens manually. You may change the model if you want. Keep in mind that the Nikon and Sony versions will have different model names. I can provide you a Fujifilm raw upon request.

Regards,
Martin

**Comment by bachrocks** [comment]
Regarding my comment, I just saw I'm not the only one.
[https://github.com/lensfun/lensfun/issues/1896](url)
Well. Most importantly, the profile is there. Auto detection of the Viltrox lenses would be nice but is not key.
Regards,
Martin

**Comment by tuxfanx** [comment]
@bachrocks 
Could you provide some raw pictures?

**Comment by bachrocks** [comment]
Sure. I am sorry for the delay, I was two days not at home.
What is the purpose? Testing my profile or the Exif / auto recognition topic?
These are two random samples from my tests. Let me know in case you need more.
[Viltrox AF 13/1.4 XF raw samples](https://c.gmx.net/@324516463530477224/adwxPM9mQUeuqBYAh3lUFg)
As I said, I own the Fujifilm-X version.

Cheers,
Martin

**Comment by tuxfanx** [comment]
@bachrocks 
Thanks for the pictures! I added your profile to the db. 
For my part, I only add profiles to the database when I have been able to test the lens profile on a few pictures.
Cheers,
Joachim
