### ISSUE TITLE
Lens profile submission for Laowa 9mm f/5.6 FF RL adapted to APS-C (Fujifilm-X)

### ISSUE THREAD

**Issue by bachrocks** [lensfun/lensfun#2117]
Dear Lensfun community

I made a profile for the Laowa 9mm f/5.6 FF RL lens. This is a full frame lens. however, I use it on my Fujifilm-X APS-C camera and hence can only deliver a correction profile for APS-C with a crop factor of 1.529. I seriously hope you can add it to misc.xml anyway. Creating a good profile for an ultra wide angle lens is quite demanding.

```
<lens>
<maker>Venus</maker>
<model>Laowa 9mm f/5.6 FF RL</model>
<mount>Fujifilm X</mount>
<cropfactor>1.529</cropfactor>
<calibration>
<!-- Taken with Fuji X-T20 -->
<distortion model="ptlens" focal="9" a="0.00347" b="-0.00922" c="-0.01236"/>
<tca model="poly3" focal="9.0" vr="0.9997434" vb="1.0003385" />
<vignetting model="pa" focal="9.0" aperture="5.6" distance="10" k1="-1.0913865" k2="0.6160524" k3="-0.1615711" />
<vignetting model="pa" focal="9.0" aperture="5.6" distance="1000" k1="-1.0913865" k2="0.6160524" k3="-0.1615711" />
<vignetting model="pa" focal="9.0" aperture="8.0" distance="10" k1="-1.0051384" k2="0.5904174" k3="-0.1796362" />
<vignetting model="pa" focal="9.0" aperture="8.0" distance="1000" k1="-1.0051384" k2="0.5904174" k3="-0.1796362" />
<vignetting model="pa" focal="9.0" aperture="11.0" distance="10" k1="-1.0229630" k2="0.6240608" k3="-0.1962557" />
<vignetting model="pa" focal="9.0" aperture="11.0" distance="1000" k1="-1.0229630" k2="0.6240608" k3="-0.1962557" />
<vignetting model="pa" focal="9.0" aperture="16.0" distance="10" k1="-1.0408011" k2="0.6482655" k3="-0.2068316" />
<vignetting model="pa" focal="9.0" aperture="16.0" distance="1000" k1="-1.0408011" k2="0.6482655" k3="-0.2068316" />
<vignetting model="pa" focal="9.0" aperture="22.0" distance="10" k1="-1.0372164" k2="0.6337100" k3="-0.1952078" />
<vignetting model="pa" focal="9.0" aperture="22.0" distance="1000" k1="-1.0372164" k2="0.6337100" k3="-0.1952078" />
</calibration>
</lens>
```
Lens: [Laowa 9mm f/5.6 FF RL](https://www.venuslens.net/product/laowa-9mm-f-5-6-ff-rl/)

[Raw samples taken at f/5.6](https://c.gmx.net/@324516463530477224/Pck5VwTBR3iY_gGVXRj6TA). There are no Exif lens data in the raw files because it is a manual lens.

Kind regards,

Martin

**Comment by tuxfanx** [comment]
@bachrocks 
Does the lens really have a mount for Fujifilm-X or did you use an adapter?

**Comment by bachrocks** [comment]
No the lens is not available with Fujifilm X mount.
It is designed for mirrorless FF systems.
I have the Leica M mount lens and used an adapter. It is the original Fujifilm adapter.

Regards,
Martin

**Comment by tuxfanx** [comment]
@bachrocks
Thank you for the clarification.
The vignetting and distortion correction works well on your images. However, it is known that adapted wide-angle M lenses often cause image errors (color smearing) at the edges of the image, even on aps-c cameras ([read here ](https://lavidaleica.com/content/using-m-lenses-fujifilm-x-cameras)in section Performance). These image errors vary depending on the image sensor used. Without checking your data on photos taken with one of the unadapted lenses offered, I cannot transfer your correction data for vignetting and tca into the database. Unfortunately, such images are not available to me at the moment.
So I will initially only apply the correction values for the distortion and only for the mounts Nikon Z, Leica L and Sony E offered by the manufacturer. Users who use the lens via an adapter like you can [use the lensfun-add-adapter function](https://github.com/lensfun/lensfun/blob/master/docs/man/lensfun-add-adapter.1.rst) under Linux or they have to [add the mount connection](https://lensfun.github.io/manual/v0.3.1/database.html) themselve.
I hope you understand my approach.
Regards,
Joachim

**Comment by bachrocks** [comment]
OK I understand Joachim.
Just - also my distortion profile will only work for use with APS-C size sensors or APS-C crops on FF sensors. It will not work with FF sensors because all the outer part is missing!
So, the question is, does the upload make sense, at all?
What do you think?
Kind regards,
Martin

**Comment by bachrocks** [comment]
Perfect. Many thanks @tuxfanx .

Cheers,
Martin
