### ISSUE TITLE
Tamron 70-210mm F/4 Di VC USD (A034) callibration missing?

### ISSUE THREAD

**Issue by ghost** [lensfun/lensfun#2123]
Good afternoon,
I've recently bought the Tamron 70-210mm F/4 Di VC USD (A034) for my also new Nikon D7500. I've looked for that lens in the Lensfun coverage, because I use Darktable on Ubuntu, but I couldn't find it. Do I have overlooked it?
If not, do you have the possibility to add it to your list?
Thank you very much in advance.
Kind regards,
Sander

**Comment by tuxfanx** [comment]
@vdMast 
The lens is not included in the database.
For generating a lens profile we need correctly taken pictures. How to take these pictures is described [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://wilson.bronger.org/calibration). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). The calibration can then be carried out by the members of this project. The other option is to do the calibration yourself and make the data available to this project.

Here you will find some hints:
[calibration with lens_calibrate.py and taking pictures](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[calibration and taking pictures](https://wilson.bronger.org/calibration)
[video 1 calibration with Hugin](https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/)
[video 2 calibration with Hugin](https://www.youtube.com/watch?v=_p0fR-nH6cU)
[lensfuns coverage](https://wilson.bronger.org/lensfun_coverage.html)
[lensfuns database](https://github.com/lensfun/lensfun/tree/master/data/db)
[calibration with calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/)
