### ISSUE TITLE
Sigma 24mm f/1.4 DG HSM Art (APS-C Nikon mount) calibration data

### ISSUE THREAD

**Issue by Macchiato17** [lensfun/lensfun#2126]
By this request I provide the calibration data (distortion, tca) for the Sigma 24mm f/1.4 DG HSM Art lens. This lens already exists in lensfun, but just for full frame. This calibration data is intended for APS-C (shot at Nikon F AF mount).
[Sigma 24mm DG HSM Art APS-C Nikon-F.zip](https://github.com/lensfun/lensfun/files/13401036/Sigma.24mm.DG.HSM.Art.APS-C.Nikon-F.zip)

**Comment by Macchiato17** [comment]
I will try to add vignetting correction to this data within the next few days. I will update this issue accordingly.

**Comment by tuxfanx** [comment]
Could you provide a raw image?

**Comment by Macchiato17** [comment]
I'd like to, but upload here unfortunately is restricted to 25MB, zipping the RAW didn't help much 🤪

**Comment by tuxfanx** [comment]
Use the lensfun [upload server](https://wilson.bronger.org/calibration). I will find the picture there.

**Comment by Macchiato17** [comment]
OK, I just uploaded the package with a reference to this issue.
