### ISSUE TITLE
Sigma 24mm F1.4 DG HSM | A not recognized in darktable

### ISSUE THREAD

**Issue by Macchiato17** [lensfun/lensfun#2127]
The Sigma 24mm F1.4 DG HSM | A is not recognized by darktable (master, [eb2d8420]). The lens is just recognized as "126", i.e. its lens ID. Reading the meta data from the RAW with the latest version of exiftool (12.6.9.0) on Windows, it reports the following:

Lens Type: G
Lens: 24mm f/1.4
Lens Data Version: 0204
Lens ID Number: 126
Lens F Stops: 7.00
Lens ID: Sigma 24mm F1.4 DG HSM | A
Lens Spec: 24mm f/1.4 G

Seems as if it was added not too long time ago, since an older version of exiftool (12.4.4.0) I tried was not able to detect it. It would be great, if this lens may be added to the database. I provided correction data in #2126

**Comment by MStraeten** [comment]
if darktable doesn’t identify the lens you might have a look at https://github.com/darktable-org/darktable/wiki/User's-portal#my-lens-is-wrongly-identified
you need to help exiv2 to identify it correctly from raw file’s metadata 

the lens itself is in the slr-sigma.xml:
```
<model>Sigma 24mm f/1.4 DG HSM | [A] Art 015</model>
<model lang="en">Sigma 24mm f/1.4 DG HSM | A</model>
```

**Comment by Macchiato17** [comment]
Thanks so much @MStraeten, I finally managed to let darktable automatically detect that lens 🦾 

I created `%USERPROFILE%\exiv2.ini` with the following entry

    [nikon]
    126=Sigma 24mm F1.4 DG HSM | A

Apart from this, I also needed to add the correction values that I provided in #2126 to `slr-sigma.xml`, since the therein existing data is related to a crop factor of 1 and not 1.5 and thus resulting in different correction values.

**Comment by tuxfanx** [comment]
@Macchiato17
Your profile in #2126 is added to the db.
A lens issue should be created in [the exiv2 project](https://github.com/Exiv2/exiv2/issues).
Providing a picture, some informations and a link to #2126 would be necessary.
Do you want to do that?

**Comment by Macchiato17** [comment]
Thanks so much @tuxfanx for processing my request so quickly. I just raised an issue in the exiv2 project.
