### ISSUE TITLE
calibration data hosting

### ISSUE THREAD

**Issue by jonas-ott** [lensfun/lensfun#2131]
Currently, `lensfun-update-data` downloads calibration data from `https://lensfun.sourceforge.net/db/` and `https://wilson.bronger.org/lensfun-db/`. I'm not sure how those are hosted and updated, but I believe both are reliant on @bronger.

As the updates are just files hosted on a web server it would be possible to use https://lensfun.github.io for hosting. The site already updates with every new lens (make-lenslist workflow), so just building the update files and putting them in a folder would be easy.

GitHub pages have ["a soft bandwidth limit of 100 GB per month"](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)  equivalent to more than 250,000 updates (minus the normal traffic). I don't have any usage data but it feels like this should be sufficient.  

I have already played a bit with this, and if there are no objections to the idea, I could open a pr.

Edit: I have created three pull requests for doing this.

1. https://github.com/lensfun/lensfun/pull/2132 Preparation: Python script for creating the update files
2. https://github.com/lensfun/lensfun.github.io/pull/9 The workflow for generating the files and deploying the site
3. https://github.com/lensfun/lensfun/pull/2133 updating the sources in lensfun-update-data

**Comment by bronger** [comment]
Good idea! So, a job on GitHub that is triggered after every commit would update the DB files?

**Comment by jonas-ott** [comment]
Yes, so the `make-lenslist` workflow creates a commit in the lensfun.github.io repo which triggers the `pages-build-deployment` workflow. This workflow (default GitHub Pages behavior) can be replaced by a custom workflow that first builds the update files. The files would not be committed to the repo, so it doesn't grow in size.

**Comment by bronger** [comment]
I suggest to replace SourceForge with GitHub. I can continue to operate my own site as a backup, but would not object to letting it fade out over the next two or three years.
