### ISSUE TITLE
lens not detected depending on lens name

### ISSUE THREAD

**Issue by MStraeten** [lensfun/lensfun#2135]
found in darktable (https://github.com/darktable-org/darktable/issues/15934)
situation:
i created lens correction data for Canon EF 100-400mm f/4.5-5.6L IS II USM + 1.4x and added them to local lensfun database:
slr-canon.xml:
```
...
    <lens>
        <maker>Canon</maker>
        <model>Canon EF 100-400mm f/4.5-5.6L IS II USM + 1.4x</model>
        <model lang="en">Canon EF 100-400mm f/4.5-5.6L IS II USM + 1.4x</model>
        <model lang="de">Canon EF 100-400mm f/4.5-5.6L IS II USM + 1.4x</model>
        <mount>Canon EF</mount>
        <cropfactor>1</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="140" a="-0.018543" b="0.0512283" c="-0.0572633"/>
            <distortion model="ptlens" focal="189" a="-0.0083338" b="0.0157056" c="-0.0149411"/>
            <distortion model="ptlens" focal="280" a="-0.0084512" b="0.0161198" c="-0.0117873"/>
            <distortion model="ptlens" focal="420" a="-0.0069125" b="0.0173189" c="-0.0211893"/>
            <distortion model="ptlens" focal="560" a="-0.0047086" b="0.0120691" c="-0.0208262"/>
        </calibration>
    </lens>
...
```
exiv2 -pa --grep lens/i  identifies it quite ok:
```
exiv2 -pa --grep lens/i  ~/Pictures/Import_20230723/20230722-IMG_0416.CR3
Exif.Photo.LensSpecification                 Rational    4  140/1 560/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      39  EF100-400mm f/4.5-5.6L IS II USM +1.4x
Exif.CanonCs.LensType                        Short       1  Canon EF 100-400mm f/4.5-5.6L IS II USM + 1.4x
Exif.CanonCs.Lens                            Short       3  140.0 - 560.0 mm
Exif.Canon.LensModel                         Ascii     138  EF100-400mm f/4.5-5.6L IS II USM +1.4x
```

when activating lens correction, the lens is not properly detected:
`11,1025 Trouble: [Objektivkorrektur] camera/lens not found (20230722-IMG_0416.CR3 56279)`

now the strange part:

if i rename the LensType via .exiv2 file:
```
[canon]
748=an arbitrary value
```
and do the same with lensfun
```
    <lens>
        <maker>Canon</maker>
        <model>an arbitrary value</model>
``` 
it's properly detected and the correction is applied
but also ditching the blank between EF and 100-400 via .exiv2 and in slr-canon.xml  (—> „Canon EF100-400mm f/4.5-5.6L IS II USM + 1.4x“) gives a proper result ;)

any ideas?

**Comment by 4kbt** [comment]
Seems like it might have some overlap with #2052  -- the fuzzy matcher is a very strange animal, ripe for improvement.

**Comment by tuxfanx** [comment]
With RawTherapee, automatic detection is error-free.
darktable 4.8.1 claims to have recognized a Tamron lens with a 1.4x extender. To me it looks like something is wrong in darktable.
RT:
![RT](https://github.com/user-attachments/assets/87accbc4-92f1-4cde-8657-895d28a697dc)

DT:
![DT](https://github.com/user-attachments/assets/8af23bb4-6052-435a-8561-996434d3b245)

**Comment by tuxfanx** [comment]
Thanks @kmilos.
Under my Windows binary installation, darktable 4.8.1 recognizes the correct lens. Don't know which exiv2 version it was built against. However, the automatic detection by lensfun still does not work. Only after entries `[Canon]
748=EF100-400mm f/4.5-5.6L IS II USM +1.4x` in the exiv2.ini / .exiv2 files lensfun does the job under debian and windows.

@MStraeten
I would like to add your lens profile to the master database. Is it suitable for this?

**Comment by 4kbt** [comment]
Original reporter of https://github.com/lensfun/lensfun/issues/2052 here.   As you'll see in the discussion linked from an RT bug ( https://github.com/Beep6581/RawTherapee/pull/6837 ) there, RawTherapee has implemented their own workaround for at least some parsing in LensFun.

**Comment by tuxfanx** [comment]
@MStraeten
Thanks for the pictures!
