### ISSUE TITLE
Lens profiles for Affinity: Sigma 24-70 mm f/2.8 DG OS HSM Canon Art & Canon EF 70-200mm f/2.8 L IS lll USM

### ISSUE THREAD

**Issue by infofuerak** [lensfun/lensfun#2144]
I am searching for profiles for
Sigma 24-70 mm f/2.8 DG OS HSM Canon Art
Canon EF 70-200mm f/2.8 L IS lll USM
If necessary I can contribute pictures.

**Comment by tuxfanx** [comment]
For this, we need correctly taken pictures. How to take these pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://wilson.bronger.org/calibration). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). Please store the images separately for each lens in folders (distortion, tca, vignetting) and provide the file names of the images with the focal length and aperture. The calibration can then be carried out by the members of this project. The other option is to do the calibration yourself and make the data and some raw pictures for testing available to this project.

Here you will find some hints:
[calibration with lens_calibrate.py and taking pictures](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[calibration and taking pictures](https://wilson.bronger.org/calibration)
[video 1 calibration with Hugin](https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/)
[video 2 calibration with Hugin](https://www.youtube.com/watch?v=_p0fR-nH6cU)
[lensfuns coverage](https://wilson.bronger.org/lensfun_coverage.html)
[lensfuns database](https://github.com/lensfun/lensfun/tree/master/data/db)
[calibration with calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/)

**Comment by tuxfanx** [comment]
anwered --> closed
