### ISSUE TITLE
Tamron 18-400 different names

### ISSUE THREAD

**Issue by mathieui** [lensfun/lensfun#2146]
Hello, 
I am using the Tamron 18-400mm lens on a Nikon D7500, and it is not recognized in darktable because the lensfun entry is "Tamron 18-400mm f/3.5-6.3 Di II VC HLD (B028)" and the EXIF of my pictures say "Tamron AF 18-400mm f/3.5-6.3 Di II VC HLD (B028)".
I do not think those are different lenses, but I am unsure why the tests, which have apparently been done on a nikon D750, would have a different ID.
I was about to duplicate the block with a slightly different name in the db, but I am opening this issue instead in case there is a more elegant solution.

**Comment by mathieui** [comment]
> Shall we just remove the the "AF" from the exiv2 internal translation table?
> 
> It's not there in the [exiftool one](https://exiftool.org/TagNames/Nikon.html#LensID) either, and the Tamron product page also doesn't have it...
> 
> In the meantime, one could work around for darktable (or any other exiv2 client) w/ overriding the string in the [user `.exiv2`/`exiv2.ini` config file](https://exiv2.org/manpage.html#config_file).

Thanks, it seems to work indeed (though darktable seems to bake the first detected one into the xmp file, which means I have to open a new file, and also it displays as "Tamron, Tamron 18-400… etc" which looks a bit weird, but a least corrections work).

**Comment by kmilos** [comment]
> though darktable seems to bake the first detected one into the xmp file

You can force refresh the existing metadata: in lightroom, selected files on the left panel somewhere...

**Comment by tuxfanx** [comment]
@kmilos
[Here you can find pictures](https://www.dpreview.com/samples/9152094990/gallery-impressions-tamron-18-400-f3-5-6-3) taken with a Canon EOS 80D. Neither exiv2 nor exiftool lists an "AF".
We could add an "AF" in lensfun. Recognition would then work for both Id's. But a change in exiv2 would probably be better.

**Comment by kmilos** [comment]
@tuxfanx exiv2 uses different internal lens tables for Canon mount vs Nikon mount (unfortunately), and so does exiftool.

So I think we'd better remove the "AF" from the Nikon one.

**Comment by tuxfanx** [comment]
#2147 merged
