### ISSUE TITLE
Integration conflict for Mamiya 35mm f/3.5

### ISSUE THREAD

**Issue by BAGELGENESIS** [lensfun/lensfun#2155]
I do not know how to integrate my calibration data for the Mamiya 35mm f/3.5, captured on the IQ180, without conflicting with – or alternatively overwriting – the existing entry. Any advice would be appreciated.

Thanks,
BAGELGENESIS

[Mamiya 35mm.txt](https://github.com/lensfun/lensfun/files/14026947/Mamiya.35mm.txt)

**Comment by tuxfanx** [comment]
@BAGELGENESIS 
I don't think there will be a conflict.
The model name for your lens should be `<model>35mm f/22.0-3.5</model>` so there won't be a conflict with the existing lens which is `<model>Mamiya 35mm f/3.5</model>`
