### ISSUE TITLE
Support for the Panasonic LEICA DG 200mm f/2.8 Power O.I.S. lens

### ISSUE THREAD

**Issue by jaroslawmlynarczyk** [lensfun/lensfun#2170]
Please, add support for the Panasonic LEICA DG 200mm f/2.8 Power O.I.S. lens.

**Comment by CAHEK7** [comment]
@jaroslawmlynarczyk, I guess none of the developers have this lens and camera, so it would be nice to have an assistance to get some calibration pictures.

Please refer to this comment for the details:
https://github.com/lensfun/lensfun/issues/2167#issuecomment-1936068708

**Comment by tuxfanx** [comment]
answered --> closed
