### ISSUE TITLE
lensfun-update-data http.client.RemoteDisconnected

### ISSUE THREAD

**Issue by Lawrence37** [lensfun/lensfun#2174]
http://wilson.bronger.org/lensfun-db/versions.json briefly went down recently, causing the `lensfun-update-data` (v0.3.4) script to throw an error:
```
Reading http://lensfun.sourceforge.net/db/versions.json …
Reading http://wilson.bronger.org/lensfun-db/versions.json …
Traceback (most recent call last):
  File "/usr/bin/lensfun-update-data", line 136, in <module>
    read_location("http://wilson.bronger.org/lensfun-db/")
  File "/usr/bin/lensfun-update-data", line 118, in read_location
    response = urllib.request.urlopen(base_url + "versions.json")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

`http.client.RemoteDisconnected` or one of its base classes could be added to the `except` clause to print the friendly error message and continue.

Also, I noticed the https version of the URL worked. Should it be added as one of the URLs to check? Or maybe not. As I'm typing this, I noticed the http URL now returns a 301 status and redirects to the https one.

**Comment by bronger** [comment]
I had to restart the server. IMO the availability is sufficient, but surely not 100%.

**Comment by CAHEK7** [comment]
Could https://github.com/lensfun/lensfun/pull/2133 be related to this issue?

**Comment by jonas-ott** [comment]
> Could #2133 be related to this issue?

Not really, the exception could happen anyways. So this seems like the right solution: 

> http.client.RemoteDisconnected or one of its base classes could be added to the except clause to print the friendly error message and continue.

> Also, I noticed the https version of the URL worked. Should it be added as one of the URLs to check?

In `master` we use the https version, in `release_0.3.x` only http. So I think it would be good to upgrade to https.
