### ISSUE TITLE
Calibration data for Osawa MC 28mm F2.8

### ISSUE THREAD

**Issue by networkscientist** [lensfun/lensfun#2192]
Please add the attached lens data to the lensfun data base. I used a mount adapter to use this Contax/Yashica mounted lens with my Canon EOS 6D, I hope that is ok.
[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/14628104/lensfun_calibration.zip)

**Comment by sarunasb** [comment]
Please provide RAW image samples for verification.

**Comment by networkscientist** [comment]
Since I cannot upload files larger than 25MB, I uploaded the raw files I used to WeTransfer: [https://we.tl/t-uYYBF9kR1A](https://we.tl/t-uYYBF9kR1A)

**Comment by sarunasb** [comment]
Expired before I could get it.

File drop here: https://math.dartmouth.edu/nextcloud/s/Cwrpm4k9aPxBow5

**Comment by tuxfanx** [comment]
no new pictures yet --> closed
