### ISSUE TITLE
uav.xml

### ISSUE THREAD

**Issue by sbonaime** [lensfun/lensfun#2204]
Hi,
What do you think about creating an uav.xml for uav cameras ? I can do it if is accepted.

Thanks

**Comment by sbonaime** [comment]
or drone-uav or uav-drone or drone !

**Comment by sarunasb** [comment]
This would mean splitting `actioncams`, which may be not the best name, but on the other hand these files are not supposed to be dealt much with by end users. So not sure if it's worth it.
