### ISSUE TITLE
Canon EF-S 18-135mm f/3.5-5.6 IS USM vignetting calibration data

### ISSUE THREAD

**Issue by MC-DeltaT** [lensfun/lensfun#2207]
Calibration data since the lens currently only has distortion and TCA corrections available.

Uploaded here because the file size is huge: [link](https://drive.google.com/file/d/1nRJFOwRim-TM5iMHALqVz8BRG2RgFV2u/view?usp=sharing)

Camera: Canon EOS 80D

Note this camera has a slightly different crop factor than the camera that was used for the existing data - Canon EOS 7D Mark II (1.613 vs 1.605). From testing in Darktable the vignetting is improved with this data, although not perfect. Is there a way to convert the data between crop factors? If not, let me know and I can redo the distortion and TCA correction on my camera.

**Comment by tuxfanx** [comment]
@MC-DeltaT 
Attached you will find the profile I created.
Unfortunately, I don't have any normal pictures available for testing. Please test it against your photos and report back to us or provide us with relevant pictures.
The slightly different crop factors shouldn't play a role. Their difference is far too small.
You only took pictures at 5 focal lengths. May be 6-7 focal lengths would have been better (e.g. 18, 22, 29, 35, 50, 85, 135mm). However, you could have saved yourself some pictures at the high aperture numbers. Please read [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") how the pictures should be taken.
[Canon_EF-S_18-135mm_f__5-5.6_IS_USM.zip](https://github.com/lensfun/lensfun/files/14889121/Canon_EF-S_18-135mm_f__5-5.6_IS_USM.zip)

**Comment by MC-DeltaT** [comment]
Thanks for the data. I have attached some test images. By my eye, looks like the vignetting is significantly, but not completely, corrected. I'm happy with it though :)

> May be 6-7 focal lengths would have been better

I had read that article, but only saw that it says to do 5 focal lengths. Might it be possible to update the article?

[test_images.zip](https://github.com/lensfun/lensfun/files/14893393/test_images.zip)

**Comment by tuxfanx** [comment]
Thanks for your answer.
A correction that is a little too weak is definitely better than a correction that is a little too strong. I will copy the values into the db.
Five focal lengths with 5 aperture stops each are sufficient for most zoom lenses, that's correct. For lenses with a wide zoom range, it can sometimes make sense to add a few more focal lengths.
