### ISSUE TITLE
increase devignetting by multiple execution

### ISSUE THREAD

**Issue by ethpi** [lensfun/lensfun#2225]
Is it possible to execute the devignetting multiple times?

Background:

When using my Nikon AF-S DX Nikkor 35mm f/1.8G on my Nikon D850, unsurprisingly the corners are dark. I created a correction-file (below) for distortion and devignetting. By using this file with darktable, the corners get a little more light but are still shaded.  I tried multiple instances of the  lenscorrection module in darktable (only activated devignetting). The results for close shots with focus 1.8 are really good. I packed this four instances of the lens correction module in a darktable style. Now I can use the devignetting with one click. Works so far so good.

But it would be much easier, if I could tell lensfun to execute the devignetting multiple times. Or is it possible to increase the devignetting by manipulating the data in the XML-file below?

```
<lensdatabase>
    <lens>
        <maker>Nikon</maker>
        <model>Nikon AF-S DX Nikkor 35mm f/1.8G</model>
        <mount>Nikon F</mount>
        <cropfactor>1.0</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="35.0" a="0.014" b="-0.038" c="-0.007" />
            <vignetting model="pa" focal="35.0" aperture="1.8" distance="10" k1="-1.2784482" k2="0.6235737" k3="-0.2436129" />
            <vignetting model="pa" focal="35.0" aperture="1.8" distance="1000" k1="-1.2784482" k2="0.6235737" k3="-0.2436129" />
            <vignetting model="pa" focal="35.0" aperture="2.5" distance="10" k1="-0.6705844" k2="-0.3964637" k3="0.1970925" />
            <vignetting model="pa" focal="35.0" aperture="2.5" distance="1000" k1="-0.6705844" k2="-0.3964637" k3="0.1970925" />
            <vignetting model="pa" focal="35.0" aperture="4.0" distance="10" k1="-0.1280667" k2="-0.5287182" k3="-0.0464113" />
            <vignetting model="pa" focal="35.0" aperture="4.0" distance="1000" k1="-0.1280667" k2="-0.5287182" k3="-0.0464113" />
            <vignetting model="pa" focal="35.0" aperture="7.1" distance="10" k1="-0.3911368" k2="0.5074879" k3="-0.9777071" />
            <vignetting model="pa" focal="35.0" aperture="7.1" distance="1000" k1="-0.3911368" k2="0.5074879" k3="-0.9777071" />
            <vignetting model="pa" focal="35.0" aperture="11.0" distance="10" k1="-0.7352206" k2="1.7200735" k3="-1.9041305" />
            <vignetting model="pa" focal="35.0" aperture="11.0" distance="1000" k1="-0.7352206" k2="1.7200735" k3="-1.9041305" />
            <vignetting model="pa" focal="35.0" aperture="16.0" distance="10" k1="-0.2688632" k2="-0.0608769" k3="0.0771672" />
            <vignetting model="pa" focal="35.0" aperture="16.0" distance="1000" k1="-0.2688632" k2="-0.0608769" k3="0.0771672" />
            <vignetting model="pa" focal="35.0" aperture="22.0" distance="10" k1="-0.9870593" k2="2.6504873" k3="-2.6356322" />
            <vignetting model="pa" focal="35.0" aperture="22.0" distance="1000" k1="-0.9870593" k2="2.6504873" k3="-2.6356322" />
        </calibration>
    </lens>
</lensdatabase>

```

**Comment by tuxfanx** [comment]
@ethpi 
If the workflow for the calibration process was carried out correctly, multiple devignetting runs should not be necessary at all. As far as I know, Lensfun doesn't offer such a function either.
My suggestion would be to [create the calibration profile](https://wilson.bronger.org/lens_calibration_tutorial/) again[ using the calibrate.py script](https://github.com/lensfun/lensfun/tree/master/tools/calibrate) or [upload your images here](https://wilson.bronger.org/calibration) to use lensfuns calibration service.
There already exist a profile for the lens [in the database](https://wilson.bronger.org/lensfun_coverage.html) with distortion and TCA correction data.

**Comment by tuxfanx** [comment]
answered --> closed
