### ISSUE TITLE
Calibration for Canon Lens RF-S55-210mm F5-7.1 IS STM

### ISSUE THREAD

**Issue by crispyapple** [lensfun/lensfun#2238]
I am new to this, so I am not sure if this is where I request adding a lens. I did not see the Canon Lens RF-S55-210mm F5-7.1 IS STM as a lens option for lens correction.

Thanks!

**Comment by sarunasb** [comment]
To add a lens one would need calibration data, which can be obtained from suitable images. Please take a look at 
https://lensfun.github.io/calibration/
and see whether you can provide such images and maybe even do the calibration as well.
