### ISSUE TITLE
What's the best way to obtain a precise correction?

### ISSUE THREAD

**Issue by AprentiUnity** [lensfun/lensfun#2243]
I have a Canon RF 24-50mm f4.5/6.3 IS STM mounted on a Canon R8 and there is no correction profile for this lens. I would be very grateful if someone could add the profile. This lens is the best kit lens sold with the Canon R8 and I think a correction profile would benefit many photographers. In case nobody owns this lens, I am willing to take the pictures to create the profile. I also came across this tutorial on how to create your own correction profile https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/.
Does this tutorial still work?
Is this still the way to get the best correction?
Is it easier for you if I find the values myself and make a pull request or if I send you the raws so that you can create the profile yourself?
Thanks in advance

**Comment by sarunasb** [comment]
It is easier if you calibrate yourself and provide 1) corrections as Lensfun XML; 2) images to check correction (share on the web). 

Please check https://lensfun.github.io for how to take suitable images and how then to derive calibration data.
