### ISSUE TITLE
lens not automatically recognized when using the lens correction module in darktable

### ISSUE THREAD

**Issue by urukai1968** [lensfun/lensfun#2250]
Hello, I am using darktable to develop my RAW photos, I have found that it does not recognize my nikon 70-300 lens.
Running exiv2 shows the output "Nikon AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR", while the name that appears in darktable is "Nikon AF-P Nikkor 70-300mm f/4.5-6.3G DX ED VR", the only difference is the position in the letters DX and I think this may be the reason why darktable does not correctly recognize my lens.
I don't know if the problem is with darktable or lensfun, so I sent this message to both bug fixing systems.
Darktable older versions had same bug

My versions are the following:
OS Debian Bookworm
Package: liblensfun-data-v1
Version: 0.3.3-1
Package: exiv2
Version: 0.27.6-1
Darktable 4.8 app image

Thank you

**Comment by sarunasb** [comment]
Please share a sample raw image to test.

**Comment by urukai1968** [comment]
Hello, I have realized that the difference is not just the letters DX, many more letters change, uppercase, lowercase, etc.
I have done the Darktable comment thing and it still doesn't work.

user@sobremesa:$ cat /home/user/.exiv2
[nikon]
163=NIKKOR AF-P 70-300mm f/4.5-6.3G DX ED VR

The output of exiv2 with the modified .exiv2 file is
user@sobremesa:$ exiv2 -pt ../nef/DSC_3380.NEF | grep -ai lens
Exif.Nikon3.LensType Byte 1 D G VR
Exif.Nikon3.Lens Rational 4 70-300mm F4.5-6.3
Exif.Nikon3.LensFStops Undefined 4 4.66667
Exif.NikonLd3.LensIDNumber Byte 1 NIKKOR AF-P 70-300mm f/4.5-6.3G DX ED VR
Exif.NikonLd3.LensFStops Byte 1 F4.7

Unmodified ,exiv2
user@sobremesa:~$ exiv2 -pt ../nef/DSC_3380.NEF | grep -ai lens
Exif.Nikon3.LensType Byte 1 D G VR
Exif.Nikon3.Lens Rational 4 70-300mm F4.5-6.3
Exif.Nikon3.LensFStops Undefined 4 4.66667
Exif.NikonLd3.LensIDNumber Byte 1 Nikon AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR
Exif.NikonLd3.LensFStops Byte 1 F4.7

RAW file
https://drive.google.com/file/d/1mkmvRwigRhhOJ7B_Z6UX5qYJHqdQWMAP/view?usp=drive_link
Screenshoot 
https://drive.google.com/file/d/1KHU38vUThyci2umMdbTOPZxyH2Uq299N/view?usp=sharing

If you need anything else, don't hesitate to ask, thank you.

**Comment by sarunasb** [comment]
There should be no need for `.exiv2` in this case, unless indeed there is an issue with locale dependent decimal separator and settings in `.exiv2` can somehow address that.

In my tests darktable matches the correct lens automatically for your sample image. darktable 4.6 and 4.8, Ubuntu and Fedora, all standard distribution packages. As indeed it should be, because for Lensfun matching algorithm strings
```NIKKOR AF-P 70-300mm f/4.5-6.3G DX ED VR```
and
```AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR```
are identical.

Also searching Lensfun database with `lenstool`:
```$ lenstool -L 'Nikon AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR'
Matching lens found in the database:
  Nikon / NIKKOR AF-P 70-300mm f/4.5-6.3G DX ED VR
    |- Crop factor: 1.534
    |- Aspect ratio: 1.5
    |- Focal: 70-300mm
    |- Min-Aperture: f/4.5
    |- Center: 0,0
    |- Compatible mounts: Nikon F AF, 
    |- Calibration data: tca, vign, dist,```

**Comment by urukai1968** [comment]
Well, I already know what the problem was, I had imported these photos when that lens was not supported with the software versions I had installed, now when I refresh the EXIF ​​data darktable automatically recognizes the lens.

Thanks problem solved
