### ISSUE TITLE
Add OM System 150-600mm f/5-6.3 IS Lens

### ISSUE THREAD

**Issue by mlouielu** [lensfun/lensfun#2254]
Hi there,

I would like to know how to add new lens (OM System 150-600mm f/5-6.3 IS Lens) into the database? Should I run through the calibration process, or add it into the XML first?

Thanks!

**Comment by tuxfanx** [comment]
For this, we need correctly taken pictures. How to take these pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://wilson.bronger.org/calibration). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). Please store the images separately for each lens in folders (distortion, tca, vignetting) and provide the file names of the images with the focal length and aperture. The calibration can then be carried out by the members of this project. 
The better option is to do the calibration yourself and make the data and some raw pictures for testing available to this project.

Here you will find some hints:
[calibration with lens_calibrate.py and taking pictures](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[calibration and taking pictures](https://wilson.bronger.org/calibration)
[video 1 calibration with Hugin](https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/)
[video 2 calibration with Hugin](https://www.youtube.com/watch?v=_p0fR-nH6cU)
[lensfuns coverage](https://wilson.bronger.org/lensfun_coverage.html)
[lensfuns database](https://github.com/lensfun/lensfun/tree/master/data/db)
[calibration with calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/)

**Comment by mlouielu** [comment]
@tuxfanx thanks for the reply!

I have another question, does the camera body affect the calibration result? Did the underlying calibration software use latest rawspeed (or I can build it by myself?), since my camera body has a newer RAW format that just landed in rawspeed month ago.

**Comment by mlouielu** [comment]
Another question: since I'm trying to calibrate a super-tele lens, is it OK for me to print a grid and use it as a reference, or use a Zeiss chess board as a reference?

**Comment by tuxfanx** [comment]
@mlouielu 
If the calibration with the raw pictures does not work then you can try to work with converted dng's.
Using a grid should be ok if the shooting distance is sufficient.
