### ISSUE TITLE
Calibration data for Samsung EX2F (manual upload)

### ISSUE THREAD

**Issue by ge0rg** [lensfun/lensfun#2255]
Hi,

over the last two months, I've tried multiple times to upload the Samsung EX2F raw pictures using the official upload service, but I never got a confirmation email, and they never materialized here. 

I've shot raw pictures according to the instructions and uploaded them to https://op-co.de/tmp/ex2f-lens-calibration.tar.gz - it would be great if somebody in the know could have a look at them and create a corresponding lens profile.

Thanks very much!

**Comment by tuxfanx** [comment]
The EXIF ​​data of your images do not contain the  required real focal length values. It only contains the equivalent values ​​based on the 35mm format.

**Comment by ge0rg** [comment]
Thanks for looking into the files. Looks like there is a bug in the EX2F raw file encoder, the actual focal length is present in the JPG files:

```
File Name                       : SAM_0153.JPG
Focal Length                    : 5.2 mm (35 mm equivalent: 24.0 mm)
File Name                       : SAM_0154.JPG
Focal Length                    : 6.7 mm (35 mm equivalent: 31.0 mm)
File Name                       : SAM_0155.JPG
Focal Length                    : 8.0 mm (35 mm equivalent: 37.0 mm)
File Name                       : SAM_0156.JPG
Focal Length                    : 9.8 mm (35 mm equivalent: 45.0 mm)
File Name                       : SAM_0157.JPG
Focal Length                    : 12.3 mm (35 mm equivalent: 57.0 mm)
File Name                       : SAM_0158.JPG
Focal Length                    : 15.1 mm (35 mm equivalent: 70.0 mm)
File Name                       : SAM_0159.JPG
Focal Length                    : 17.3 mm (35 mm equivalent: 80.0 mm)
```

The file numbers correspond to the SRWs I uploaded. I'm running the latest firmware that was made available by Samsung, 303194, so I suppose we will not get this fixed. But maybe there is a way to get the actual focal length values from some manufacturer-specific EXIF fields?

**Comment by tuxfanx** [comment]
Pictures with correct exif data ara needed

**Comment by ge0rg** [comment]
I've "corrected" the values by running the files through `exiftool -tagsFromFile %f.JPG -FocalLength -FieldOfView SAM_*.SRW` - they now have correct EXIF focal length data. It's also possible to correct the `FocalLength` tag without the respective JPG, based on the (correctly stored) `FocalLengthIn35mmFormat` in the SRW, but it requires two exiftool calls per file as exiftool can't do float math on tag values:

```sh
for fn in *.SRW ; do
    exiftool -FocalLength=$(($(exiftool -b -FocalLengthIn35mmFormat "$fn")/4.6)) "$fn"
done
```

The new archive is available under https://op-co.de/tmp/ex2f-lens-calibration-focus-corrected.zip

Should I open a new issue or would you kindly re-open this one?

**Comment by tuxfanx** [comment]
[done](https://github.com/lensfun/lensfun/commit/09b2b6caf23afb6567bdddceb63c4e260a4e8db7)
