### ISSUE TITLE
I need calibration advice

### ISSUE THREAD

**Issue by AprentiUnity** [lensfun/lensfun#2259]
I captured photos to calibrate the distortion of a lens. The lines in the image are perfectly straight but not perfectly parallel to the horison line. Could this be a problem?

**Comment by tuxfanx** [comment]
I think, small deviations should not be a problem if the two lines are parallel to each other and the upper or lower line is positioned close enough to the edge of the image. [Read here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) and[ here](https://wilson.bronger.org/calibration/target_tips)

**Comment by AprentiUnity** [comment]
Ok thx I will try
