### ISSUE TITLE
Fujifilm XF 150-600mm not recognized

### ISSUE THREAD

**Issue by Meganynt** [lensfun/lensfun#2261]

**Comment by tuxfanx** [comment]
For this, we need correctly taken pictures. How to take these pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/) and [here](https://wilson.bronger.org/calibration). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). Please store the images separately for each lens in folders (distortion, tca, vignetting) and provide the file names of the images with the focal length and aperture. The calibration can then be carried out by the members of this project. The other option is to do the calibration yourself and make the data and some raw pictures for testing available to this project.
