### ISSUE TITLE
Lens Profile for Sigma 100-400mm f/5-6.3 DG DN OS | C lens

### ISSUE THREAD

**Issue by Javernus** [lensfun/lensfun#2271]
I own a Sigma 100-400mm f/5-6.3 DG DN OS | C lens and would like to have a proper lens profile for it. I will try to create suitable test photos soon. To that regard, I have some questions.

I understand I will need to take at least 5 pictures of varying focal lengths. Should I equally subdivide it (100, 175, 250, 325, 400) or does it not matter too much? I suppose I can also take more pictures, since the range is quite large.

Also, does it matter which aperture I shoot at? I have access to a tripod, so I can compensate higher f-stops with slower shutter speed. 

Finally, I have IBIS and lens OS. Do I keep them on, turn one or both of them off, or provide pictures with a subset of options?

Thanks in advance!

**Comment by tuxfanx** [comment]
How to take the pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/), [here](https://wilson.bronger.org/calibration) and [here](https://wilson.bronger.org/calibration/target_tips).
Images with 6-7 different focal lengths should be sufficient.
For distortion correction, ideally an image should be included with a focal length at which the distortion changes from pincushion shape to barrel shape.

**Comment by tuxfanx** [comment]
answered--> closed
