### ISSUE TITLE
Profile request 24mm F3.5 DG DN Contemporary

### ISSUE THREAD

**Issue by j4r3kb** [lensfun/lensfun#2274]
https://www.sigma-global.com/en/lenses/c021_24_35/

**Comment by tuxfanx** [comment]
@j4r3kb 
For that, correctly taken pictures have to be taken with the lens.
How to take the pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/), [here](https://wilson.bronger.org/calibration) and [here](https://wilson.bronger.org/calibration/target_tips).

**Comment by Andries-B** [comment]
A couple of hours ago, I took some calibration photos with this lens. I'm planning to submit my files to the project in the propper way. In the mean time, here is the preliminary xml-code that should go in "mil-sigma.xml":
```
    <lens>
        <maker>Sigma</maker>
        <model>24mm F3.5 DG DN | Contemporary 021</model>
        <mount>Leica L</mount>
        <mount>Sony E</mount>
        <cropfactor>1.0</cropfactor>
        <calibration>
            <!-- Taken with Lumix S5 high res mode, 2024-08-21 -->
            <distortion model="ptlens" focal="24" a="0.0187798" b="-0.0331216" c="0.0146341"/>
            <tca model="poly3" focal="24" br="0.0000007" cr="-0.0000901" vr="1.0003918" bb="-0.0001195" cb="0.0003470" vb="0.9997972"/>
        </calibration>
    </lens>

```

**Comment by tuxfanx** [comment]
Thanks!
