### ISSUE TITLE
Please add model name for Tamron mil-tamron.xml 

### ISSUE THREAD

**Issue by JimKnopfIoT** [lensfun/lensfun#2292]
I'm not sure how a pull request works. Thats why i'm open an issue.
I bought the TAMRON 150-500mm F/5-6.7 Di III VC VXD A057Z lense for my Nikon Z8 Camera. 
The lense is in the mil-tamron.xml file for Sony E mount.
The lense is not autoselected in darktable. No Camera/Lense found. When i search for A057 in a RAW image file i get this info:
```
grep -a A057 DSC_4164.NEF
���dTAMRON 150-500mm F/5-6.7 Di III VC VXD A057Z31000281  NikonIIQ021�
```

I had to add the following two lines to get the lense calibration working in darktable. 
I added line number 512 and 514 in the mil-tamron.xml.
```
512 + <model>150-500mm F/5-6.7 Di III VC VXD A057Z</model>
514 + <model lang="en">Tamron 150-500mm F5-6.7 Di III VC VXD (A057Z)</model>
```
Please complete the mil-tamron.xml file with the two lines.

**Comment by tuxfanx** [comment]
@JimKnopfIoT 
Only one `<model>` line is allowed in the lens profiles.
`<model lang=en>` is only for your eyes
The profile was created with images from a Sony camera. It is most likely an EXIF ​​data problem. Please provide us with one raw image [here](https://wilson.bronger.org/calibration) and refer to this issue in the comment field.
I will then look at what needs to be changed.
