### ISSUE TITLE
Multiple distortion models defined

### ISSUE THREAD

**Issue by jsmucr** [lensfun/lensfun#2304]
In Darktable, this errror keep popping up in the console output several times a second:
```
** (darktable.exe:23732): WARNING **: 11:02:43.563: [Lensfun] lens Panasonic/Leica DG 12-60mm f/2.8-4.0 has multiple distortion models defined
```
I'm not quite sure what to do about it, but I've tried to compile DT myself after upgrading the local Lensfun database, and the error is still there.

**Comment by tuxfanx** [comment]
Yes, there are actually 2 different models entered for the distortion. The poly3 model is used for the 60mm focal length and ptlens for the others. But darktable has no problems with this for me and corrects the images in the right way without such error messages. 
To get rid of the error message in a first step, you can try to change the poly3 model to ptlens model in the mil-panasonic.xml file of your lensfun database:

 ```
<lens>
        <maker>Panasonic</maker>
        <model>Leica DG 12-60mm f/2.8-4.0</model>
        <model lang="en">Leica DG Vario-Elmarit 12-60mm f/2.8-4.0 Asph. Power OIS</model>
        <mount>Micro 4/3 System</mount>
        <cropfactor>2</cropfactor>
        <aspect-ratio>4:3</aspect-ratio>
        <calibration>
            <!-- Taken with E-M10 II -->
            <distortion model="ptlens" focal="12" a="0.02423" b="-0.07869" c="-0.01266"/>
            <distortion model="ptlens" focal="20" a="0.00423" b="-0.01585" c="0.00894"/>
            <!-- Taken with Panasonic DMC-GH5 -->
            <distortion model="ptlens" focal="25" a="0" b="0.00247064" c="0"/>
            <distortion model="ptlens" focal="40" a="0" b="0.00512035" c="0"/>
            <distortion model="ptlens" focal="50" a="0" b="0.00367001" c="0"/>
            <!--<distortion model="poly3" focal="60" k1="0.0030586"/> -->
            <distortion model="ptlens" focal="60" a="0" b="0.0030586" c="0"/>
```

**Comment by tuxfanx** [comment]
Yes, the profile is a little unusual and I think I will change it in the master db as well.

**Comment by jsmucr** [comment]
Thank you! It actually stopped my DT Windows build from crashing due to some glibc assertion. :-)
