### ISSUE TITLE
Calibration data for Panasonic Leica DG Vario-Elmarit 12-60mm f/2.8-4.0 Asph. Power OIS

### ISSUE THREAD

**Issue by Andries-B** [lensfun/lensfun#2316]
Please add the attached lens data to the lensfun data base.

Github message: "File size too big: 25 MB are allowed, 47 MB were attempted to upload." I will send the calibration file using the calibration upload service.

Please note 1: the database already has a calibration profile for this lens. However, recently there has been an issue with that: see https://github.com/lensfun/lensfun/issues/2304 . This uploaded profile is a complete profile using one distortion model.

Note 2: The lens has been calibrated for many focal lengths: the lengths that are marked on the lens (12, 18, 25, 40, 50, 60) and 23mm and 32mm. 23mm and 32mm are included, because the lens has barrel distortion in the range from 12mm to 23mm, pincushion from 32mm to 60mm.

Note 3: Visual comparing this profile with the already existing profile in the database, the differences are minor, but I think this new one is slightly more accurate.

**Comment by tuxfanx** [comment]
Thank you for your efforts to improve the lensfun database!
I will adopt your profile. In my opinion, it is a little better than the old one. 
Could it be that in the focal length range of 12-18mm the vignetting correction is a little too strong (the right and left edges of the image appear a little too bright in your pictures)?
Did you take the pictures for calibration under artificial lighting or against an evenly overcast and illuminated sky? Sometimes it helps if you do not take the pictures for the critical focal length ranges at a focal length of infinity. A vignetting correction that is a little too weak is always better than a correction that is too strong.

**Comment by Andries-B** [comment]
You're welcome and ofcourse thank you all for the good work!
For calibration images, I always use natural daylight. Maybe the vignetting correction is a bit to strong at the wider focal lengths, because of the area where these were shot: no open enough. I will re-do these shots, find a better place, wait for the right weather/light. However, the weather forecast here for the next days is sunny (!), so have to wait for worse weather and better light.
