### ISSUE TITLE
Vignetting for NIKKOR Z 180-600mm f/5.6-6.3 VR

### ISSUE THREAD

**Issue by wgoetz** [lensfun/lensfun#2325]
Many hurdles...

https://gitlab.com/cryptomilk/lens_calibrate.git  PdfFileMerger->PdfMerger (see issue No 6)

gh upload: tar.xz not supported, additionally gzip'd to circumvent this ... but:
File size too big: 25 MB are allowed, 37 MB were attempted to upload.

here the gzip'd lensfun.xml

[lensfun.xml.gz](https://github.com/user-attachments/files/17104317/lensfun.xml.gz)

kr 
Wolfgang

https://github.com/lensfun/lensfun/issues/2205

**Comment by tuxfanx** [comment]
To create profiles, I recommend using [the script calibrate.py](https://github.com/lensfun/lensfun/tree/master/tools/calibrate) by [T. Bronger](https://wilson.bronger.org/lens_calibration_tutorial/). I have had the case several times now that profiles created with the lens_calibrate.py script resulted in a too weak correction of the vignetting.

And please, we need some normal raw shots on which we can test your vignetting data.
Normal taken Pictures of evenly lit, colored surfaces with little structure (e.g. brick walls, garage doors, etc.) are best suited for this. 2-3 raw images in focus and taken with the wider focal length settings would be sufficient. [Here you can upload the pictures](https://wilson.bronger.org/calibration). Please refer to this issue in the comment field.

**Comment by wgoetz** [comment]
Here the lensfun.xml using calibrate.py: (line 14 changed to:   from scipy.optimize import leastsq)

[lensfun.xml.gz](https://github.com/user-attachments/files/17119450/lensfun.xml.gz)


**lens_calibrate.py**
![lens_calibrate.py](https://github.com/user-attachments/assets/83c62c42-eacd-4602-8763-9e0888b8aaac)

**calibrate.py**
![calibrate.py](https://github.com/user-attachments/assets/9676d663-b32b-4f2e-9629-2a66b44ce10f)

**no correction**
![no_coorection](https://github.com/user-attachments/assets/a4e8c962-f2c2-4415-b871-255c1e9f3f29)

**Comment by tuxfanx** [comment]
@wgoetz 
Thanks for the pictures and your efforts!
merge [32dda1f](https://github.com/lensfun/lensfun/commit/32dda1f20a0684f73954a6ee915b628e10658a92)
