### ISSUE TITLE
Add Leica Q3 43 including calibration data for Leica APO-Summicron 43mm f/2 ASPH.

### ISSUE THREAD

**Issue by Andries-B** [lensfun/lensfun#2347]
Please add the attached lens data to the lensfun data base.

Leica Q3 43 has a fixed lens Leica APO-Summicron 43mm f/2 ASPH. The dataset includes both the camera Leica Q3 43 and the lens data. Leica Q3 43 is different from Leica Q3, which has a fixed 28mm lens.

[lensfun_calibration.tar.gz](https://github.com/user-attachments/files/17412647/lensfun_calibration.tar.gz)

**Comment by sarunasb** [comment]
Thank you for contributing. Leica Q3 43 and its lens added to Lensfun.
