### ISSUE TITLE
Update Exiv2 : Sigma 30mm F1.4 DC DN | Contemporary 016

### ISSUE THREAD

**Issue by chris-hld** [lensfun/lensfun#235]
https://github.com/lensfun/lensfun/commit/8280f580d8edff586789e031270aa19ab96eba92
The exiv2 information for this lens is actually
`30mm F1.4 DC DN | Contemporary 016`
from
`Exif.Photo.LensModel                         Ascii      35  30mm F1.4 DC DN | Contemporary 016`

>        <maker>Sigma</maker>
>        <model>30mm F1.4 DC DN | Contemporary 016</model>
>        <model lang="en">30mm f/1.4 DC DN</model>
>        <mount>Sony E</mount>
>        <mount>Micro 4/3 System</mount>

This way e.g. darktable finds it.

**Comment by bronger** [comment]
Thank you for the report!
