### ISSUE TITLE
Exiv2/lensfun ID string mismatch for "Sigma 12-24mm F4.5-5.6 EX DG Aspherical HSM"

### ISSUE THREAD

**Issue by dakhubgit** [lensfun/lensfun#2350]
Exiv2 reports my lens as "Sigma 12-24mm F4.5-5.6 EX DG Aspherical HSM" while lensfun knows this lens without the word "Aspherical" in its string.  That results in RawTherapee not recognizing it.

It would be nice if lensfun supported adding aliases to the DB to avoid copying whole entries.

**Comment by tuxfanx** [comment]
@dakhubgit
Please [upload a raw image for us here](https://wilson.bronger.org/calibration) and refer to this issue in the comment.

**Comment by dakhubgit** [comment]
I can corroborate that after the action taken on upload #2367 (and updating the lens database), RawTherapee on my computer recognizes photographs taken with that lens on a Nikon camera without requiring assistance by a custom `~/.exiv2` file.
