### ISSUE TITLE
Request addition of the Canon RF 200-800mm F6.3-9 IS USM lens to the lens correction database.

### ISSUE THREAD

**Issue by eldoradobirds** [lensfun/lensfun#2361]
Am using Darktable in Ubuntu 22.04 and for photos that use the Canon RF 200-800 F6.3-9 IS USM lens the tool reports 'camera/lens not found'.  I referred to the list of supported lenses and cameras.  The camera is there (Canon EOS R7) but the lens (Canon RF 200-800 F6.3-9 IS USM) is not.  I have done 'sudo lensfun-update-data' and am using version 4.8.1 of Darktable.  I referred the list of supported lenses at https://lensfun.github.io/lenslist/.

**Comment by tuxfanx** [comment]
@eldoradobirds 
To create a lens profile at first we need correctly taken pictures. How to take the pictures is described [here ](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures") and partly also [here](https://wilson.bronger.org/lens_calibration_tutorial/), [here](https://wilson.bronger.org/calibration) and [here](https://wilson.bronger.org/calibration/target_tips). The images can then be [uploaded from this website](https://wilson.bronger.org/calibration). Please store the images separately for each lens in folders (distortion, tca, vignetting) and provide the file names of the images with the focal length and aperture. The calibration can then be carried out by the members of this project. The other option is to do the calibration yourself and make the data and some raw pictures for testing available to this project.

Here you will find some hints:
[calibration with lens_calibrate.py and taking pictures](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
[calibration and taking pictures](https://wilson.bronger.org/calibration)
[How anti-distortion images should look like](https://wilson.bronger.org/calibration/target_tips)
[video 1 calibration with Hugin](https://kameratrollet.se/create-your-own-lens-correction-data-for-lensfun/)
[video 2 calibration with Hugin](https://www.youtube.com/watch?v=_p0fR-nH6cU)
[lensfuns coverage](https://wilson.bronger.org/lensfun_coverage.html) **current status**
[lensfuns database](https://github.com/lensfun/lensfun/tree/master/data/db)
[calibration with calibrate.py](https://wilson.bronger.org/lens_calibration_tutorial/)

**Comment by eldoradobirds** [comment]
Could a pattern printed on paper be used for distortion and chromatic aberration?  Black horizontal lines printed on white paper for distortion and a grid of black lines on white paper for chromatic aberration.  Not sure if I'll be able to find a suitable building nearby.  If the paper pattern method is feasible seems like it would be simpler, could be done at home, and not require asking permissions to photograph buildings on private property.

**Comment by tuxfanx** [comment]
It is possible to use a grid on paper. However, [as described here](https://wilson.bronger.org/lens_calibration_tutorial/), you should take your pictures being at least 8 meters away from the grid.

**Comment by eldoradobirds** [comment]
Thanks, since the lens is a telephoto I thought the printed paper method would be feasible.  I do understand you'd need something like the side of a building for other lenses especially wide angle lenses.  Will update the ticket once I have uploaded images at https://wilson.bronger.org/calibration.
