### ISSUE TITLE
Request addition of the Canon RF 600mm F11 IS STM lens to the lens correction database.

### ISSUE THREAD

**Issue by eldoradobirds** [lensfun/lensfun#2362]
Looks like the Canon RF 800mm F11 IS STM lens is in the lens correction database but not its smaller cousin the Canon RF 600mm F11 IS STM lens.  For photos with this lens (Canon RF 600mm F11 IS STM) I get 'camera/lens is not supported'.  My camera is there (Canon EOS R7) but not the lens. Am using Darktable 4.8.1 and have done sudo lensfun-update-data.  I referred the list of supported lenses at https://lensfun.github.io/lenslist/.

**Comment by tuxfanx** [comment]
@eldoradobirds 
see #2361

**Comment by tuxfanx** [comment]
answered --> closed
