### ISSUE TITLE
Canon RF600 & RF200-800 corrections for fullframe taken with APS-C camera

### ISSUE THREAD

**Issue by MStraeten** [lensfun/lensfun#2389]
Corrections for Canon RF 200-800mm F6.3-9 IS USM and Canon RF 600mm F11 IS STM were taken with an APS-C camera, so cropfactor 1.0 isn't correct.
https://github.com/lensfun/lensfun/commit/03b3d2f137f2a8d5c2ae055d3b6e54a777dec151
https://github.com/lensfun/lensfun/commit/f3130a5a97dd09b2dfa1738be0d2453deda31451

so better change cropfactor ...

**Comment by tuxfanx** [comment]
...done --> closed
