### ISSUE TITLE
Honor 6A vignetting

### ISSUE THREAD

**Issue by falket** [lensfun/lensfun#251]
I have tried to calibrate my phone (Honor 6A) for vignetting since it's quite extreme (despite this, the phone and the camera are really nice imho!). I attach the xml, at least the values inside <vignetting> tags are ok, for maker and model i've copied from jpeg exif, cropfactor calculated using 28mm/3.4mm, aspect ratio is 4:3 . The dng is generated with open camera open source camera app.

The jpeg is autocorrected.

Files (jpeg, dng and generated lensfun.xml) here: https://drive.google.com/open?id=0B322LUNWP_FWcGNpNVJsN1p3SGs

Thank you in advance.

<lensdatabase>

    <lens>
        <maker>HUAWEI</maker>
        <model>DLI-L22</model>
        <mount><mount></mount>
        <cropfactor>7,77</cropfactor>
        <type>4:3</type>
        <calibration>
            <distortion model="ptlens" focal="3.4" a="0" b="0" c="0" />
            <vignetting model="pa" focal="3.4" aperture="2.2" distance="10" k1="-2.3342" k2="2.8667" k3="-1.3321" />
            <vignetting model="pa" focal="3.4" aperture="2.2" distance="1000" k1="-2.3342" k2="2.8667" k3="-1.3321" />
        </calibration>
    </lens>

</lensdatabase>

**Comment by bronger** [comment]
Have you actually tested this data?  I ask because this XML is invalid.  It will not work with Lensfun.

Does this phone have only one aperture?  This may well be, I just ask.

**Comment by falket** [comment]
I haven't been able to make it work.

Like most phone, it hasn't a real iris and works only at full-wide aperture. If you follow the link you can find the dng and the jpeg (or if you want i can upload them to the calibrating page).

Thank you.

**Comment by falket** [comment]
I have tried again with the last version of calibrate.py from http://wilson.bronger.org/lens_calibration_tutorial/ , but still the dng is not recognized. I have created a vignetting directory, with the dng inside (with Fuji 10-24mm vignetting files, i did the same and it worked without troubles, i checked the result and they are great ;) ).

Then i've called 

$ calibrate.py
I wrote a template lenses.txt.  Please fill this file with proper information.  Abort.

But the lenses.txt look this way:

# No RAW images found.  Please have a look at
# http://wilson.bronger.org/lens_calibration_tutorial/

If i run calibrate.py again, i obtain this message:

$ calibrate.py
Traceback (most recent call last):
  File "/usr/local/bin/calibrate.py", line 330, in <module>
    exif_data = file_exif_data[os.path.join(vignetting_directory, filename)] + (distance,)
KeyError: 'vignetting/IMG_20171028_210149.dng'

Thank you again.

**Comment by bronger** [comment]
The message “No RAW images found” is generates if no focal lengths were found. Does exiv2 find focal lenghts in your DNGs?  If there are no privacy concerns, would you mind uploading your image set at http://wilson.bronger.org/calibration?

**Comment by falket** [comment]
Ok understood. Exiv 2 don't recognize focal lenght, exiftool does.

Uploading now. Thank you.

**Comment by bronger** [comment]
There was a bug in `calibrate.py` which prevented it from processing JPEGs for vignetting measurement.  This has not been detected so far because using JPEGs for vignetting is usually not a good idea anyway (there may have been made manipulations with the histogram).  I updated `calibrate.py`.  Moreover, I improved the error messages.
