### ISSUE TITLE
Add camera support Nikon D5600

### ISSUE THREAD

**Issue by battata** [lensfun/lensfun#405]
<camera>
        <maker>Nikon Corporation</maker>
        <maker lang="en">Nikon</maker>
        <model>Nikon D5600</model>
        <model lang="en">D5600</model>
        <mount>Nikon F AF</mount>
        <cropfactor>1.534</cropfactor>
    </camera>

**Comment by sarunasb** [comment]
Entry for Nikon D5600 added.

https://www.digicamdb.com/specs/nikon_d5600/
