### ISSUE TITLE
Calibration data for Sony RX100M6

### ISSUE THREAD

**Issue by csperr** [lensfun/lensfun#499]
I did the steps to calibrate the fixed lens of the Sony RX100 M6 compact camera. You find the attached lensfun.xml. It would be nice if you could include it into the database

Christian

[lensfun-sonyRX100M6.zip](https://github.com/lensfun/lensfun/files/2948526/lensfun-sonyRX100M6.zip)

**Comment by tuxfanx** [comment]
calibration data are completely included in db
