### ISSUE TITLE
Calibration data for Lumix G Macro 30 mm f/2.8 Asph. Mega OIS

### ISSUE THREAD

**Issue by PierrePiveteau** [lensfun/lensfun#510]
I've done all calibrations for the Panasonic Lumix macro 30mm with the GX80.
Thanks to add this lens to the database :)

[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/3054517/lensfun_calibration.zip)

**Comment by tuxfanx** [comment]
merged -->closed
