### ISSUE TITLE
Vignetting calibration for Lumix G 20mm f/1.7 II Asph.

### ISSUE THREAD

**Issue by PierrePiveteau** [lensfun/lensfun#511]
I've done the missing vignetting calibration for this lens with the GX80.
Thanks for adding !

[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/3054572/lensfun_calibration.zip)

**Comment by AxelG-DE** [comment]
Sorry for OT
This lens does not provide LensIDNumber with exiftools. So I wonder, what to put in .exiv2 inorder to get this lense supported???

**Comment by tuxfanx** [comment]
calibration data are completely included in lensfuns DB --> closed
