### ISSUE TITLE
Calibration upload ecbefb

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#57]
Calibration images were uploaded to the directory that starts with “`ecbefb_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

**Comment by schenlap** [comment]
@bronger 
Who is responsible for merging calibration data?

**Comment by bronger** [comment]
I do merging currently.  (But I think about moving to an everybody-can-commit workflow.)
