### ISSUE TITLE
Calibration Nikkor Z 24-70 mm f/4 S

### ISSUE THREAD

**Issue by Affreux666** [lensfun/lensfun#587]
Accurate transmitting procedure not understood (not an expert with english, github, etc) please excuse me!
Data (made with Nikon Z7):

<lens>
        <maker>Nikon</maker>
        <model>Nikkor Z 24-70mm f/4 S</model>
        <mount>Nikon Z</mount>
        <cropfactor>1.0</cropfactor>
        <calibration>
           <distortion model="ptlens" focal="24" a="0.024" b="-0.072" c="0.011" />
           <distortion model="ptlens" focal="28.5" a="0.036" b="-0.127" c="0.119" />
           <distortion model="ptlens" focal="35" a="0.019" b="-0.047" c="0.040" />
           <distortion model="ptlens" focal="50" a="0.012" b="-0.016" c="0.030" />
           <distortion model="ptlens" focal="70" a="0.019" b="-0.041" c="0.071" />
           <tca model="poly3" focal="24.0" vr="1.0006171" vb="1.0001018" />
           <tca model="poly3" focal="28.5" vr="1.0003930" vb="1.0002012" />
           <tca model="poly3" focal="35.0" vr="1.0001500" vb="1.0001782" />
           <tca model="poly3" focal="50.0" vr="0.9999972" vb="1.0000567" />
           <tca model="poly3" focal="70.0" vr="0.9997883" vb="0.9999320" />
        </calibration>
    </lens>
Next time more accurate.
Thanks for lensfun!

**Comment by sboukortt** [comment]
Hi, and thank you for opening this issue. Do I understand correctly that what you gave here is the lens name as it appears in the image metadata?

> Accurate transmitting procedure not understood (not an expert with english, github, etc) please excuse me!

Your username appears to be in French, is there anything in the procedure that I could maybe try to clarify in French? :)

**Comment by Affreux666** [comment]
Hi,
You understand correctly the lens name.
I was unable to attach a file from my computer... must use an external site for a simple text???

Something wrong: "Nikon Z" in cameras make "no standard Nikon FX, Z lenses only"  in lenslist (only with darktable tested)

Good sunny (I hope) sunday!

**Comment by tuxfanx** [comment]
calibration data are completely included in lensfuns DB --> closed
