### ISSUE TITLE
Setup a regular job to build the latest docs

### ISSUE THREAD

**Issue by seebk** [lensfun/lensfun#589]
The latest Doxygen docs can be found in the website repo and should be accessible from 
        
  	https://lensfun.github.io/manual/latest

We could try to "misuse" a Travis CI job to regularly update the docs in the repo. If that doesn't work, one of the developers could maybe setup a cron job on a dev machine. 

In both cases, the job should check if any doc files are changed and only commit files where the content actually changed (avoid cluttering the commit history).

**Comment by 1480c1** [comment]
Updating and deploy docs aren't really considered a misuse of a travis job as they are considered part of the development cycle

**Comment by 1480c1** [comment]
I was able to add a job to build the docs.
