### ISSUE TITLE
Move bug tracker items from Sourceforge to GitHub

### ISSUE THREAD

**Issue by seebk** [lensfun/lensfun#590]
We still need to move the bug tracker items from SF to GitHub. There is a tool that promises to do this automatically, but it has to be tested carefully:

https://github.com/cmungall/gosf2github

I can have a look but won't promise that it will happen soon. If @bronger or someone else can work on this earlier, feel free to do so.

**Comment by bronger** [comment]
Moved.

On SF, the two trackers are read-only now.
