### ISSUE TITLE
Review center X/Y definition in mod_center branch

### ISSUE THREAD

**Issue by seebk** [lensfun/lensfun#592]
I have moved the center x/y parameters back into the lfLens structure as it is not a characteristic of a calibration measurement but of the lens itself. Furthermore if it is part of lfLens it allows to apply all modifications (scaling, tca, ...) in respect to a common lens center.

The implementation is on branch mod_center and needs review. In particular, the tests that have an off-center origin in parts still fail and need adjustments of the reference values.

**Comment by seebk** [comment]
@bronger, this should be fixed now in master, right? Can we close this item?

**Comment by seebk** [comment]
The mod_center branch has been merged and all tests succeed, so I guess I can close this item.

**Comment by bronger** [comment]
Ups, I overlooked this one.  Yes, I heavily tested it and it should be fine.
