### ISSUE TITLE
Tests not compiling if OpenMP not found

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#705]
This is about problems in the `tests/CMakeLists.txt` file.

First, the following two lines appear twice:
```
find_package(OpenMP)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
```

Second, if OpenMP is not found, then `${OpenMP_CXX_FLAGS}` will be the string "NOTFOUND" which leads to compile errors. If OpenMP is strictly required for the tests, then `REQUIRED` should be added to the `find_package` call. If it's not required, then the `CMAKE_CXX_FLAGS` should be changed conditionally based on the `OpenMP_CXX_FOUND` flag.

Reported by: neothemachine

**Comment by danfe** [comment]
> If OpenMP is strictly required for the tests

Is it, actually? Which particular test(s) require it?  For version 0.3.95 it seems I can just delete lines that match `OpenMP` and all 26 (on x86, one less elsewhere because of SSE) tests would build and pass fine.
