### ISSUE TITLE
Please commit your results instead of pull requests

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#79]
@lensfun/lensfun: Please commit your results directly to master from now on.  Create a pull request only if you need feedback.  I will review the additions either way, and will report back important tips.

**Comment by bronger** [comment]
Current pull request will be treated as pull request.  Please don't withdraw them and commit them.

**Comment by junkyardsparkle** [comment]
@bronger: Is there any reason to not delete the forked repositories when merges are done?

**Comment by bronger** [comment]
No.

**Comment by bronger** [comment]
BTW, I invented all of you to the team “calibratiors” because then we can reach everyone more easily with `@lensfun/calibrators` in issues.  Then, I don't have to assign everyone to an issue anymore like here.
