### ISSUE TITLE
Vignetting for 2 Lumix G Vario lenses

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#794]
Hi, I've done the simple vignetting calibration (focusing to infinity) for these lenses:

LUMIX G VARIO 12-32/F3.5-5.6  : Panasonic, Micro 4/3 System, 2, 4:3
LUMIX G VARIO 35-100/F4.0-5.6: Panasonic, Micro 4/3 System, 2, 4:3

It's the first time I tried that, so please do a sanity check on my values. I used a milky glass and put the camera underneath it pointing at the ceiling lamp (ca 2 meters above). The camera was handheld with lens pushing against the glass plate. Lens+Sensor image stabilization was on (no digital stabilization).

The tca and distortion are taken from the existing DB entries.

I used the calibration script from Windows, and it needed a major rearranging: when using multiprocessing on Windows, you need to move most of the "effective" code into `if __name__ == "__main__":`, but leave the function/class definitions outside. This is something that can be done quite easily, but I understand it'd affect readability of the script, when the functions are moved away from the places where they are used. There's also a system program called convert.exe which serves for converting FAT partitions to NTFS, and the calibration script is trying to call this one instead of the ImageMagick executable. Quite dangerous :) If you'd be interested in seeing the working script, I can share it.

Reported by: peci1

**Comment by fajabird** [comment]
Today I tested the lens correction for the following combination (as reported by EXIF)
model: Panasonic DMC-GX80
lense: LUMIX G VARIO 12-32/F3.5-5.6  

The results for me are super bad, vignetting highlights corners way too much - loosing details as e.g. sky becomes a white area (clipping) and distortion is way off too, e.g. convex lines are turned into convex lines from 12mm until around 20mm, from 20mm it seems to be ok - but vignetting keeps clipping details until 32mm.

Sorry - but I think the profiling was done with a broken lense. The distortion characteristics of my 12-32 lense is that at 12mm its very slightly concave but already at 14mm its seems to be good until 32mm. The same goes for vignetting - but this is more hard to judge without measuring.

**Comment by junkyardsparkle** [comment]
@fajabird It sounds like yoiu're applying the corrections to an OOC JPEG; that's not what these profiles are for.

**Comment by fajabird** [comment]
Yes, I copied over JPEG files from cam to pc. For my other cam, a Nikon D50 with two different lenses the results seem fine even for jpeg files. Should I test with raw files instead?

**Comment by junkyardsparkle** [comment]
All Micro Four Thirds cameras apply corrections internally to native lenses which supply this information, so for that format, at least, the profiles only make sense for use in RAW editors (particularly those that don't license the proprietary correction specification, due to being open source or just because they choose not to). Modern fixed-lens cameras and some (most?) other mirrorless formats also do internal software correction. Older DSLRs probably don't, so for those the JPEGs may work, but in general the profiles are created from RAW for cameras that produce RAWs.

**Comment by fajabird** [comment]
Thanks for the comments. I just did RAW vs. JPEG comparisons on both cameras and your absolutely right - while the Panasonic does apply internal correction for JPEG my good old Nikon does not. I find it even more interesting, that distortion on my lenses for the nikon is very minimal but on the panasonic, the amount of distortion in the RAW files is just ridiculous. Its a shame that lenses nowadays seem to be so poor that without software correction they just would be useless.

**Comment by junkyardsparkle** [comment]
Well, Micro Four Thirds was based around the idea of software correction enabling smaller, lighter, cheaper lenses, but people are usually surprised to see just how much is involved in some cases. :-)
