### ISSUE TITLE
Hugin patch link broken in calibration.rst

### ISSUE THREAD

**Issue by sarunasb** [lensfun/lensfun#85]
Is the patch to disable/remove lines in Hugin available? Thanks. otherwise one has to use Hugin 2013...

**Comment by bronger** [comment]
Ah! Gmane went down last week, right.  Very sad, BTW.
I inserted the patch instructions into https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/calibration.rst#hugin-patch.

**Comment by junkyardsparkle** [comment]
(It's line 250 in hugin 2016.0.0 btw.)

**Comment by bronger** [comment]
Thanks, I added it!

**Comment by sarunasb** [comment]
Yes, it works, pretty simple. Thanks!
