### ISSUE TITLE
Add support for vignetting correction for Panosonic FZ200/FZ300

### ISSUE THREAD

**Issue by lapineige** [lensfun/lensfun#875]
Distortion and TCA #259 are already supported for fz200 (and by extension fz300 which uses the same lens), but not vignetting.

How can I help you to create such a profile ?

I can submit RAW files if needed. Using this tutorial ? https://wilson.bronger.org/lens_calibration_tutorial/#id3

**Comment by Sturmflut** [comment]
The current tutorial is located at https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
no pictures up to now --> closed
