### ISSUE TITLE
Canon EF 20-35mm f/3.5-4.5 USM

### ISSUE THREAD

**Issue by gilbertohasnofb** [lensfun/lensfun#878]
Hi, would it be possible to add support for the Canon EF 20-35mm f/3.5-4.5 USM lens? It is not listed under https://wilson.bronger.org/lensfun_coverage.html

**Comment by Sturmflut** [comment]
Someone has to provide calibration images, for more details see https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
no pictures up to now --> closed

**Comment by gilbertohasnofb** [comment]
Apologies but I don't own this lens any longer.
