### ISSUE TITLE
Lens Support Request: Canon IXY 900IS

### ISSUE THREAD

**Issue by mjhborja** [lensfun/lensfun#879]
Hi lensfun team,

Great plugin you guys have in https://seebk.github.io/GIMP-Lensfun/.
I am interested in using this with my Canon IXY 900IS, which is currently not supported in the https://lensfun.github.io/lenslist/. 

The lens specs 28–105 mm f/2.8–5.8, 
and alternative camera names for the camera are: 
[1] Powershot Digital ELPH SD800IS; and
[2] Digital IXY 850IS
 according to https://en.wikipedia.org/wiki/Canon_Digital_IXUS.

\+ Martin

**Comment by Sturmflut** [comment]
Someone has to provide example images, for more details see https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
no pictures up to now --> closed
