### ISSUE TITLE
Lens Support Request: Apple iPad mini

### ISSUE THREAD

**Issue by mjhborja** [lensfun/lensfun#880]
Hi,

Please support Apple iPad mini rear iSight camera with the following specs: 
- f/2.4 aperture
from https://everymac.com/systems/apple/ipad/ipad-mini-faq/differences-between-ipad-mini-ipad-mini-retina-2.html.

\+ Martin

**Comment by Sturmflut** [comment]
Someone has to provide example images, for more details see https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by tuxfanx** [comment]
outdated --> closed
