### ISSUE TITLE
Calibration data for Ricoh GR III

### ISSUE THREAD

**Issue by pulce** [lensfun/lensfun#895]
Please add the attached lens data to the lensfun data base.

Please note: the vignetting.pdf was 72mb, so I shrinked the pdf by turning the vector graphics to images.

[lensfun_calibration.zip](https://github.com/lensfun/lensfun/files/3219458/lensfun_calibration.zip)

**Comment by yeertha** [comment]
Thanks for gathering and submitting this data. Looking forward to seeing it incorporated.

**Comment by junkyardsparkle** [comment]
Added, thanks!
