### ISSUE TITLE
Camera support request Fujifilm X-T100

### ISSUE THREAD

**Issue by saknopper** [lensfun/lensfun#901]
I'd like to request support for the camera mentioned in the subject. It is an entry-level aps-c camera from Fujifilm which supports the X mount range of lenses.

Not to be confused with the X-100T which is a fixed lens camera. (And already included in lensfun)

There is a raw file available on raw.pixls.us, see: https://raw.pixls.us/getfile.php/2676/nice/Fujifilm%20-%20X-T100%20-%2014bit%20uncompressed%20(3:2).RAF

Thanks in advance!

**Comment by junkyardsparkle** [comment]
Added, thanks.
