### ISSUE TITLE
Infer calibration data for larger crop factors from that of smaller crop factors

### ISSUE THREAD

**Issue by sinking-point** [lensfun/lensfun#909]
Suppose we have an image with crop factor 1.5 and calibration data for the lens only for crop factor 1. Take the image and pad it with zeros to the size of a crop factor 1 image. Then, apply the corrections. Finally, crop to the centre to return the image to its original size. The image should be corrected correctly despite the lack of calibration data for the specific crop factor.

Just an idea. Note that this is a proof, not a suggested implementation.

**Comment by sinking-point** [comment]
One approach could be to take full frame calibration images and simply crop them to the size of a crop sensor in that system.

**Comment by bronger** [comment]
Lensfun does this already but with a certain tolerance theshold. The rules are here: <https://github.com/lensfun/lensfun/blob/master/libs/lensfun/database.cpp#L1269>. Unless the calibration sensor size is not smaller than 96% of the image sensor size, the calibration is used.

**Comment by sinking-point** [comment]
Strange. Darktable only corrects for barrel distortion in photos from my Nikon AF-S 50mm f/1.4G on my D3200 (APS-C). Is this because it prefers to use the calibration for the smaller sensor, which lacks CA and vignetting calibration?

**Comment by sinking-point** [comment]
Yes, when I comment out the APC-C calibration it does all corrections. It would be nice if it used the best data it has for all corrections. E.g., in this example, the APS-C barrel distortion calibration and the scaled full-frame CA and vignetting calibration.

**Comment by sinking-point** [comment]
The corrections also don't seem to be scaled correctly for the smaller image sensor, at least for vignetting. The result is excessive brightening of the corners.
![beforeafter](https://user-images.githubusercontent.com/17532243/60108209-28486b00-9760-11e9-81cd-09cf6f96fa1e.jpg)

**Comment by bronger** [comment]
Acknowledged, but this is a separate issue that is due to the fact that Lensfun does not distinguish between "lens" and "calibration". The next release will contain different internal data structures, but the real fix will have to happen later.
