### ISSUE TITLE
Err 111 with lensfun-update-data and fix

### ISSUE THREAD

**Issue by fishcu** [lensfun/lensfun#925]
The `lensfun-update-data` script will try to load the database from the sourceforge server.
However, the data is no longer there and the script crashes with error 111.

Fix: Remove code line 135, `read_location("https://lensfun.sourceforge.net/db/")`

**Comment by fishcu** [comment]
I could not figure out a proper replacement URL for github, however the alternative URL `read_location("https://wilson.bronger.org/lensfun-db/")` is sufficient for now.

**Comment by edcoreweb** [comment]
@fishcu https://wilson.bronger.org/lensfun-db/ is down for me.

**Comment by fishcu** [comment]
Yeah, it seems like there are some problems now. It used to work for me.

So the script should be updated with a working link.
