### ISSUE TITLE
Windows - Can't get hugin-tools or Exiv2 to be located by calibrate.py script

### ISSUE THREAD

**Issue by aliensojurner** [lensfun/lensfun#932]
I was able to get this setup on Mac with only a few issues but on Windows, I've installed Hugin, and put exiv2 in system32 folder. I've added the Hugin install directory to my user and system path, yet every time I run "python calibrate.py" I get "The following packages are missing (Ubuntu packages, names may differ on other systems):
    exiv2  hugin-tools
Abort."

Can someone please help me figure out what the problem is here?

**Comment by bronger** [comment]
`calibrate.py` tries to execute `tca_correct` and `exiv2`, therefore, these two executables need to be in the `PATH`.

**Comment by aliensojurner** [comment]
Thank you for that. I was one sub-directory short for Hugin... I am now facing one final issues with Exiv2. It was missing a slew of DLL files and I've been able to find all but one named cygexpat-1.dll. When running exiv2 from the command line I get the prompt that the specific dll cannot be found. I am assuming the script isn't seeing it because it can't run (but I may be wrong). The direct path to exiv2 is in my user and system PATH. I can't find a place to obtain this dll...Is there another place to download EXIV2 from that contains this or a way to fix it?

**Comment by junkyardsparkle** [comment]
There's some info [here](http://clanmills.com/exiv2/cygwin.shtml) about getting Cygwin builds working (I don't have any experience with that myself, sorry).

**Comment by aliensojurner** [comment]
Thanks but that's leaving me with the same problem. Under the vanilla section for Windows, I have all but the cygexpat-1.dll and I can't find it anywhere. That seems to be the last dll that I need and it's no where to be found.

**Comment by aliensojurner** [comment]
I did find a cygexpat-1 from a dll site finally ( I know those sites are problematic a lot of times but it's the only palace I can find it so far). Now I'm getting ---------------------------
exiv2.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 

I am desperate to get this working. Does anyone have this installed at all on a Windows system and if so do you have a working version of this file or any advice on how to get exiv2 to execute properly?

**Comment by aliensojurner** [comment]
Okay, so I finally found a DLL that worked. However the script still cannot find exiv2. It's in both the user and system paths. If it's in the path and the script still isn't finding it, what could the problem be?

**Comment by bronger** [comment]
As you can see in line 19 of the script, it simply calls `subprocess.call(["exiv2"])`. You may check this directly in Python:

    python3 -c 'import subprocess; subprocess.call(["exiv2"])'

**Comment by aliensojurner** [comment]
FileNotFoundError: [WinError 2] The system cannot find the file specified

That's what I keep getting. I can see that it's not finding the file, but I can drop right to the command prompt and execute "exiv2.exe" right from the prompt in any directory. That would point me to believe it's not in the PATH but I know for a fact that it is 1) because I have manually added it and checked it for both the system and the user, and 2) because I can run the command from anywhere on the command line. Any other suggestions sir?

**Comment by aliensojurner** [comment]
I added shell=True and get 'exiv2' is not recognized as an internal or external command,
operable program or batch file. Making it appear as though it's not in the path, yet it runs from the command prompt just fine. 
subprocess.call(["exiv2"], shell=True)
'exiv2' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bronger** [comment]
I don’t have Windows, so my possibilities and knowledge are limited. With shell=True, though, you may remove the brackets.

**Comment by aliensojurner** [comment]
Do you know anyone who does that may be able to chime in on this issue?

**Comment by aliensojurner** [comment]
Okay so the Windows issue has been resolved. Now the script is running in circles complaining that I'm "attempting to start a new process before the current process has finished its bootstrapping phase". 
"This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module:"

Have you any knowledge on why this would be happening now that it can find all the required packages.

**Comment by aliensojurner** [comment]
If you know anyone who does run Windows could you please point them to this for some feedback?

**Comment by junkyardsparkle** [comment]
Sounds like [this can of worms](https://perfspy.blogspot.com/2017/05/python-multiprocessing-behaves.html), but I don't have a Windows machine to troubleshoot on either.

**Comment by bronger** [comment]
@aliensojurner Do you use the current calibrate.py on master?  @peci1 has prepared Windows support in that. (https://github.com/lensfun/lensfun/pull/291)

**Comment by aliensojurner** [comment]
The Exiv problem is resolved. Now on to speaking with @peci1 about the Windows script.
