### ISSUE TITLE
How to provide RAW files for calibrating ultra wide angle lens?

### ISSUE THREAD

**Issue by jcubic** [lensfun/lensfun#937]
In https://wilson.bronger.org/calibration there is info that image shoult be taken at least in 5 meters away. Can I move closer with 15mm lens? And should the lens be leveled in Z axis or can it be shot little bit higher?

I have 2 lenses I want to give calibration data:

Tamron SP 90mm f/2.8 Di VC USD Macro 1:1 (F017)
Tamron SP 15-30mm f/2.8 Di VC USD G2 (A041)

second generation of the lenses that are already in Lensfun db.

My question is for the second lens, I don't I will be able to shot from 5 meters away to have straight line in proper position, so I would need to be closer and move camera up.

Do you have sample images for ultra wide angle zoom lens?

**Comment by bronger** [comment]
Yes, this is possible.
