### ISSUE TITLE
Panasonic FZ2000/2500

### ISSUE THREAD

**Issue by TheChief79** [lensfun/lensfun#952]
Please add support for Panasonic FZ2000/2500 (same lens, different names) since Affinity and RawTherapee using lensfun. AppleRaw supports this camera, but i dont know, if the plugin file could help you. 

[rw2.panasonic.dmc-fz2500.cam.zip](https://github.com/lensfun/lensfun/files/3465261/rw2.panasonic.dmc-fz2500.cam.zip)

I could use FZ1000 (25-400mm) settings but the lens in slightly diffrent from FZ2000 (24-480mm).

https://www.dkamera.de/media/cache/full/news/panasonic-lumix-dmc-fz1000-vs-lumix-dmc-fz2000-teil-1/Panasonic_Lumix_DMC_FZ1000_vs_FZ2000_Vergleichstabelle.png

If you need more information, let me know

**Comment by sarunasb** [comment]
Please take calibration pictures and upload them (https://wilson.bronger.org/calibration).

**Comment by sarunasb** [comment]
No images supplied.
