### ISSUE TITLE
Tamron 70-200 wrong name in database

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [lensfun/lensfun#957]
The older Tamron 70-200mm (sometimes retronymed the G1 lens) is called `Tamron SP 70-200mm f/2.8 Di VC USD A009` in the database or `Tamron SP 70-200mm f/2.8 Di VC USD` but when I open a NEF in darktable it displays `Tamron SP AF 70-200mm F/2.8 Di VC USD` and fails to apply the right correction.

I don't know if the other names are correct for other lens mounts but on my Nikon it always has this value.

Maybe this can be somehow added as an alias?

**Comment by sarunasb** [comment]
A link to NEF file?

**Comment by Leonidas-from-XIV** [comment]
Here's a NEF with that lens: [spider.nef](https://xivilization.net/~marek/tmp-spider.nef).

If I ask exiftool for the `LensID` then I get `Tamron SP 70-200mm f/2.8 Di VC USD (A009)` which is about the same as in the lensfun db so I assume the error is probably in darktable?
