### ISSUE TITLE
Zeiss Batis 25mm f2 not recognized

### ISSUE THREAD

**Issue by vilim** [lensfun/lensfun#973]
I am using lensfun through darktable, and there seems to be a bug in recognizing my lens (it is in the database, but is not being picked up automatically).

Exiv2 gives the following output:
```
Exif.Image.Make                              Ascii       5  SONY
Exif.Image.Model                             Ascii       9  ILCE-7M3
Exif.Photo.MakerNote                         Undefined 37496  (Binary value suppressed)
Exif.MakerNote.Offset                        Long        1  5310
Exif.MakerNote.ByteOrder                     Ascii       3  II
Exif.Sony2.SonyModelID                       Short       1  (363)
Exif.Sony2.LensID                            Long        1  Manual lens
Exif.Photo.LensSpecification                 Rational    4  250/10 250/10 20/10 20/10
Exif.Photo.LensModel                         Ascii      18  ZEISS Batis 2/25
Exif.Thumbnail.Make                          Ascii       5  SONY
Exif.Thumbnail.Model                         Ascii       9  ILCE-7M3
```

ZEISS Batis 2/25 is also written in Darktable. I would have added the alias to the xml via a pull request myself, but I am not sure of the procedure.

**Comment by FreddieWitherden** [comment]
What does exiftool identity the lens as?

**Comment by vilim** [comment]
`ZEISS Batis 2/25` as listed above 
Thanks!

**Comment by FreddieWitherden** [comment]
So it looks as if the model name: ```        <model>E 25mm f/2</model>``` is wrong and this is why the lens is not being recognised.

**Comment by vilim** [comment]
Exactly. But it is possible that other/older cameras output it as E 25mm f/2, which is why I guess it was put it like this in the first place. There is support for multiple lens aliases, right?

**Comment by vilim** [comment]
> What does exiftool identity the lens as?

Sorry, I did not read this carefully, exiftool (unlike exiv2) lists 
```
Lens Type 3: Zeiss Batis 25mm F2
Lens Type 2: Zeiss Batis 25mm F2
Lens spec:﻿﻿ E 25mm F2
Lens Model: ZEISS Batis 2/25
```
I am not sure which of these fields is relevant.
I think darktable uses the Lens Model, which is also given by exiv2

**Comment by tuxfanx** [comment]
completet
