### ISSUE TITLE
Capitalization Issue - compact-canon-xml

### ISSUE THREAD

**Issue by Pottch** [lensfun/lensfun#974]
Just noticed a few entries in the compact-canon.xml file has some capitalization inconsistencies for the PowerShot models. Confirmed with the EXIF tool that the "S" in "PowerShot" is always capitalized. 

<model lang="en">Powershot ELPH 110 HS</model>  -> PowerShot ELPH 110 HS
<model lang="en">Powershot A1200</model>            -> PowerShot A1200
<model lang="en">Powershot SX60 HS</model>         -> PowerShot SX60 HS

Thanks!

**Comment by tuxfanx** [comment]
done --> closed
