### ISSUE TITLE
Sony a6400 (ICLE-6400) camera entry

### ISSUE THREAD

**Issue by mschulkind** [lensfun/lensfun#981]
The 6400 is supposed to have the same sensor as both the 6300 and the 6500, which are both in `mil-sony.xml`. Neither seem to have any more data than just the crop factor. I added the following locally:

```
    <camera>
        <maker>Sony</maker>
        <model>ILCE-6400</model>
        <model lang="en">Alpha 6400</model>
        <mount>Sony E</mount>
        <cropfactor>1.534</cropfactor>
    </camera>
```

I copied the above directly from the 6500 entry, and now darktable can correctly detect the lens and camera for my photos. Seems like it's worth adding this to the database?

**Comment by juststur** [comment]
Updated as part of fix for #1046
