### ISSUE TITLE
Calibration data for iPhone XS / XS Max

### ISSUE THREAD

**Issue by JLTastet** [lensfun/lensfun#982]
Hi,

I have created [calibration data](https://github.com/lensfun/lensfun/files/3587774/lensfun.zip) (distortion + TCA + vignetting) for the two back cameras of the iPhone XS (and the XS Max which should share the same camera module). To do that, I used the DNG files generated by the ProCamera app. The front (selfie) camera cannot produce raw files using this app.

The two back cameras have fixed focal length and aperture, and the two sensors have different crop factors. I am not sure how this should be implemented in the XML file. I have uploaded a raw file for each of them to https://raw.pixls.us/.

Currently, the lens is not autodetected in Darktable (but the camera is). Manually selecting the 6 mm (tele) lens works fine, and all corrections are applied. However, selecting the 4.25 mm (wide) lens results in no corrections being applied at all. Changing the camera crop factor in the XML file to match the one of the 4.25 mm camera does not improve the situation.

The wide camera presents a very wavy distortion pattern, which results in a bad fit in Hugin (a,b,c ~ O(1)), despite a large number of control points (64). I can upload the .tif and .pto files if needed.

Let me know if you need any additional information.

**Comment by JLTastet** [comment]
It seems that Darktable did not digest the distortion data well for the wide camera. Not sure why :thinking: 

Anyway, removing this distortion entry solves all issues, including camera autodetection :tada: 

Here is the updated XML file: [lensfun.zip](https://github.com/lensfun/lensfun/files/3587809/lensfun.zip)

**Comment by junkyardsparkle** [comment]
Problem might have been due to the distortion line having a focal=4.2 instead of focal=4.25? Just a guess.

**Comment by JLTastet** [comment]
> Problem might have been due to the distortion line having a focal=4.2 instead of focal=4.25? Just a guess.

Indeed, if I change `4.2` for `4.25`, all corrections are now applied!

However, the distortion correction is obviously wrong due to the different crop factor (everything outside the tele sensor area is awfully distorted). Not sure if this affect the TCA and vignetting corrections (they don't look too bad, but they might be sub-optimal).

Do you know if there is a way to handle these multi-camera phones?

**Comment by junkyardsparkle** [comment]
The simple TCA correction is just a scale factor, so crop factor shouldn't matter for that... it might for vignetting, though.

IIRC, the last time I looked at the (new at the time) dual-camera phone issue, the problem was a lack of distinguishing EXIF data, but that looks like not a problem here. If I get a chance I'll look at the actual files later - it's not clear to me what the difference between the "Max" and non-Max camera entries is, or where the 6.118 crop factor is coming from. The crop factor in the lens profile should be the crop factor of the sensor as given in the image with the calibration shot. Should one of the two camera profiles also have that crop factor?

**Comment by JLTastet** [comment]
The Max and non-Max are just two iPhone models with different screen sizes, but the exact same camera module. They nonetheless have different EXIF, so we should probably duplicate everything.

The back camera module consists of two 12MP sensors, each with its own lens:
* The "wide" sensor has a crop factor of 6.118 and its lens is 4.25 mm -> equiv. 26 mm (1x)
* The "tele" sensor has a crop factor of 8.667 and its lens is 6.0 mm -> equiv. 52 mm (2x)

**Comment by junkyardsparkle** [comment]
Ah, so it looks like the problem is still as before: we have a single camera model name, but two different possible crop factors. Maybe something like the "variant" tag as used with the Panasonic compacts with dual aspect ratios could be used... at any rate, this is clearly going to be common now, along with RAW files from phones, so there should be a way to handle it. I'm just not smart enough to figure it out right now. ;)

**Comment by JLTastet** [comment]
I noticed that the EXIF data contains a `Exif.Image.UniqueCameraModel` field, which differs for the two cameras:
* Wide: `iPhone11,2 back camera`
* Tele: `iPhone11,2 back telephoto camera`

I'll have a look at these Panasonic compacts.

**Comment by JLTastet** [comment]
In the meantime, I will see if I can add the corrections for the main (wide) camera, and only TCA for the tele camera (which has shitty image quality anyway). If this works, then we could merge that as a temporary solution.

**Comment by junkyardsparkle** [comment]
If `Exif.Image.UniqueCameraModel` is going to be a standard field, then that's going to need to be integrated into the matching, but that needs to be coordinated with host applications which supply the string for matching.

I would say for now just create distinctly named camera/mount/lens profiles for the tele lens, and if anyone wants to use them, they'll have to select them manually... but maybe somebody else has a better idea.

**Comment by JLTastet** [comment]
Ok, I'll try to add two distinct cameras, and experiment a bit to see if I can still get the matching to work. The number of iPhone XS users relying on lensfun is probably quite small anyway :laughing: 

I have no idea if `Exif.Image.UniqueCameraModel` is a standard field. I could try checking the EXIF of other phones on https://raw.pixls.us/ to see if they use it.

**Comment by junkyardsparkle** [comment]
> I have no idea if Exif.Image.UniqueCameraModel is a standard field.

Well, it's not in [the latest version of EXIF that I know of](http://cipa.jp/std/documents/download_e.html?DC-008-Translation-2019-E), but it [does pop up here and there](https://sourceforge.net/p/lensfun/bugs/49/)... it's clearly what's needed in cases like this one, so it should probably be a policy for applications to present this for matching if it exists, even if it's only a *de facto* standard. The lensfun profile could then use the standard model field for the "pretty" name for both entries, and quietly handle them as distinct... or whatever.

What I don't know is how many current profiles would break if this policy were put into place. Maybe somebody with local access to the raw.pixls.us could do a quick survey...

**Comment by junkyardsparkle** [comment]
I noticed that raw.pixls.us web interface provides handy links for EXIF in search results, so I did a little poking around, and it looks like this tag is a DNG thing: it's present in DNG output from the Adobe converter, from CHDK, from Magic Lantern, as well as DNG-native cameras from Pentax and others. In the typical case, the content was simply the same string as found in the model tag.

It would therefore be sane behavior for an application to present the contents of this tag to LensFun for matching, and perhaps fall back to the model tag if nothing is returned... unless I'm missing something.

**Comment by JLTastet** [comment]
> What I don't know is how many current profiles would break if this policy were put into place.

> It would therefore be sane behavior for an application to present the contents of this tag to LensFun for matching, and perhaps fall back to the model tag if nothing is returned... unless I'm missing something.

If we want the change to be backward compatible, maybe we should do it the other way round? If the maker and lens fields do not result in a unique match, then try with the `UniqueCameraModel` to disambiguate.

**Comment by junkyardsparkle** [comment]
That could work, too, depending on exactly what policy is adopted for creating the profiles. I've created an issue for general discussion about this at #184, which will hopefully attract some additional perspectives on the matter...

**Comment by JLTastet** [comment]
It seems that the distortion issue on the 4.25mm is not due to the different crop factor, but just to the bad fit (large a, b, c coefficients). For now I will just disable this correction, but if anyone has an idea on how to fix it, I can upload the `.tif` and `.pto` files.

The correct crop factor is still needed for the vignetting correction, so I have added another camera `iPhone XS (tele)` with a corresponding mount.

By default, Darktable will automatically select the main camera for all photos taken with the iPhone XS, but I do not notice any correction being applied when the tele camera was actually used. Corrections are applied as expected when manually selecting both the `iPhone XS (tele)` camera AND `iPhone XS back camera 6mm f/2.4` lens.

Here is the updated file: [lensfun.zip](https://github.com/lensfun/lensfun/files/3612818/lensfun.zip)

If I can find some RAW files for the XS Max, I will try to add it too (assuming the same corrections).

**Comment by JLTastet** [comment]
The EXIF data does not seem to be very consistent between apps. So we can probably merge the `lensfun.xml` as-is. Users of the XS Max or other apps will need to manually select the camera and lens.

**Comment by JLTastet** [comment]
@junkyardsparkle I think this `lensfun.xml` can be merged in its current state, even if enabling the corrections for the secondary (tele) lens requires the user to explicitly select this lens from the list. Should I prepare a PR?

**Comment by junkyardsparkle** [comment]
Done. I'm still concerned that there will be a bunch of reports of the auto-applied profile being "wrong", but we'll see... LensFun is going to need a dedicated maintainer if it's going to keep up with emerging situations like this one, I think. :/

**Comment by JLTastet** [comment]
> Done. I'm still concerned that there will be a bunch of reports of the auto-applied profile being "wrong", but we'll see... LensFun is going to need a dedicated maintainer if it's going to keep up with emerging situations like this one, I think. :/

I don't think this is actually an issue, since the corrections are only applied if they match the camera + lens. So we get the correct auto-applied profile for the main (wide) lens, but by default no corrections are applied if the image was taken with the secondary (tele) lens. In the latter case, the correct profile needs to be manually selected from the list. At least in Darktable, I never ended up with a wrong profile being applied.

**Comment by junkyardsparkle** [comment]
Ah, ok. I forgot that the lens is actually different in Exif... not so bad, then. It would be good to get a distortion correction for the other lens added soon, if possible. Changing things like that later can potentially mess with people's edits in non-destructive editors like darktable... although in this particular case I think the danger of that is minimal. :wink:

**Comment by JLTastet** [comment]
> It would be good to get a distortion correction for the other lens added soon, if possible.

I actually tried to generate a distortion correction profile for the wide lens, but no matter how hard I tried, I could not get a decent fit (even when letting all free parameters vary in Hugin). The a, b, c coefficients were typically > O(1), such that the resulting polynomial would take large values, hence *adding* a huge amount of distortion to the image.

I guess this is caused by the wide lens being too far from an idealized rectilinear lens. The distortion pattern seemed very wavy. This might still be correctable by using a look-up table instead of a polynomial fit. I can post the calibration picture and the `.pto` file in case someone wants to have a look. But, honestly, we can probably leave things as they are now since (as you noticed) the set of lensfun users who shoot on iPhone *and* care about distortion is probably very small :)

**Comment by junkyardsparkle** [comment]
> But, honestly, we can probably leave things as they are now since (as you noticed) the set of lensfun users who shoot on iPhone and care about distortion is probably very small :)
The future person getting set up for a nasty surprise could be yourself! :wink: I'd be willing to take a look at the calibration shot if you make it available, now that I did finally get around to building a properly patched Hugin. Maybe it needs to be treated as a fisheye?

**Comment by JLTastet** [comment]
Here is an archive containing the raw file, the `.pto` project, and the `lenses.conf` (for the wide lens only): [Distortion_iPhoneXS.zip](https://github.com/lensfun/lensfun/files/4290046/Distortion_iPhoneXS.zip)

I have not included the `.tif` file because it is quite large, but `lens_calibrate` should generate it. I can add it if needed.

I remember trying to fit the distortion with a fisheye profile at the time, but the fit coefficients were also quite large.

Let me know if you manage to do something useful with these files, or if you need extra files. I also found a better location to take calibration pictures since I took this one, so next time I'll be there I can try to take better pictures for distortion correction.

Good luck ;)

**Comment by junkyardsparkle** [comment]
Only had time for a quick look, but it appears to just be mild "mustache" distortion... I think the problem might be with mixed up numbers for crop and focal length. I'll try to figure it out this evening.

**Comment by junkyardsparkle** [comment]
I just found out I'm going out of town in the morning on short notice, so this might have to wait until Monday.

**Comment by junkyardsparkle** [comment]
@JLTastet I had a chance to play with it a little, and it does seem almost like the frame isn't concentric with the image circle... does this phone do some kind of stabilization or anything else that might cause that? Anyway, this is the best I came up with... the image really should have a straight line closer to the edge of the frame for calibrating, so it might be worth trying another one... the vignetting correction seemed like it was overshooting a little, but that's a common problem with the diffuser-in-front-of-lens method, unfortunately.

I also added the missing aspect ratio tags (assuming the tele camera is 4:3 as well?) which might help a little, and changed some of the naming to be more consistent with conventions for fixed-lens cameras in the database. I'll be away for the next few days...

[iphonexs.xml.txt](https://github.com/lensfun/lensfun/files/4300266/iphonexs.xml.txt)

**Comment by JLTastet** [comment]
You are right that there is some optical stabilization, although it is not advertised much in the app I use (ProCamera). There is also some electronic stabilization, but only for JPEGs. I will try to take some better calibration shots (without the stabilization) when I have the opportunity to do so.
