### ISSUE TITLE
Lens distortion model missing for Canon EF 50mm f/1.8 STM APS-C Crop Factor 1.613.

### ISSUE THREAD

**Issue by laituckweng** [lensfun/lensfun#997]
Copied distortion model from other entry crop factor 1.005 (Canon 6D), seems to work well.

**Comment by tuxfanx** [comment]
no pictures available for calibration, see [here](https://wilson.bronger.org/calibration) and [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)
